crengine/include/lvfntman.h
crengine/src/epubfmt.cpp
crengine/src/lvfntman.cpp
crengine/src/lvtinydom.cpp

fontface must be the same as shown in koreader's font selection menu. 
I also found a bug in this version of crengine related to "font-style:Italic;", which may cause words overlap when define Italic style. The newest version of crengine have fixed this. I wonder if you can update it in koreader-base. I have tested the newest version with koreader, it works well.
the left is the newest version of crengine with my patch
the middle is the current version in koreader-base
the right one is the current version with my patch
the @font-face used of the tested book is 
```
@font-face{
src:local("STSong"),local("FZSongS-Extended"),local("华文宋体"),local("Song S"),local("Droid Sans Fallback");
font-family:'Song';
}
```
here is the newest crengine with my patch. …

support "local" in css

---

crengine/include/cssdef.h
crengine/include/lvdrawbuf.h
crengine/include/lvrend.h
crengine/include/lvstyles.h
crengine/src/lvdrawbuf.cpp
crengine/src/lvrend.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvstyles.cpp
crengine/src/lvtinydom.cpp

support all CSS Border Properties, fully working for block and
paragraph. partially working for tables as they are rendered in different
ways. I may work on tables in the future.
border	Sets all the border properties in one declaration
border-bottom	Sets all the bottom border properties in one declaration
border-bottom-color	Sets the color of the bottom border
border-bottom-style	Sets the style of the bottom border
border-bottom-width	Sets the width of the bottom border
border-color	Sets the color of the four borders
border-left	Sets all the left border properties in one declaration
border-left-color	Sets the color of the left border
border-left-style	Sets the style of the left border
border-left-width	Sets the width of the left border
border-right	Sets all the right border properties in …

support CSS Border Properties

---

crengine/src/lvrend.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvxml.cpp

*add support of text values for border width,like "thin","thick","medium"
*fix several typo
*add all html color names
*bypass  \<![CDATA] in <style> tag. make it possible to test against epub-conform epubs from idpf. The results were not bad,passed half of the tests in css2.1/s8.5 ,which is about border property.
*tweak page spilting for borders.

several fix

---

cr3gui/CMakeLists.txt
cr3gui/data/hyph/languages.json

This will be used for automatically choosing the hyphenation dictionary based on the document language.

Auto-hyphenation: add JSON index for hyphenation dictionaries and languages

---

crengine/include/lvstsheet.h

tested on a few books used to crash koreader when switch embedded style on and off

fix crash when updating style sheet(from upstream)

---

crengine/src/hyphman.cpp

when len==63, it may crash as well

prevent crash

---

crengine/include/cssdef.h
crengine/include/lvdrawbuf.h
crengine/include/lvrend.h
crengine/include/lvstyles.h
crengine/src/lvdrawbuf.cpp
crengine/src/lvrend.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvstyles.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp

add css support:
background-image: support one image per element
background-position: do not support x% y% or xpos ypos only support keywords like "left top"
background-repeat: support repeat,repeat-x,repeat-y
background: color,image,repeat, position must be in order, use default for missing properties
Fixed one bug releated to padding on left or right. set any paragraph's left or right padding to 50px or 100px will be easier to observe this bug. The format will change when any word is selected, and there is a distance equal to padding between actual word and area to select the word.

add support for background-image and one fix

---

cr3gui/data/epub.css
crengine/include/cssdef.h
crengine/include/lvstyles.h
crengine/include/lvtextfm.h
crengine/src/lvrend.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvstyles.cpp
crengine/src/lvtextfm.cpp

1. support table borders , border-collapse(simple) and border-spacing.
2. support image's height and width properties, in px or %. Disabled auto
zoom in of low resolution images. Now it only zoom out large images to
fit the screen.

Table border and image zoom

---

crengine/src/lvxml.cpp

convert printable windows-1252 code (128-159) to Unicode counterpart.

fix some "?" in ebooks

---

cr3gui/data/epub.css
crengine/CMakeLists.txt
crengine/include/lvtinydom.h
crengine/src/lvrend.cpp
crengine/src/lvstyles.cpp
crengine/src/lvtinydom.cpp

1. floating punctuation often causes problem or bad layout of tables
2. fixed some typos
3. a bug related to page-break

disable floating punctuation in table and several fixes

---

crengine/include/lvxml.h
crengine/src/lvdocview.cpp
crengine/src/lvfntman.cpp
crengine/src/lvstring.cpp
crengine/src/lvxml.cpp

Instead of a very unfriendly 'Error: unknown format' message.
This issue has been discussed in issue #4 (https://github.com/koreader/crengine/issues/4)
This change fixes following issues,
1. Cannot open a book with only several invalid characters in top 3.2K.
2. Cannot open a book without spaces or newlines.
3. Crash if a book contains an invalid characters after 3.2K. (It should crash, but the requirement is a little bit complex, I have not tried to build a case to actually crash it.)
This change won't fix a non utf-8 file which contains several invalid characters in top 3.2K. It will only render garbage. A better solution should be calculating an invalid characters ratio, fail only when the ratio is over a certain bar. Which I believe is a common solution across different text file …

Add LVTextRobustParser to force using utf-8 encoding to open unknown format text file

---

crengine/src/lvrend.cpp

This bug only affects fixed font-size style which is not recommended in
ebooks. it is obvious as fontsize*basefontsize/(256*18) usually returns
0 and cre's minimum font size is 8, so it always shows these text in 8px
font.

bug of fixed font size

---

crengine/src/lvstsheet.cpp

Relative font sizes are specified in terms of absolute size keywords
instead of fixed ratios but crengine doesn't support those yet.

Initial implementation of "font-size: smaller" and "larger"

---

crengine/src/lvdrawbuf.cpp

Should not dither if bpp is 8bit

fix #2230 fb2 cover turns black in 8bit gray drawing buffer

---

crengine/src/lvtinydom.cpp

Holding text in list item was triggering a segmentation fault.
Sample file for testing the segfault : [hold_on_li.html.txt](https://github.com/koreader/crengine/files/706235/hold_on_li.html.txt)
First line change is enough to fix the segfault.
And now that it do not segfault, and selected word or text is mostly fine, I noticed it was not fine when the list item text contains some italic, or some spans (some text before the holded word, back to some words from the previous paragraph or list item, was selected instead). The next 3 changed lines fix that.
I debugged that with printf()s following the function calls :| , and noticed that this `->getRendMethod()==erm_list_item` was often along the `->getRendMethod()==erm_final` at some other parts of the code, and took my chance :)
If does fix …

Fix segfault when holding on list item text

---

crengine/include/lvdocview.h
crengine/include/lvtinydom.h
crengine/src/lvdocview.cpp
crengine/src/lvtinydom.cpp

Possible fix for https://github.com/koreader/koreader/issues/2412
I added an optional parameter strictBounds=false to the functions in the call chain, so that this code is not executed for existing calls to these functions: so no risk of side effects.
It would only be used in cre.cpp for links with this:
```
--- a/cre.cpp
+++ b/cre.cpp
@@ -912,7 +912,7 @@ static int getLinkFromPosition(lua_State *L) {
int y = luaL_checkint(L, 3);
lvPoint pt(x, y);
-       ldomXPointer p = doc->text_view->getNodeByPoint(pt);
+       ldomXPointer p = doc->text_view->getNodeByPoint(pt, true);
lString16 href = p.getHRef();
lua_pushstring(L, UnicodeToLocal(href).c_str());
return 1;
```
It works perfectly on my Kobo.
But it is less perfect on the emulator... where there's some remaining area that are still …

Fix for links clickable out of bounds

---

crengine/include/lvimg.h
crengine/src/lvimg.cpp

Parsing and rasterisation provided by nanosvg (some svg tags like text, span and images are not supported).
Only svg image included as files in the .epub are supported (embedded svg tags in html are not).
See https://github.com/koreader/koreader/issues/2668
It will be followed by a small addition to cre.cpp in getImageDataFromPosition to get a PNG version of a SVG image, as MuPDF does not yet support SVG.

Added support for SVG images

---

crengine/include/lvdocview.h
crengine/include/lvtinydom.h
crengine/src/epubfmt.cpp

Found out there was often an interesting (and often long) `<dc:description>` in epub metadata, that we may want to make available to KOReader for display in `Book Information` (and extracted and stored in CoverBrowser plugin cache database). This will be followed by a small patch to base/cre.cpp.
I also added extraction of multiple `<dc:subject>`, which are often used as keywords or categories (I named the methode `getKeywords()`, as this may be implemented for other formats (html, fb2, pdb...), where the multiplicity may have more sense for Keywords than for a possibly single Category - Keywords feels also more generic than Categories).
On the PDF side, there are 2 interesting (most often not) metadata that KOReader does not currently display …

epub: extract description and subjects metadata

---

crengine/src/lvimg.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp

- #2908
- in rare circumstances, image height being 0 (integer dividing result is less
than 1) causes crash
- #2386 and maybe other weird epub crash
- there is a function called autoboxchildren(), which is to remove
empty nodes when openning a new book. autoboxchildren() will be called
again when the embedded styles is turned off. usually it will not cause
problem.
- if there is an empty `<br/ class="block">` tag (css: ``.block { display: block;}``) 
in the epub and the book is large enough, it will crash in unpredictable ways.
- with above embedded style, the `<br/> `tag was stored as a block node, if
embedded style is off, it is treated as inline node. I suspect after the
cache file is saved it does not allow some node manipulation because
turning off emmbedded when the book is openning …

fix #2908,#2386 cre crash, and better handling of gifs

---

crengine/src/lvstsheet.cpp

I've seen some books with styles like:
```
h1.Heading-1 {font-size:1.81818181818181em;font-style:normal;font-variant:normal;font-weight:bold;margin-bottom:1.84251968503938em;margin-left:0em;margin-right:0em;margin-top:2.97779527559056em;page-break-after:auto;page-break-before:auto;text-align:center;text-indent:0em;text-transform:none}
p.Endnote {font-size:0.909090909090909em;font-weight:normal;margin-bottom:0em;margin-left:1.69511811023622em;margn-right:0em;margin-top:0em;text-align:justify;text-indent:-1.69511811023622em}
```
The parsing of these very long `font-size:0.909090909090909em` was giving a size of 0 (which crengine would rendered with a very small size, but not a null size), because the `int frac` and `int frac_size` were overflowed.
I could have changed them to type `long`, …

Fix parsing of long decimal values in css

---

cr3gui/data/hyph/Dutch.pattern
cr3gui/data/hyph/Spanish.pattern

CRengine doesn't respect the dot(`.`) in the dictionary. Instead of a dot(`.`) we should use space(` `).
After this change hyphenation in Spanish and Dutch should works better.

Fix Dutch and Spanish hyph dictionary

---

crengine/src/lvfntman.cpp

Avoid some infinite loop somewhere (couldn't track where) when no fallback font is defined.
Droid Sans Mono is such a font that is not accepted as a fallback (couldn't see why...).
Closes https://github.com/koreader/koreader/issues/3152
edit: for reference, as this may happen again in other contexts:
One thing that gets visited by this infinite loop is:
https://github.com/koreader/crengine/blob/e2dc17c4721f52077932b1948a44022e403ed759/crengine/src/lvfntman.cpp#L970-L980
It should return the replacement char in the original font, but it returns false when this replacement char is not found either in the original font. So there must be somewhere some place that does not like getting `false` and loop...
An option to fix this would be, instead of returning false, if the def_char is not found, …

Keep previous fallback font if new fallback font fails

---

crengine/include/lvfntman.h
crengine/src/lvfntman.cpp
crengine/src/lvrend.cpp

Will be used from koreader's lua side to make the default font used when renderer request a font when dealing with the `font-family` css style: `serif`, `sans-serif`... or font not found (and so, when Embedded Fonts are disabled).
Without that, the first default font set will always be used: if an other default font is set, it is used only for text that has no font-family style.
This should fix the behaviour described at https://github.com/koreader/koreader/pull/3149#issuecomment-326002177.
Details:
when rendering styles, when meeting a "font-family:" style, the renderer calls `GetFont()` with characteristics from the style stack (italic, size, weigth...) to get the font to use.
This `GetFont()` loops thru all the available fonts, compute a score number about how well that font matches …

Allow setting a bias to fonts for them to be prefered in CalcMatch algorithm

---

crengine/src/epubfmt.cpp

Series number is stored internally as string, but there was a unnecessary integer conversion. This allows koreader to get `The super serie #2.5` (see https://github.com/koreader/koreader/issues/3347)
This is just for epub.
There is another part of code that may do it for fb2 (?), but as it's a bit more complicated and I have no fb2 to test with, I prefer not to touch it.
https://github.com/koreader/crengine/blob/8eefe54e40e4c3f56392e7d8ee2fe43848d53256/crengine/src/lvtinydom.cpp#L5629-L5640

(epub) Return Series Number as string

---

crengine/src/epubfmt.cpp

Only needed for Series, whose text is put as xml element attributes by calibre (other metadata are all in text elements and are already correctly decoded). (see koreader/koreader#3347)
Sample epub content;opf file:
```
<meta name="calibre:series" content="les &toto; g&ezauts blah &amp; les couleurs"/>
<meta name="calibre:series_index" content="5.5"/>
<meta name="calibre:title_sort" content="Il a vu rouge"/>
<dc:description>&lt;div style="text-align: justify;"&gt;Dans ...&lt;/div&gt;</dc:description>
<dc:title>Il a vu rouge &amp; noir</dc:title>
<dc:subject>Policier</dc:subject>
<dc:subject>Rouge &amp; noir</dc:subject>
```

(epub) decode XML charref in Series metadata

---

crengine/include/lvtinydom.h
crengine/src/lvtinydom.cpp

See details in https://github.com/koreader/koreader/pull/3656 and https://github.com/koreader/koreader-base/pull/595.
Fix a few coding errors (probably from original author when copy'and'pasting the forward section into a reverse section, and forgetting to replace/update a few things - and some > vs >=), which would result in:
- reverse search: `<span>1234stuff56789012345</span>` : `stuff` was not found because reverse lookup stopped at text[5] (5 being the length of `stuff`)
- reverse search: `<span>stuff123456789012345</span>` : `stuff` was not found because reverse lookup stopped at text[1] (once previous was fixed)
- forward search: `<span>123456789012345stuff</span>` : `stuff` was not found because forward lookup stopped at text[-1]
Also, in reverse code, a `_start` (that should be …

cre:findText(): fix some coding errors

---

crengine/src/lvtinydom.cpp

Follow up to #94: findText() was not stopping at maxHeight, and was searching until (and returning results from) end of document.
(We may now accumulate words while not yet setting `firstFoundTextY` - we wait till `maxHeightCheckStartY` reached - so the condition needed to be changed as a condition on _firstFoundTextY not yet set_ instead of _no word found_).

cre:findText(): fix my coding errors

---

crengine/include/lvtinydom.h
crengine/src/lvtinydom.cpp

To get the accurate xpointer to the `<A>` elements in cre.cpp's getLinkFromPosition() and getPageLinks().
I need more precise xpointers for https://github.com/koreader/koreader-base/pull/597.
Because of some bugs in crengine I can't pinpoint (yet), it happens, mostly in the same complex epub (some wikipedia) that are already messed up (tables missing), that the xpointer returned (by https://github.com/koreader/koreader-base/pull/597, but also by the methods this PR adds) is wrong, and points to some other elements (some other `<a>` only?) in the same `<p>`. I don't want to use it as it may be on previous page, and would make things worse.
These new methods will allow verifying the quality of the a_xpointer, simply by getting its position and calling getHRef again on it: if the a_xpointer …

Add getHRef(a_xpointer) methods

---

crengine/include/lvtinydom.h
crengine/src/lvtinydom.cpp

See https://github.com/koreader/koreader/issues/3261#issuecomment-348710821 for why not compressing data saved in cache can be a good thing (speedup of many things, but uses more disk space).
It had to be specified at compile time with:
https://github.com/koreader/crengine/blob/6e37d80dd638211c35e7ed9892e476aaacc5a9a1/crengine/src/lvtinydom.cpp#L20-L23
but we will now be able to have the same effect as it being 0 by calling at run time, from cre.cpp: `compressCachedData(false)`.
Some updated numbers (with the same book as in https://github.com/koreader/koreader/issues/3261#issuecomment-348710821 - dunno why I get worse times today, may be I had a non-debug emulator build at the time...)
compression| cache before | load time | render time | close time | page change time| resulting cache …

Allow toggling cache data compression at run time

---

crengine/include/lvtinydom.h
crengine/src/lvdocview.cpp
crengine/src/lvrend.cpp
crengine/src/lvstyles.cpp
crengine/src/lvtinydom.cpp

Now that I know [how to make crengine output some logs](https://github.com/koreader/crengine/pull/99#issuecomment-364692377), I get to see a bit more what happens and when :)
I noticed that, when loading from cache, we almost always got:
```
2018/02/26 12:10:06.6552 WARN checkRenderContext: Style hash doesn't match 9d95bb50!=a7379213
2018/02/26 12:10:06.6552 WARN rendering context is changed - full render required...
```
so the data from the cache was trashed, and a full rendering was done :( (only the DOM tree was kept and XML parsing still avoided).
I tracked it down to changes introduced in #40 and #45 (pinging @frankyifei for info), that the first commit here fix. Commit message:
```
Fix styles cache corruption
When a style is applied to a node with el->setStyle(newstyle), a hash of …
```

Cache re-use fix, warnings, and tunable

---

crengine/src/lvdocview.cpp

Clearer and shorter explanation of what I tried to describe at https://github.com/koreader/koreader-base/pull/601#discussion_r171065144

Clearer comment about TOC loaded from cache optimisation

---

crengine/src/lvrend.cpp
crengine/src/lvtinydom.cpp

I had been trying to figure out this bug every other month, and I'm glad I finally found a so small fix :)
It was quite noticable on Wikipedia articles saved as epub, that often have a multi-pages table (biography elements, numbers, various factual infos) at start of book.
It would display all fine on first opening, but when you change some layout option, or font sizes (or just toggle `Embedded fonts`, which should have zero impact on the rendering), the table would be messed up, with some big parts of it missing, and the number of pages would have decreased !
Also, it you then switch from `page` mode to `scroll` mode, it's all fine in scroll mode! and bad again when you switch back to `page` mode. (I also initially thought it was a problem with cache, but it was not).
It was that some …

Fix some re rendering issues (mostly with tables)

---

crengine/src/lvtinydom.cpp

Fix https://github.com/koreader/crengine/pull/102#issuecomment-369920620
If some compressed chunk would once uncompressed be > 256KB (`UNPACK_BUF_SIZE = 0x40000`), it would not fit in the buffer and cache loading would be abandoned, causing a full reloading and rendering.
Fixed this by having in ldomUnpack a loop so we can call inflate() as many times as it is necessary to get the full chunk.
With  @Eduardomb22 's problematic book:
```
[saving]
[...]
deflate() done: 462 > 329
deflate() done: 419564 > 63895
deflate() done: 13164 > 5994
[...]
[loading]
inflate() done 329 > 462
inflate() additional call needed (63895 > 262144) [this would have cause failure to unpack]
inflate() done 63895 > 419564   [but now we can complete  it]
inflate() done 5994 > 13164
[...]
```
Also added this loop in …

Fix cache decompression bug that would invalidate cache

---

crengine/src/lvdocview.cpp

On some pages (eg: that ends with some padding between an image on this page, and some text on next page), there may be some area which is rendered "final" without any content, thus holding no node. We would then get no xpointer for end of page (and features that use it would fail, ie: word selection, `getCurrentPageLinks()`, `getPageText()`).
But we can get a xpointer by looking a few pixels back the height of page.
For example, on this page (showing next page just below), swipe to follow nearest link would fail (while there are footnotes links):
<kbd>![page1](https://user-images.githubusercontent.com/24273478/37020527-568d1878-211c-11e8-936b-49678485f5c2.png)</kbd>
<kbd>![page2](https://user-images.githubusercontent.com/24273478/37020529-59364108-211c-11e8-8da6-63c1f196431d.png)</kbd> …

Fix getPageDocumentRange() on some pages

---

crengine/src/lvtinydom.cpp

References https://github.com/koreader/koreader/issues/2859

Add list-style-type: none

---

crengine/include/lvmemman.h
crengine/include/lvptrvec.h
crengine/include/lvref.h
crengine/include/lvrefcache.h
crengine/src/lstridmap.cpp
crengine/src/lvstring.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp
crengine/src/pdbfmt.cpp

Attempt at fixing warnings from #106. Just to see what cppcheck says.
Don't merge yet: it compiles, it seems to work, and my C skills warning still applies :) and there is at least one which I doubt:
This one has 2 `*` more at start than in the `sizeof()`
```c
-            rows = (_Ty**) realloc( rows, sizeof(_Ty)*nrows );
+            rows = cr_realloc( rows, nrows );
```
All the others have one `*` more at start than in the `sizeof()`
```c
-            _list = (T**)realloc( _list, size * sizeof( T* ));
+            _list = cr_realloc( _list, size );
```
Added a `inline` to this cr_realloc , so I don't have to worry about performance impacts (libcrengine grows by 1 KB only, so it's negligeable).

Fix cppcheck warnings

---

crengine/src/lvpagesplitter.cpp
crengine/src/lvrend.cpp
crengine/src/lvtinydom.cpp

Fix bug reported at https://github.com/koreader/crengine/pull/102#issuecomment-371266353
Any tall row (row height higher than page height) in a table could mess the rendering of the few first rows.
(Because of a typo in lvrend.cpp: the `emptycontext` was created for that purpose, but the author just forgot to use it on the next line).
Also, such tall row content would be truncated to the page height and the overflowed content would
simply not be displayed. So, added `SplitLineIfOverflowPage()` to deal with such rows.
[Sample file for testing](https://github.com/koreader/crengine/files/1794781/Direito_tables_test.epub.zip) before/after, made out from the chapter in question from @Eduardomb22 's book, plus some added tests with (randomly found) tall images.
Thsi PR just fix the page mode …

 Fix page-mode rendering of tables with tall rows 

---

crengine/src/lvtinydom.cpp

Crash with fatal error when max nodes limit reached instead of segfault (to ease discriminating bugs).
```
t:1048574
t:1048575
t:1048576
FATAL ERROR #1003: allocTinyNode: can't create any more text nodes (hard limit)
```
Copied from https://github.com/koreader/koreader/issues/3459#issuecomment-371751375 :
Some book crashes with a segfault, when it reaches the point when there are 1024 * 1024 = 1048576 text nodes.
There is a hardcoded limit of the number of 1024-nodes slots, which is 1024:
https://github.com/koreader/crengine/blob/052637f1f4ca831fd03aafab89df8358d8ca0f49/crengine/include/lvtinydom.h#L364-L378
I thought we could just increase it to 2048, but it segfaults elsewhere.
There are some other design choices (good for limiting resources usage) that limits this to 1024: …

Crash with fatal error when max nodes limit reached

---

crengine/src/lvdocview.cpp

`getCurrentPageLinks()` (used when swipe to follow links is enabled) returns ldomXRange objects for links' content, that we can't build on empty links.
edit: `elem->getChildNode(0);` expects to have children, and it returns something (a node, widh id 32, so may be the root node) even when there is no child, which `if (node)` let pass - so it requires calling `hasChildren()` before calling `getChildNode()`.
Solves the crash reported in https://github.com/koreader/koreader/issues/3731.
For this book, it was caused by empty calibre tags with id for page changes (ala kepub I guess):
```html
The next census, compiled <a epub:type="pagebreak" id="page12" class="calibre1"></a>in 2011 and published at the end of 2012
```
If it had content, we would get in KOReader (on this page, which has another …

Fix crash on following empty links

---

crengine/include/lvtinydom.h
crengine/src/lvdocview.cpp
crengine/src/lvtinydom.cpp

Fix TOC and links with books with many footnotes, links and backlinks.
Attributes values (just like element names and attribute names) are strings stored in a table, and later referenced only by an integer value that points to this table entry.
These integer values were stored in a `lUInt16` slot, limiting their number to 0-65535. When going above this limit, it started again at 0, overriding previous references, which messed attribute string retrieval (eg: 2nd book attribute was then mapped to the value set by the 65537th attribute).
So, id= and href= were wrong, impacting TOC entries and links.
We now store them in a `lUint32` slot, allowing for a lot more different attribute values.
This fixes TOC and links on a french Bible (TOB), where every of the 30 000 verses are like:
```html
<a …
```

Allow for more than 65535 different attribute values

---

crengine/include/epubfmt.h
crengine/include/lvdocview.h
crengine/src/epubfmt.cpp
crengine/src/lvdocview.cpp

This adds an optional parameter to `LoadDocument()`, that will be used only by coverbrowser plugin for metadata and cover extraction (so extracting metadata from a big book can take 3s instead of 120s).
It will return early when metadata are obtained, and avoid the full document loading (XML parsing, DOM tree building).
Only implemented for EPUB for now (HTML needs XML parsing, and I don't really know much about the other formats).
Will need small mods to `cre.cpp` and `credocument.lua` to pass up this parameter.

Allow for quicker loading when ony interested in metadata

---

crengine/src/pdbfmt.cpp

Cancels out 077e88650ffea1a7cf26fb43120cd66191570068
Upstream commit hash is a712fa235cfb257410d7113fd5e6932acb1bc1b5

Upstream fix for MOBI format detection

---

crengine/src/lvstream.cpp

See https://github.com/koreader/koreader/issues/2959#issuecomment-373698790. Should fix opening of such books.
This case detection was there in the code, with fallback values, but these were not always used later in the code. So, just use them.

Fix opening of some zip files (and epub detection)

---

crengine/include/lvtinydom.h
crengine/src/lvtinydom.cpp

(As noticed in https://github.com/koreader/koreader/pull/3740)
`tinyNodeCollection::calcStyleHash()` is called on each rendering (at each page turn) to check nodes have not changed, so that previous rendering info can still be used.
It was looping thru all the nodes to compute some hash (each styles hash themselves are hopefully cached), which is really expensive (30% of page render time on a small book, 95% on a big book).
As nodes and their styles/fonts can only change at some occasions, it is best to use a cache for this computed value, that we reset only on such occasions.
I'm quite certain nodes do not change except when we do an explicit re-rendering when some other stuff is changed (noticed by some of the other hashes change: default font, stylesheet...)  so we would even have no …

Optimize tinyNodeCollection::calcStyleHash()

---

crengine/src/epubfmt.cpp

Speedup loading EPUB metadata by returning early when no cover to find, or as soon as we find the cover: we don't need to look at all the other items. Followup to #123.

Speedup loading EPUB metadata

---

.ci/script.sh

Ignore *.h for now because clang-tidy thinks it's C. They would need to be renamed to *.hpp to fix that issue.
Also ignore shellcheck warning for base CI.

[CI] Fix minor clang-tidy issues

---

crengine/src/epubfmt.cpp
crengine/src/lvtinydom.cpp
crengine/src/props.cpp

I have some EPUB with > 3000 individual HTML files, that take 10 seconds to open from cache on my device, 3 seconds on the emulator. With this, it opens in 1 second on the emulator, so I expect 3-4 seconds on the device.
Before:
```
2018/03/18 09:23:28.8143 DEBUG Parsing opf
2018/03/18 09:23:28.8477 DEBUG Using font mangling key abcde...
(we will be avoiding this, that is not needed when loading from cache)
2018/03/18 09:23:28.8478 DEBUG opf: reading items
2018/03/18 09:23:28.8478 WARN EPUB coverpage file: cover.jpeg
2018/03/18 09:23:28.8482 WARN EPUB coverpage image is correct: 562 x 853
2018/03/18 09:23:29.6267 DEBUG opf: reading items done.
2018/03/18 09:23:29.6268 DEBUG opf: reading spine
2018/03/18 09:23:30.4992 DEBUG opf: reading spine done
2018/03/18 09:23:30.5000 DEBUG opf: closed …
```

Speedup loading from cache EPUB with many files

---

crengine/include/lvtinydom.h
crengine/src/lvstring.cpp
crengine/src/lvtinydom.cpp

Even when loaded from cache, and no change made in rendering (layout, styles, fonts), the cache was mostly rewritten when closing the document, introducting a long pause (>10 seconds) when leaving a big document.
This PR prevents this: cache will be rewritten only when rendering has been changed (or when some other obscure parts of the code decide to write themselves stuff to cache).
(There is another flag named `dirty` that is set when writes have started, and unset when all are done - I named this one `stale` to avoid confusion.)
Note that the bug with font family described at bottom of https://github.com/koreader/crengine/pull/100#issue-171740521 is still there: with some books, after changing renderings, and so updating cache (before or after this PR), on next opening, this cache …

Avoid rewriting cache file when no change were made

---

crengine/include/fb2def.h
crengine/src/lvtinydom.cpp

See https://github.com/koreader/koreader/issues/3782
This adds support for `<ol start=N>` and `<li value=N>` attributes, and allows zero and negative values for decimal numbering.
This HTML (texts truncated) snippet:
```html
<ol class="list_">
<li value="2" class="block_18">(arts. 10 e 927, Â§1Âº) Para a formaÃ§Ã£o do precedente, somente podem ser usados argumentos submetidos ao contraditÃ³rio. <i class="calibre5">(Grupo: Prec
</ol>
<p class="block_17">Â| </p>
<ol class="list_">
<li value="3" class="block_18"></li>
<li value="3b" class="block_18"></li>
<li value="0" class="block_18"></li>
<li class="block_18"></li>
<li value="-27" class="block_18"></li>
<li class="block_18"></li>
<li value="9" class="block_18"></li>
<li class="block_18"></li>
</ol>
<p class="block_19">Â| </p>
<ol …
```

Supports <ol start=N> and <li value=N> attributes

---

crengine/src/lvdocview.cpp

Fixes #138.
The value comes from the largest currently common maximum texture size.
Common values include:
* 8192
* 16384
* 32767
My laptop with built-in Intel graphics:
```
$ glxinfo -l | grep GL_MAX_TEXTURE_SIZE
GL_MAX_TEXTURE_SIZE = 16384
GL_MAX_TEXTURE_SIZE = 16384
```

[fix] Increase maximum LVDocView::Resize() width/height to 32767

---

crengine/src/lvtextfm.cpp

Happened when changing style (epub>html or epub>clear all) on a Wikipedia article (Statistics.EN.epub) that has, in its section `Find more about Statistics at Wikipedia's `, 7 times:
`<li style="min-height: 31px;"><span style="display: inline-block; width: 31px; line-height: 31px; vertical-align: middle; text-align: center;"><img src="images/img00011.png" style="width: 27px; height: 27px" alt=""/></span><span style="display: inline-block; margin-left: 4px; width: 182px; vertical-align: middle;"><a href="https://en.wiktionary.org/wiki/Special:Search/Statistics" class="extiw" title="wikt:Special:Search/Statistics">Definitions</a> from Wiktionary</span></li>`
(the few other Wikipedia epubs I looked at don't have any vertical-align).
Haven't investigated at all what this code (coming from …

Fix possible segfault with style vertical-align

---

crengine/src/hyphman.cpp

Ignore words (obtained from patterns) larger than MAX_PATTERN_SIZE (instead of having non-null-terminated strings and using corrupted words while hyphenating).
Warn when encountering such too large words, and output a CRE WARNING with the value to increase MAX_PATTERN_SIZE to.
See discussion in https://github.com/koreader/koreader/issues/3848#issuecomment-380863368 and especially https://github.com/koreader/koreader/issues/3848#issuecomment-380918481
This outputs now, with the current `#define MAX_PATTERN_SIZE  9`, which selecting each of our hyph dicts:
```
CRE WARNING: ./data/hyph/Catalan.pattern: some hyphenation patterns were too long and have been ignored: increase MAX_PATTERN_SIZE from 9 to 10
CRE WARNING: ./data/hyph/English_GB_hyphen_(Alan).pdb: some hyphenation patterns were too …
```

Hyphenation: deal with too large pattern words

---

crengine/src/lvtinydom.cpp

This allows getting links and highlighting text in table cells.
Previously, it worked only on the first cell of a row, and highlighting was incoherent when done in secondary cells.
Noticable on Wikipedia EPUBs where we have at start and at end of article often huge tables full of links, where links were simply not working. Also allows following footnotes in these tables.
Highlighting also works now in table cells, with some possible strange results when crossing cells (but it's still better than previously).. I guess it may still not work very well with some strange combinations of colspan & rowspan.

ldomNode::elementFromPoint(): also check for x coordinate

---

crengine/include/hyphman.h
crengine/include/lvdocviewprops.h
crengine/src/hyphman.cpp
crengine/src/lvdocview.cpp
crengine/src/lvtinydom.cpp

When hyphenating a word, the existing algorithms enforce a minimal length of 2 for each word fragments on left or right side.
This allows for increasing these minimal sizes, as requested in https://github.com/koreader/koreader/issues/3848.
These new numbers need to be included in the globalHash computation so the document can be re-rendered when they are updated.
See discussion about where to do that in hyphman.cpp and tests at https://github.com/koreader/koreader/issues/3848#issuecomment-381647179 and followups.
I'll PR the frontend code to use that in the evening.

hyphenation: allow for setting min left/right fragment length

---

crengine/include/hyphman.h
crengine/src/hyphman.cpp
crengine/src/lvdocview.cpp

Followup to #151, as it seems it works fine with a minimal value of 1.
See https://github.com/koreader/koreader/issues/3848#issuecomment-382291410 for why it can matter with French.
No adaptation seemed needed in AlgoHyph, but I couldn't make it show me a hyphenation happening at 1.
Also move the #define for these values into the header file, so we can use them in lvdocview.cpp

hyphenation: change hyphen_min minimal value from 2 to 1

---

crengine/src/lvrend.cpp

`<HR>` only for now.
I let in code for generic support on all or some elements, and/or to support them only if value is in '%' or 'em' units which make the width relative to current block width. But it's safer to not support them on other elements, for wider and better readability.
Mentionned in https://github.com/koreader/koreader/issues/2842.
The only place `width:` is currently supported by crengine is for images.
For crengine, `<hr>` is just a dummy block element (which happens to be empty the way it is used by authors), to which our epub.css or html.css add some borders.
So, to support `width`, we just have to support them for all block elements.
Which I did, it was easy. And we now support `width:`!
Except that it's most often preferable to NOT support `width:` :)
95% of the EPUBs …

Support 'width:' css style on some block elements

---

crengine/src/lvdrawbuf.cpp

DrawLine wasn't converting color value as FillRect correctly does.
Before:
<kbd>![image](https://user-images.githubusercontent.com/24273478/39189033-872fe25e-47d1-11e8-9e20-b99bc515b091.png)</kbd>
After:
<kbd>![image](https://user-images.githubusercontent.com/24273478/39188987-6a333534-47d1-11e8-8415-fcae2c24dc4a.png)</kbd>
HTML:
```html
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title></title>
<style>
.testcolor {
color: blue;
border-top-color: green;
border-left-color: blue;
border-bottom-color: red;
border-right-color: yellow;
border-width: 10px;
}
.sep { margin: 10px;}
</style>
</head>
<body>
<pre>
color: blue;
border-top-color: green; …
```

Fix borders color rendering

---

crengine/src/lvdrawbuf.cpp
crengine/src/lvrend.cpp
crengine/src/lvstsheet.cpp

- Case should not matter when parsing CSS declaration properties ("`Font-Weight`"), named values ("`Bold`"), named length ("`LARGER`"), and length units ("`10PX`").
- Case should matter when matching class names ("`<div class="bottomBorder"` should not use CSS defined as "div.bottomborder").
- Fix color rendering of background image (the conversion of internal images from 32bpp to the final 16bpp was simply not implemented).
- Fix existing unwanted lowercasing of background image file reference (`url("BackgrounImage.jpeg")` was lowercased in the process of parsing it.
See discussion in #140. Closes #140.
There is still an existing issue with resolution of relative image path there that could fail (couldn't find a quick fix for this), and some other existing strange issue when no-repeat is …

Fix some CSS case sensitivity issues

---

crengine/include/lvstyles.h
crengine/src/lvstsheet.cpp

It was correct for enum values, but not for length values.
Also fix default value for `letter_spacing` to be `inherit`.
See https://github.com/koreader/koreader/issues/1430#issuecomment-385656723.
Should allow fixing some annoying books with:
```css
body { margin: 0 0 0 0 !important; }
* { line-height: inherit !important ;}
```

Stylesheets: fix parsing of 'inherit' property value

---

crengine/include/lvstsheet.h
crengine/src/lvstsheet.cpp

There was already some code to process selectors by ascending order of specificity, but LVCssSelector._specificity was always 0.
We now add to it some weight depending of the kind of each LVCssSelectorRule it may include.
See https://github.com/koreader/crengine/issues/167#issuecomment-385236850
I haven't tested that much nor looked much at the selector order navigation, I just added these simple rules and the 2 test cases in https://github.com/koreader/koreader/issues/2841 seem ok:
Before => after
<kbd>![image](https://user-images.githubusercontent.com/24273478/39490586-9ea695c8-4d89-11e8-9057-714e1a018d5f.png)</kbd> => <kbd>![image](https://user-images.githubusercontent.com/24273478/39490385-fbb2848a-4d88-11e8-9fb4-78c757d120c8.png)</kbd> …

Stylesheets: implement CSS selectors specificity

---

crengine/src/lvstsheet.cpp

Forgot to add +1 if selector itself has an element.
Followup to https://github.com/koreader/crengine/pull/170#issuecomment-385809336

Fix CSS selector specificity computation

---

crengine/src/lvfntman.cpp

The way a limit works is by setting the value to the limit if you
surpass it, not by setting `0` if you go beyond the limit.
Also upped the value to something more sensible as well as
made it more sensibly tweakable in the future.
As a testcase, just stick some large value in letter-spacing.
```html
<!DOCTYPE html>
<html>
<body>
<div style="letter-spacing:500px">
asdfasfasdf asdfasfasdf asdfasfasdf asdfasfasdf asdfasfasdf asdfasfasdf asdfasfasdf asdfasfasdf asdfasfasdf asdfasfasdf asdfasfasdf asdfasfasdf asdfasfasdf asdfasfasdf
</div>
</body>
</html>
```
See https://github.com/koreader/koreader/issues/1430#issuecomment-385753941 for discussion.

[fix] crengine/src/lvfntman.cpp: improve letter_spacing limit

---

crengine/src/lvxml.cpp

Fixes https://github.com/koreader/crengine/issues/165#issuecomment-386542218
The HTML was parsed like this instead of properly auto-closing empty elements like `LINK` and `META`.
```xml
<?xml version="1.0"?>
<html>
<head>
<title>CSS Test: Simple ID selectors specificity over attribute selectors</title>
<link rel="author" title="Microsoft" href="http://www.microsoft.com/">
<link rel="help" href="http://www.w3.org/TR/CSS21/selector.html#id-selectors">
<meta name="flags" content="">
<meta name="assert" content="ID selectors trump attribute selectors in specificity.">
<style type="text/css"> div#div1 { color: green; } div[id=div1] { color: red; } </style>
</meta>
</meta>
</link>
</link>
</head>
<body>
<p>Test passes if the "Filler Text" below is green.</p>
<div id="div1">Filler Text</div> …
```

[fix] crengine/src/lvxml.cpp: add all empty HTML elements

---

crengine/src/hyphman.cpp
crengine/src/lvtinydom.cpp

~~- `<STYLE>` after non-self-closing `<META>` or `<LINK>` wasn't parsed.~~ done correctly by next PR by @Frenzie (thanks!)
On loading a head style, a re-rendering was not explicitely requested (but may have been done because of other re-rendering reasons like setting a hyphenation dict).
Closes #165
Also: Hyphenation: increase MAX_PATTERN_SIZE from 16 to 35 . See https://github.com/koreader/crengine/pull/150#issuecomment-386612527

html head styles: fix styles not being applied

---

cr3gui/data/chm.css
cr3gui/data/dict.css
cr3gui/data/doc.css
cr3gui/data/epub.css
cr3gui/data/fb2.css
cr3gui/data/htm.css
cr3gui/data/rtf.css
cr3gui/data/txt.css
crengine/include/fb2def.h
crengine/include/lvdocviewprops.h
crengine/include/lvtinydom.h
crengine/src/lvdocview.cpp
crengine/src/lvimg.cpp
crengine/src/lvtinydom.cpp

`<BR>` were always being converted to `<P>` because of "Patch for bad LIB.RU books" that was being applied everytime.
So, it was losing the style of the container for text after a `<br>`
With this HTML:
```html
<html>
<head>
<style>
p { color: red; text-indent: 1.2em;}
</style>
</head>
<body>
This is some text.<br/>
This is some text.<br/>
This is some text.<br/>
This is some text.<br/>This is some text.<br/>This is some text.<br/>This is some text.<br/>
This is some text.
<hr/>
<p class=thisisaP style="color: blue">
This is some text.<br/>
This is some text.<br/>
This is some text.
</p>
<hr/>
<div class=thisisaDIV style="color: green">
This is some text.<br/>
This is some text.<br/>
This is some text.
</div>
<hr/>
<div class=thisisaDIV style="color: green">
This is some text.<br/>
This …
```

Proper handling of <BR> tags in .html documents

---

crengine/include/lvstsheet.h
crengine/src/lvstsheet.cpp

Fix _some_ of the issues reported in #176.
- fix standalone #ID (was working only as ELEM#ID)
- fix non-lowercase element name (elements are internally lowercased, so we should lowercase there too to expect any match)
- fix E+F selector, that should ignore immediate preceding text nodes, and consider the first met element node
- adds E~F selector (like E+F, but *any* instead of "immediate" precedessor is considered for a match)

Fix a few CSS selector issues

---

crengine/include/lvstsheet.h
crengine/src/lvstsheet.cpp
crengine/src/lvtinydom.cpp

Supports:
```
:first-child
:first-of-type
:last-child
:last-of-type
:only-child
:only-of-type
```
and, with only `odd` or `even` as parameter:
```
:nth-child(even)
:nth-of-type(odd)
:nth-last-child()
:nth-last-of-type()
```
Details about pseudo-classes at https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes
Also:
- fix parent selector to match when element-less (eg: ".pcls > DIV")
- ancessor selector would not match anything when element-less (eg: ".pcls DIV"): when element-less, it becomes non deterministic, and would need to takes multiple paths thru each parent to check for a match). It is now tweaked to at least match parent (so it behaves as ".pcls > DIV")
- fix html document HEAD STYLE parsing which could gather extraneous characters
Fix failure with css3-modsel-170d.epub …

CSS: add support for some pseudo-classes

---

cr3gui/data/chm.css
cr3gui/data/dict.css
cr3gui/data/doc.css
cr3gui/data/epub.css
cr3gui/data/fb2.css
cr3gui/data/htm.css
cr3gui/data/rtf.css
cr3gui/data/txt.css
crengine/include/fb2def.h
crengine/src/lvstsheet.cpp

Make BR a inline element again (being a block element fixed the leading space, but make xpointers invalid and highlights shifted).
Remove BR + BR CSS, which was just wrong, but didn't show up till we fixed E + F selector.
Reverts part of #172.
Discussed in and after https://github.com/koreader/koreader/pull/3934#issuecomment-386996718

Revert parts of recent BR handling fixes

---

crengine/include/lvfntman.h
crengine/src/lvfntman.cpp
crengine/src/lvtinydom.cpp

The fact that LVFont:setFallbackFont() wasn't 'virtual' made clearFallbackFonts() always use this no-op one. Now, it will use the extended LVFreeTypeFace:setFallbackFont() one, which will allow us to update the fallback font in real time, without the need for a restart.

Fix updating fallback font

---

crengine/include/cssdef.h
crengine/src/lvrend.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvtinydom.cpp

Adds support for a new non-standard css `display:` value: `-cr-list-item-block` which renders list items as block instead of final.
Based on original work from @bbgordon, see https://github.com/koreader/koreader/issues/2107#issuecomment-375799779.
I started from @bbgordon code (there's still some of his code as-is), but ended up doing things a bit differently:
- we keep the original list-item rendering code (rendering method `erm_list_item`), so it's still the default
- this PR should have no impact, unless we add to styles (standard css or via a style tweak):
`li {display: -cr-list-item-block; }`
(the new added code is always wrapped in stuff like  `if ( enode->getStyle()->display == css_d_list_item_block )`)
- no new rendering method (no `erm_list_item_block`): list items are managed by …

Toggable alternative rendering method for list items

---

crengine/include/lvtinydom.h
crengine/src/lvtinydom.cpp

On each stylesheet change, a nodeStyleDisplayHash will be computed from all the nodes "display:" values. It should allow us to detect that the DOM may not be coherent with the styles, because:
- the DOM may get some added autoBoxing nodes as children of "display: block" nodes
- these autoBoxing nodes are never removed, so they stay there when a node style change from "display: block" to "display: inline", which won't make the rendering fully inline
- when cache is re-used, the DOM can't change, and no autoBoxing will be added when a node style change from "display: inline" to "display: block"
This may cause some rendering issues, and the only solution is to reload the document (with the need to prevent cache re-use for documents with an existing cache).
These checks will be done from the …

Compute nodeStyleDisplayHash and adds isBuiltDomStale()

---

crengine/include/lvtinydom.h
crengine/src/lvtinydom.cpp

So we can manage the cache file from lua side (delete, add/remove a ".keep" extension, etc...)
Will be followed with adding this into cre.cpp:
```c
static int getCacheFilePath(lua_State *L) {
CreDocument *doc = (CreDocument*) luaL_checkudata(L, 1, "credocument");
lString16 cache_path = doc->dom_doc->getCacheFilePath();
if (cache_path.empty())
return 0;
lua_pushstring(L, UnicodeToLocal(cache_path).c_str());
return 1;
}
```

Adds tinyNodeCollection::getCacheFilePath()

---

cr3gui/data/fb2.css
crengine/include/fb2def.h
crengine/src/lvrend.cpp
crengine/src/lvtinydom.cpp

Hide `<style>` content when `<style>` appears in the `<body>`, see https://github.com/koreader/crengine/pull/191#issuecomment-391742834.
Again, it was `display: inline`, and could then be part of the process of autoBoxing and DOM change.
So, previous behaviour is ensured when `gDOMVersionRequested < 20180524` (I re-used the yesterday version as no nightly was made since).

Make the <style> element hidden by default

---

crengine/src/lvrend.cpp
crengine/src/lvtinydom.cpp

- resetRendMethodToInline() is used to make inline all nodes that are children of an inline element (which in itself looks like wrong, but that's how crengine works, and fixing that would be another thing). But it shouldn't reset to inline child nodes that are 'display:none' as that would make them visible.
- list item marker with list-style-position:ouside : don't account for the marker height on the first child only, as if this first child is display:none, that would make an empty line with the marker. Instead, account for it on the whole children block.
The little arrow at the start of item on the 1st image are in a `class='noprint'`. If we'd like to use `.noprint {display: none}`, we would get what's on the 2nd image. With this fix, we get what's on the 3rd: …

Fix a few edge-case rendering issues

---

crengine/include/lvstyles.h
crengine/src/lvrend.cpp
crengine/src/lvtinydom.cpp

A border was drawn because it should when no width is specified.
We should distinguish between styles (css_val_unspecified, 0) and (css_val_px, 0) (or some other css unit, including no-unit), which means an explicite border-width: 0 has been set via styles and no border should be drawn.
Details in https://github.com/koreader/crengine/pull/16#issuecomment-393894913
Context for the various use of `bw.type > css_val_unspecified`:
https://github.com/koreader/crengine/blob/a2f4e37be34f488ca22a978cd3e7c27e8ee05e2e/crengine/include/cssdef.h#L161-L175

Fix border being drawn in spite of 'border-width: 0'

---

crengine/include/lvstyles.h

Attempt at fixing:
```
/home/travis/build/koreader/koreader-base/thirdparty/kpvcrlib/crengine/crengine/include/lvstyles.h:167:5: error: expected member name or ';' after declaration specifiers
, background_repeat(css_background_r_none)
^
/home/travis/build/koreader/koreader-base/thirdparty/kpvcrlib/crengine/crengine/include/lvstyles.h:161:19: error: expected '('
, border_width{
^
/home/travis/build/koreader/koreader-base/thirdparty/kpvcrlib/crengine/crengine/include/lvstyles.h:165:45: error: expected ';' after expression
css_length_t(css_val_unspecified, 0)
^
;
```
even if I'm not sure that's the right or most efficient way of initializing that array of `css_length_t border_width[4]`

Try to please clang: avoid compiler errors

---

cr3gui/data/epub.css

This looks unneeded, and may cause unwanted page break (eg: when big image in a DIV, scaled down to fit 100% of screen height, this added 1px may add a blank page before or after the image).
See https://github.com/koreader/koreader/pull/3992#issuecomment-394071949

epub.css: remove div { margin: 1px; }

---

crengine/src/hyphman.cpp
crengine/src/lvtextfm.cpp

(follow up to https://github.com/koreader/koreader/pull/3993#issuecomment-394197067)
Very rare, but happened systematically on a specific page of a specific book.
There's probably a bug elsewhere that makes some code go look further than `m_length` and cause a segfault. `memset()`'ing all buffers on their full allocated size to 0 seems to avoid these occasional segfaults. But just setting zero to the slot just after `[0..m_length-1]` seems enough (and is less expensive than full memset).
I did first disable the use of static buffers, and it didn't crash anymore.
I then went on with memseting to zero the whole m_size/STATIC_BUFS_SIZE, and it didnt crash.
I then went on with memseting to zero only `[0..m_length-1]`, and it crashed.
I then went on with memseting to zero only `[0..m_length]`, …

Fix rare segfault with text formatting code

---

crengine/src/lvtextfm.cpp

Mostly some saner bound checking, and the use of `flags&LCHAR_IS_SPACE` instead of `char==' '`.
That's mostly what has changed upstream for lvtextfm.cpp (except some revert of the CJK stuff that we added and that was initially merged upstream, that we should obviously keep).
I have no test case that would show these changes fix anything, but they look safe and sane, so rather merge them in case they fix stuff. (and I don't have to wonder if this commit upstream would solve that problem I see).
Sources (for reference, we diverged `Fri Feb 21 14:10:20 2014`):
https://github.com/buggins/coolreader/commits/master/crengine/src/lvtextfm.cpp commit history
https://github.com/buggins/coolreader/commit/e2a1cf3306b6b083467d77d99dad751dc3aa07d9 some changed that I just added as a comment, as it …

lvtextfm.cpp: simple changes from upstream

---

crengine/include/lvfnt.h
crengine/src/lvrend.cpp
crengine/src/lvtextfm.cpp

This should fix the issue
- described by @frankyifei in https://github.com/koreader/koreader/issues/2021#issuecomment-219996796
- met alongside https://github.com/koreader/crengine/pull/172
- explained in https://github.com/koreader/koreader/pull/3934#issuecomment-387114056
- reported in https://github.com/koreader/koreader/issues/1283 and https://github.com/koreader/koreader/issues/2067.
With:
```html
<p>
Some text<br/>
More text
</p>
```
Before > after
<kbd>![image](https://user-images.githubusercontent.com/24273478/41142486-22665e82-6af6-11e8-95e2-216000ea54d8.png)</kbd> > <kbd>![image](https://user-images.githubusercontent.com/24273478/41142506-335f8074-6af6-11e8-9c9a-df5baa9de94e.png)</kbd>
The newlines being considered like a space, and the XML parser replacing multiple spaces with …

text formatting: fix leading spaces issues

---

crengine/src/lvdocview.cpp
crengine/src/lvpagesplitter.cpp
crengine/src/lvrend.cpp

Properly add the RN_SPLIT_AFTER_AVOID and RN_SPLIT_BEFORE_AVOID to the AddLine() calls for the padding lines when these contain a border, so no page break can happen in between them.
Also fix page splitting algorithm to properly ensure these AVOID flags.
Upstream had some commits and reverts that may be were a try at fixing that: https://github.com/koreader/crengine/commit/8471d00c2afcc2953e3408b6988a830a0f654798  https://github.com/koreader/crengine/commit/1e08c37c3cb7a732ad12b41d3ee6d357c551651b  https://github.com/koreader/crengine/commit/64fadbbbe9aa82803c2ba1b386e9d3c5bfac1e74
Pining @frankyifei for having a quick look at the lvrend.cpp changes (as you added these padding/border management).
Before:
<kbd>![border_before1](https://user-images.githubusercontent.com/24273478/41290404-142 …

Avoid page break between a node and its borders

---

crengine/include/lvtinydom.h
crengine/src/lvdocview.cpp
crengine/src/lvtinydom.cpp

Allow building an alternative TOC from document headings.
This only adds methods so that can be checked and triggered from lua side.
(Getting back the original TOC will need the cache to be invalidated and the book reloaded)
For now, I'll have that be toggable with long-press on the `Table of content` menu item.
It should allow us to got from empty or minimal TOC (I sometimes got some with only 1 or 2 items) like:
<kbd>![toc_no_toc](https://user-images.githubusercontent.com/24273478/41274774-eafb00ac-6e1e-11e8-8e2e-07b3c5451ae1.png)</kbd>
<kbd>![footer_no_toc](https://user-images.githubusercontent.com/24273478/41274810-105c1444-6e1f-11e8-9bbe-2bcf3545f4d8.png)</kbd>
to:
<kbd>![toc_alt_toc](https://user-images.githubusercontent.com/24273478/41274783-f1f5f286-6e1e-11e8-8c62-6bf19e55346f.png) …

Allow building an alternative TOC from document headings

---

crengine/src/lvrend.cpp

These were drawn 1px too far, which could make the bottom border not shown in page mode (where some clipping is done).
This is a quick and simple search and replacce in DrawBorder() of   `fmt.getHeight()`  by  `fmt.getHeight()-1`
and  `fmt.getWidth()`   by  `fmt.getWidth()-1` as detailed in https://github.com/koreader/crengine/issues/160#issuecomment-396375101
(Shouldn't need a FORMATTING_VERSION_ID bump as it's really just drawing code).
Closes #160
Before:
<kbd>![image](https://user-images.githubusercontent.com/24273478/41363202-a2ef9b86-6f33-11e8-887c-d9ba985b59d8.png)</kbd>
After:
<kbd>![image](https://user-images.githubusercontent.com/24273478/41363292-d510fa60-6f33-11e8-978d-dd1b39fc443e.png)</kbd>

Fix drawing position of bottom and right borders

---

.ci/script.sh
.gitignore
cr3gui/data/hyph/languages.json
crengine/include/hyphman.h
crengine/include/lvdocviewprops.h
crengine/include/lvstring.h
crengine/include/lvtinydom.h
crengine/src/hyphman.cpp
crengine/src/lvdocview.cpp
crengine/src/lvfntman.cpp
crengine/src/lvstring.cpp
crengine/src/lvtinydom.cpp

Implement method **C** described in https://github.com/koreader/koreader/issues/3431#issuecomment-397534353 :
Don't consider soft-hyphens as word separator anymore: now, they are just like a zero-width alpha character, and are never drawned (this should fix any spacing/rendering glitch by getting rid of some dubious edge cases handling).
Only the hyphenation methods will use them to decide where that word is breakable, and only that added hyphen will be drawn.
Remove soft-hyphens only at library boundaries:
- when returning selected text when holding on word or text, for the methods used by cre.cpp:
- when creating ldomWordEx, for ldomWordEx.getText(), for cre.cpp getWordFromPosition()
- ldomXRange::getRangeText(), for cre.cpp getTextFromPositions()
- when searching user provided text …

Fix handling of soft-hyphens

---

crengine/include/cssdef.h
crengine/include/lvdocview.h
crengine/include/lvdocviewprops.h
crengine/include/lvrend.h
crengine/src/lvdocview.cpp
crengine/src/lvrend.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp

Follow up to #161.
Add or fix support of 'px', 'in', 'cm', 'mm', 'pt' and 'pc' css units.
They are all scaled according to the global crengine setting `PROP_RENDER_DPI`/`gRenderDPI `with a default value of `96`. This setting will be toggable from a set of values from a KOReader bottom config panel, and is independant from the KOReader/device internal screen_dpi setting. This will acts like a Zoom option (but not affecting the selected default font size, except for elements with a font size set with a css absolute unit).
(I don't think we should use the device DPI, using 300 DPI on my GloHD makes everything too large for my liking, and cause some surprise with many text epubs that uses stuff like `MsoNormal {text-indent: 0.5pt}`)
<kbd>![image](https://user-images.githubusercontent.com/24273 …

Adds support for dpi-based css units (px/in/cm/mm/pt/pc)

---

cr3gui/data/epub.css
crengine/include/lvdocview.h
crengine/src/lvdocview.cpp
crengine/src/lvfntman.cpp
crengine/src/lvstyles.cpp

Don't re-parse stylesheets on each rendering (page turn, menu opening, widget opening or closing...) when not needed. Should save a few 10ms on each document painting on a device.
(Shouldn't really be noticable, but that will avoid me suspecting crengine when looking at slowness in refreshes.)
Fix the last remaining `CRE WARNING: cached rendering is invalid (style/stylesheet hash mismatch): doing full rendering` that could happen on loading a document from cache if we had change font size on previous session, mostly when a document has `body {font-family: serif}`.
(That's the one I couldn't fixed mentionned at end of https://github.com/koreader/crengine/pull/100#issue-171740521).
~~epub.css: don't inherit text-align for TABLE, OL, UL, mostly for when they are contained in a `<CENTER>`. …

Avoid stylesheet reparsing, fix some cache mismatch

---

crengine/include/cssdef.h
crengine/include/lvstring.h
crengine/include/lvstyles.h
crengine/src/lvrend.cpp
crengine/src/lvstring.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvstyles.cpp
crengine/src/lvtinydom.cpp

(as wished in https://github.com/koreader/koreader/issues/3432#issuecomment-406062300 )
Only `uppercase`, `lowercase` and `capitalize`.
https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform
http://www.fileformat.info/info/unicode/block/halfwidth_and_fullwidth_forms/list.htm
Some code for `full-width` is there but not used, and would need additional changes to lvfnt/lvfntman/hyphman/lvtextfm, This may change CJK rendering, so it will need some CJK user or developer to confirm and followup.
Details: supporting full-width (original or text-transform'ed) ascii text would need to handle these as ASCII chars, and the IDEOGRAPHIC_SPACE (0x3000) as a space in word splitting and hyphenation: that would make it candidate to width change for justification, and it would lose it's fixed …

CSS: adds support for the 'text-transform:' property

---

cr3gui/data/epub.css
crengine/src/lvrend.cpp
crengine/src/lvtinydom.cpp

Previously discussed in https://github.com/koreader/crengine/pull/196#issuecomment-393861885 and #218.
- For list items with with "list-style-position: outside" (default and most common) and "text-align: center" or "right", draw them just like "list-style-position: inside" is rendered, as this will draw the marker at the near left of the text (previously, the marker was drawn on the far left of the whole available width, which was ugly).
- Firefox resets text-align: to 'left' for table (eg: `<center><table>` doesnn't have its cells' content centered, not even justified if body has "text-align: justify"), while crengine would make them centered. We'd rather do the same as Firefox.
edit: but a bit different than Firefox: we use the BODY text-align value. Why? I had initially written this:
> …

Fix table & lists when in centered/right aligned container

---

crengine/src/lvdocview.cpp
crengine/src/lvstring.cpp
crengine/src/lvtinydom.cpp

Only use char properties to detect word boundaries for hyphenation.
In all other places, mostly in lvtinydom.cpp, we use the isWordSeparator functions to detect word boundaries. One place was still not using it, and this caused some highlights inconsistencies (the `some text` in the screenshots below).
(Fix some char properties errors, even if they are now no more used).
Fix ldomXPointer::getRect(extended=true) to return the width of the char pointed to, instead of the width of the word containing that char. The notion of what a word is can in some cases be different, and that was causing displaced highlights on some hyphenated words (eg: with french words "l'empe-reur", the part before hyphenation being considered either as one word for rendering, or as 2 words when walking words to get …

Fix two highlight issues

---

crengine/include/lvfnt.h
crengine/src/lvrend.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp

Attempt to conform better to https://www.w3.org/TR/css-text-3/ mainly in the way we handle collapsing spaces. When in doubt, try to display as Firefox does.
Details as comments in the code. Added more comments about how I understood lvtextfm works.
(Some specifics to CJK are mentionned, and some sample code commented out - will have to be continued by a CJK dev if that feels necessary.)
This reverts the recent "fix leading spaces issues" commit #204, while still fixing these leading spaces issues in a more generic way, leading spaces being considered collapsed spaces.
Also fix missing new line when standalone `<br/>` stuck together (`<br/><br/>`) (and stuck `\n\n` in pre-paragraphs). Don't display the last such newline at the end of rendered block, as most browser's don't.
I must say that …

text formatting: fix collapsing spaces and newlines

---

crengine/src/lvtinydom.cpp

The few attributes of which we compare the value to predefined strings were not lowercased. So, the following would be ignored:
```html
<link href="some.css" rel="styleSHEET" type="TEXT/css"/>
<div align=CENTER>align center</div>
<DIV Align=Right>align right</div>
```
(The tagname and attrname comparisons are ok, as they are internally lowercased. Only the attrvalue isn't, and shouldn't be, except when comparing to expected fixed values that can be in mixed case.)
Fix the issue with styles not applied on a specific book reported at https://www.mobileread.com/forums/showthread.php?t=309717.
The books html contains:
```html
<head>
<link href="springer_epub.css" type="text/css" rel="styleSheet"/>
</head>
```

HTML: fix parsing of non-lowercase stylesheet link tags

---

crengine/include/lvdocview.h
crengine/include/lvtinydom.h
crengine/src/lvdocview.cpp
crengine/src/lvtinydom.cpp

3 commits for various fixes related to styles handling on load
When opening a document, there was always a default document loaded ("Welcome to CoolReader").
This allows for bypassing this (noDefaultDocument=true will be passed by cre.cpp).
```c
--- a/cre.cpp
+++ b/cre.cpp
@@ -334,7 +334,7 @@ static int newDocView(lua_State *L) {
luaL_getmetatable(L, "credocument");
lua_setmetatable(L, -2);
-       doc->text_view = new LVDocView();
+       doc->text_view = new LVDocView(-1, true); // bitsPerPixel=-1, noDefaultDocument=true
//doc->text_view->setBackgroundColor(0xFFFFFF);
//doc->text_view->setTextColor(0x000000);
//doc->text_view->doCommand(DCMD_SET_DOC_FONTS, 1);
```
The performance improvement is negligeable, but these ghost documents interfered with debugging crengine, so things will get …

Various fixes related to styles handling on load

---

cr3gui/data/epub.css
crengine/src/lvstsheet.cpp

crengine supports many older and obscure hyphenation CSS properties.
It will now also support the CSS current proper one `hyphens:`
https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens
See discussion at https://github.com/koreader/crengine/pull/209#issuecomment-401378885
Added some comments about the older properties with info I grabbed from https://github.com/readium/readium-css/blob/master/docs/CSS21-epub_compat.md.
(I'll clean it up also in the style tweaks in frontend code)

CSS: proper support for "hyphens:" property

---

crengine/include/lvfntman.h
crengine/src/lvfntman.cpp
crengine/src/lvtinydom.cpp

Avoids mismatches & broke-ass advances

Use the same FT load flags in HB as in FT

---

crengine/src/lvrend.cpp

See https://github.com/koreader/koreader/issues/4207#issuecomment-419668415
See https://github.com/koreader/koreader/issues/4197
Changed a few rules:
Previously, on tables where columns have no width= specified:
- width was distributed between columns according to each longest   cells plain text size (so, if a column contains only cells with 10 chars, and another column contains one cell with 990 chars, the former would get a width of 1/100th of the table width, which could cause various display gliches when trying to render the 10 chars on a very small width)
- a minimal width of 8px was ensured
- it was further reduced to the length of its longest plain text if it happens to be smaller
- the width recovered from this last reduction was evenly distributed to all columns (so, the …

Tweak table columns widths algorithm. Fix some ignored page-breaks

---

crengine/src/lvrend.cpp

Previous fix (in #233) was wrong, and was adding too many wrong page breaks (noticed by unit tests in https://github.com/koreader/koreader/pull/4217).
This reverts some bits from it, and fix that hopefully the right way.
Note that this fix (to solve https://github.com/koreader/koreader/issues/4207) may still add some new page breaks (and blank pages) that might be bothering (to me at least :) or feel uneeded. But in my tests, they look like they obey HTML and CSS.
For example if one HTML file in an epub (so, making a DocFragment, which generates a page-break by itself) contains:
```html
<body>
<div></div>
<h3>some title</h3>
```
Previously, the empty div that would have carried the page-break (from DocFragment) was ignored, and the DocFragment page-break was lost, but the one implied by …

Better fix: don't ignore page breaks on empty nodes

---

crengine/include/lvdocview.h
crengine/include/lvtinydom.h
crengine/src/lvdocview.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvtinydom.cpp

Will be needed by upcoming PRs in frontend code and base/cre.cpp.
I'll bump it all at once, as it felt quite hard to split all that into individual single-topic cre>base>frontend bumps.
There will probably be some warnings with my C++ code from the clang checks done in base...
Details in the individual commit messages.
Some screenshots about what's fixed and what to expect:
Some single highlight of some CJK/mixed text before:
<kbd>![image](https://user-images.githubusercontent.com/24273478/46607655-02ac0080-cb02-11e8-89e5-1613182db65d.png)</kbd>
The 2nd commit will fix the non-highlighted char on the right, the `ldomXRange::getSegmentRects()` addition will allow a more proper highlighting of non-word chars on the page edges:
<kbd>![image](https://user-images.githubusercontent.com/24273478/ …

Various: fix CJK highlight, page links; adds getHtml(), getSegmentsRects()

---

crengine/src/lvdocview.cpp

People that uses the full status bar may get on document load:
`CRE: document loaded, but styles re-init needed (possible epub with embedded fonts)`
`getPageHeaderHeight()` was called before `m_infoFont` was set to its definitive value. So, the second time it is called, we may get a different value, which causes a difference in page height, so a hash mismatch, and so a re-rendering.
Just move the `dy` computation AFTER `m_infoFont` is set to its correct and definitive value, and avoid any mismatch.
(Minor, does not need an immediate bump - just PRing that so I don't forget it.)

Avoid uneeded re-rendering on load when with full status bar

---

crengine/include/lvrend.h
crengine/include/lvstyles.h
crengine/include/lvtextfm.h
crengine/src/lvrend.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvstyles.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp

Details in the individual commit messages.
2nd commit fix line-height inheritance when no unit (eg: `line-height: 1.2`) which will suprise people like me who like things condensed, but those people will then just have to use more often the `Ignore publisher line heights` style tweak.
4th commit fixes https://github.com/koreader/koreader/issues/3629#issuecomment-430383477 and other occasional spaces at start of line.
The 6th commit is the main one, and implements full and correct support for `vertical-align:` for text and images (but not for table cells). Previously discussed at https://github.com/koreader/crengine/pull/142#issuecomment-427599008.
This will need a lightening of footnotes detection (any vertical align drift will be a footnote, even if small) in base/cre.cpp.
Useful links: …

Fix and extend support of vertical-align, and other rendering fixes

---

crengine/src/lvstsheet.cpp
crengine/src/lvtextfm.cpp

First commit fix CSS class name match when multi class names (originally from #72).
With 
```html
<style>
.zabc { color: orange }
.abcz { color: red }
.abc { text-decoration: underline }
</style>
<h1>multi classes matching</h1>
<div>
<span class="abc">underline</span>
<span class="zabc">none</span>
<span class="abcz">none</span>
<span class="abc vvv">underline</span>
<span class="zabc vvv ">none</span>
<span class="abcz vvv">none</span>
<span class="uuu abc">underline</span>
<span class="uuu zabc ">none</span>
<span class="uuu abcz">none</span>
<span class="uuu abc vvv">underline</span>
<span class="uuu zabc vvv ">none</span>
<span class="uuu abcz vvv">none</span>
<br/>
</div>
```
Before (some orange `none` shouldn't be underline): …

 Fix CSS class check, and segfault on ignored starting space

---

CMakeLists.txt
crengine/include/lvtinydom.h
crengine/src/crgui.cpp
crengine/src/lvdocview.cpp
crengine/src/lvdrawbuf.cpp
crengine/src/lvfntman.cpp
crengine/src/lvstream.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp
thirdparty/antiword/fail.c
thirdparty/antiword/fail.h

Includes most of the first commit mentionned in #242.
~~Also fixed some other compiler warning introduced by my recent changes.~~ moved into #245
Still to be tested by me on my device, just pushing this to see its effect on CI output. edit: looks OK.
No real idea if we should keep or not the addition to gcc flags: `-std=c++11 -fPIC -Wno-misleading-indentation`. Pinging @NiLuJe for opinion.
(I don't think we have any misleading indentation warning - may be that was for some other part of coolreader code like cr3qt - so, we could probably remove it)

Fix some compile warnings (from upstream)

---

crengine/include/fb2def.h
crengine/include/lvtinydom.h
crengine/src/lvrend.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp

Images are enforced a max height, which was the page height.
To prevent any uneeded page break before or after a big image (originally or scaled by CSS), we should additionally take into account the image container margins/borders/padding, and the space below added by the recently enforced strut (Some details in https://github.com/koreader/koreader/pull/4378#issuecomment-444771941)
Could happen with a cover page set like:
`<div><p style="margin-top: 20px"><img src="" style="height: 100%"/></p></div>`
(Before https://github.com/koreader/crengine/commit/08adb23425350ff02ace9cec3280d68e9f0d75bb, a first page bigger than page-height was simply truncated, and the bottom part just lost. https://github.com/koreader/crengine/commit/08adb23425350ff02ace9cec3280d68e9f0d75bb fixed that, but then, …

Fix max image height, hide <epub:case> in <epub:switch>

---

crengine/include/lvpagesplitter.h
crengine/src/lvrend.cpp
crengine/src/lvtinydom.cpp

By using the mean of the cells's max_content_width instead of the max, so that a single large cell among many smaller cells doesn't request all the width for this column (which would give less to others, which could make them use more height). This should help getting more reasonable heights across all rows.
May help avoiding some less optimal column width choices as noticed with CJK in https://github.com/koreader/crengine/pull/243#issuecomment-443756622 and with symbol fonts in https://github.com/koreader/crengine/pull/243#issuecomment-445265737
There are some cases when this change make things worse, but I think there are more cases where it make things better, and it makes these far better than it makes the others worse with my test samples.
Before: …

Tables rendering: tweak column widths algorithm

---

crengine/include/cssdef.h
crengine/include/lvrend.h
crengine/include/lvstyles.h
crengine/include/lvtinydom.h
crengine/src/lvdocview.cpp
crengine/src/lvpagesplitter.cpp
crengine/src/lvrend.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvstyles.cpp
crengine/src/lvtinydom.cpp

Adds support for a private CSS property `-cr-hint:`
This will allow tuning a few crengine features with style tweaks (more details in a coming buddy frontend PR).
Currently supported named values:
For footnote popup detection (handled in base/cre.cpp):
`noteref`          link is to a footnote
`noteref-ignore`   link is not to a footnote (even if everything else indicates it is)
`footnote`         block is a footnote (must be a full footnote block container)
`footnote-ignore`  block is not a footnote (even if everything else indicates it is)
In-page display of footnotes (see below for screenshots):
`footnote-inpage`  block is a footnote (must be a full footnote block container), and to be displayed at the bottom of all pages that contain a link to it.
Alternative TOC hinting:
`toc-level1` …

Adds support for a private CSS property "-cr-hint:"

---

crengine/include/lvpagesplitter.h
crengine/include/lvrend.h
crengine/include/lvstsheet.h
crengine/include/lvstyles.h
crengine/src/lvdocview.cpp
crengine/src/lvpagesplitter.cpp
crengine/src/lvrend.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvstyles.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp

`CSS: avoid publisher's !important from overriding ours` : see https://github.com/koreader/koreader/issues/4196#issuecomment-451016032 and follow ups
`In-page footnotes: fix vertical position when full status bar` : closes https://github.com/koreader/koreader/issues/4444
The other commits fix some issues, and allow getting now in-page footnotes for links in tables (they were previously ignored and so not shown):
<kbd>![image](https://user-images.githubusercontent.com/24273478/50737019-ebde7e00-11c4-11e9-931c-a13c3c35fa6e.png)</kbd>
<kbd>![image](https://user-images.githubusercontent.com/24273478/50737022-f8fb6d00-11c4-11e9-8bd3-c65a36c16669.png)</kbd>
<kbd>![image](https://user-images.githubusercontent.com/24273478/50737041-1597a500-11c5-11e9-9d2 …

 In-page footnotes: various fixes + CSS !important importance handling

---

crengine/src/lvstream.cpp
crengine/src/lvstring.cpp

Because Why The F*** not?! :)
https://en.wikipedia.org/wiki/UTF-8#WTF-8
WTF-8 is a superset of UTF-8, that includes UTF-16 surrogates in UTF-8 bytes (forbidden in well-formed UTF-8).
We may get UTF-8 with these from bad producers or converters.
Actually, our JSON decoder used to build Wikipedia EPUBs may produce such WTF8 content when it gets from the Wikipedia API 4-bytes UTF8 chars (it will be hard to fix in that decoder, and upstream has marked it low priority `https://github.com/harningt/luajson/issues/12`).
Noticed on this https://fr.wikipedia.org/wiki/Wulfila which includes words in _gotique_, which are in Unicode > U+10000, and encoded in 4-bytes UTF8, and returned by the API as:
`<span class=\"lang-got\" lang=\"got\">\ud800\udf45\ud800\udf3f\ud800\udf3b\ud800\udf46\ud800\udf39\ud80 …

Supports book text encoded in WTF-8, workaround ZIP files with corrupted central directories

---

crengine/include/lvfntman.h
crengine/src/lvdocview.cpp
crengine/src/lvfntman.cpp

Original work by @virxkane from https://github.com/buggins/coolreader/pull/58, tweaked for the way we handle the kerning setting and soft hyphens.
Should be nearly as fast as Freetype kerning (full Harfbuzz with ligatures takes ~ 1.5 more time than light Harfbuzz). On my sample big book, a re-rendering takes:
```
Kerning off: 10s
Freetype kerning: 11s (sometimes 14s when switching from some HB kerning).
Harfbuzz light: 13s
Harfbuzz full: 20s.
```
So, that makes 4 kerning option, which is a bit too much for our toggle :)
<kbd>![image](https://user-images.githubusercontent.com/24273478/51089121-6761a180-1768-11e9-8420-24eb7bfe1f27.png)</kbd>
Best I could come up in english:
<kbd>![image](https://user-images.githubusercontent.com/24273478/51089131-7b0d0800-1768-11e9-8d61-5ca6c5a339df.png)</kb …

(Upstream) Adds new kerning method: Harfbuzz light, without ligatures

---

crengine/include/cssdef.h
crengine/include/lvstyles.h
crengine/src/lvfntman.cpp
crengine/src/lvrend.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvstyles.cpp
crengine/src/lvtinydom.cpp

Because it was easy to do and fits well into the page splitting model.
Discussed in https://github.com/koreader/koreader/issues/4484.
If we later decide the previous behaviour (of allowing widow and orphan lines) is to be enforced, we can just get it back by adding to epub.css:
`* { orphans: 1 !important; widows: 1 !important; ` or
`* { orphans: inherit !important; widows: inherit !important; }`
Or we'll just have style tweaks to play with, and one with these to "Ignore publisher orphans and widows specifications".
Also includes Harfbuzz light fixe by @virxkane provided in https://github.com/koreader/crengine/pull/251#issuecomment-454943894
(I also forgot to bump FORMATTING_VERSION_ID in the previous commits, so this one will do that with a bumpier bump of CACHE_FILE_FORMAT_VERSION.)

 CSS: adds support for 'orphans:' and 'widows:' properties

---

crengine/include/lvtinydom.h
crengine/src/lvfntman.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvtinydom.cpp

Includes:
- CSS: adds (limited) parsing of [list-style:](https://developer.mozilla.org/en-US/docs/Web/CSS/list-style) property
The property was there, but its parsing was not implemented, so I added some limited parsing:
It will fail when this shortcut property contains a "url(...)" like list-style-image (we don't support this property), but allows parsing simple ones like "list-style: none" or "list-style: square inside".
Witnessed on the screenshots differences in https://github.com/koreader/koreader/issues/2878.
(There's some code for parsing url() in the section dealing with background-image. Including it there while still allowing in-any-order parsing would take me a few hours and obligatory headaches with that string walking stuff... so may be for later.)
- Avoid "style hash …

Increase max nodes limit, avoid hash mismatch on kerning change

---

cr3gui/data/hyph/French.pattern

`<pattern> dé3s2i2r</pattern>` correct a typo (as it seems it was)

Update french pattern

---

cr3gui/data/epub.css
crengine/include/lvdrawbuf.h
crengine/src/lvdrawbuf.cpp

This will allow frontend code to decide if refresh with (possibly costly) dithering should be used or not on devices with HW dithering capabilities. See https://github.com/koreader/koreader/pull/4541 , https://github.com/koreader/koreader/pull/4541#issuecomment-459947281
Decrease margin-right to give more room to text (as Opera does, even if most other browsers uses the same margin on each side). See https://github.com/koreader/crengine/pull/243#issuecomment-458100435

DrawBuf: count nb of images and surface drawn

---

crengine/src/lvstream.cpp

From https://github.com/buggins/coolreader/pull/77. Ref https://github.com/koreader/crengine/issues/242#issuecomment-460052910

(Upstream) Support UTF-8 filenames in zip archives

---

crengine/src/lvstsheet.cpp
crengine/src/lvtinydom.cpp

We could get stuck on some page (not able to go see next or previous pages that do contain the search
pattern) when this page (or its neighbours) starts with some margin or empty elements that would not
resolve to a XPointer.
This ensures we always find a XPointer to work with by moving a bit the provided y till we find one.
`DIV .classname` would not work as expected, as it was parsed just like `DIV.classname`.
(Note that ancessor rules are still limited because of the non-deterministic/multiple paths to take for checking that we do not take, and work much like just a parent rule.)

Fix CSS ancessor rule parsing, and text search getting stuck on some pages

---

crengine/include/lvfnt.h
crengine/src/lvdocview.cpp
crengine/src/lvfntman.cpp
crengine/src/lvrend.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp

Fix some of the issues noticed and discussed along https://github.com/koreader/koreader/issues/4577.
Including the rendering issue with harfbuzz kerning full (aka "best") described in https://github.com/koreader/koreader/issues/4577#issuecomment-462908911.
See individual commit messages for detail.

Fix font clipping and harfbuzz hyphenation rendering issues

---

crengine/include/lvfntman.h
crengine/include/lvtextfm.h
crengine/src/lvdocview.cpp
crengine/src/lvfntman.cpp
crengine/src/lvrend.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp

Followup to #261. Fix most of the other things noticed along https://github.com/koreader/koreader/issues/4577, summarized in https://github.com/koreader/koreader/issues/4577#issuecomment-463557555.
Was surprised to see some speed up in rendering (my test book went from 10s-loading +5s-rendering to 10s + 3s), probably thanks to the use of the new caches.

Various font, text rendering and highlights fixes and enhancements

---

crengine/src/lvstsheet.cpp

Hello, I was experiencing recurring crashes with few books, and I managed to find the fault, which was a typo. All epub books that previously were crashing koreader now successfully load on my machine.

Fix segmentation fault because of typo

---

crengine/include/lvdocview.h
crengine/src/lvdocview.cpp

Will help fixing highlights in 2-pages mode, specifically https://github.com/koreader/koreader/issues/772#issuecomment-470107420 : 
<kbd>![after](https://user-images.githubusercontent.com/24273478/53966556-ade1d580-40f3-11e9-9d16-ef0c6ea0b269.png)</kbd>
The first line of the 2nd page was previously not highlighted, because its top y was considered part of the first page. Making it considered part of the 2nd page (by using `<` instead of `<=`, and it was highlighted - but then, the bottom line of the first page was not highlighted, because its bottom y was considered part of the 2nd page (see comments in the code for details.)
This will allow using that in cre.cpp to get things right:
```diff
bool docToWindowRect(LVDocView *tv, lvRect &rc) {
lvPoint topLeft = rc.topLeft();
lvPoint …
```

docToWindowPoint(): adds isRectBottom parameter 

---

crengine/include/lvdocview.h
crengine/src/lvdocview.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp

See individual commits and message for details.
Will help solving that rare issue described at https://github.com/koreader/crengine/pull/268#issuecomment-470661095
Will allow toggling `one page | two pages` in landscape mode on any device, and allow the little tweaks made by frontend on pages (extending text selection across pages, showing marker in the margin when following a footnote or back). See https://github.com/koreader/koreader/issues/772#issuecomment-470493499 and https://github.com/koreader/crengine/pull/268#issuecomment-470833786
I tweaked the middle margin sizing to something that I feel is right in all conditions of margins and font size. Some samples:
<kbd>![2pages1](https://user-images.githubusercontent.com/24273478/54221725-5dec7f80-44f4-11e9-85ac-14a71b80f238.png)</kbd> …

2-pages view tweaks, fix words stuck when hyphenating on italic

---

crengine/include/lvfntman.h
crengine/src/lvfntman.cpp

Fix issue with FreeSerif with the "good" kerning implementation, noticed at https://github.com/koreader/koreader/pull/4744#issuecomment-473113760 and investigated in followup posts.
Disalbing "liga" was not enough, there are other such features that need to be disabled to keep one glyph by codepoint, which is a requirement for the HARFBUZZ_LIGHT algorithm.
Glitches could be espacially witnessed with latest FreeSerif on french texts.
Also clear glyph caches when changing fallback font to prevent previous fallback font glyphs from leaking (reason why that happened not found).

Harfbuzz light: disable additional HB features

---

.ci/script.sh
crengine/include/lvrend.h
crengine/include/lvtextfm.h
crengine/src/lvrend.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp

Switch base from 16 to 256 for more granularity. Move it from lUint8 to lInt16 (and not lUInt16, as we'll soon want to use negative values to store fixed size line heights).
Details in https://github.com/koreader/koreader/pull/4785#issuecomment-473111879.
`%` and `em` were handled just like unitless values, being inherited as is, and absolute sizes computed height was just wrong.
Introduce negative line_h/interval to support computed sizes to be used as-is, keeping positive values for
unitless line-height as a factor with base 256. (a)
Switch document root line-height from being 100% to being unitless def_interline_space.
(a) we could probaly kill that and just compute the absolute size even for unitless value in lvrend.cpp - just didn't want to change too much.
Details in …

Line height tweaks: more granularity, fix handlling and inheritance

---

crengine/include/cssdef.h
crengine/include/lvrend.h
crengine/include/lvtextfm.h
crengine/src/lvdocview.cpp
crengine/src/lvrend.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp

Revert #272 , and re-implement line-height handling more correctly, fixing issues noticed in https://github.com/koreader/koreader/pull/4785#issuecomment-474569391:
- CSS: parse `normal` keyword length: can happen with `line-height: normal` and `letter-spacing: normal`.
- (CSS More generic support for parsing or not negative lengths.)
- Handle CSS `line-height` only in lvrend.cpp, and pass an already computed value (in screen pixels) to lvtextfm.cpp (`line_h`/`interval`).
- Compute it for each inline node, as we should (it was computed only from the containing block node, and used by all inline nodes; inline nodes can provide their own line-height, which we should ensure, for the lines this node spans, if it is higher than the "strut".)
- Fix computing of `line-height` in em, % or unitless …

line-height: reworked implemenation for better conformance

---

crengine/src/lvdocview.cpp
crengine/src/lvrend.cpp

When increasing the margin from frontend, at some point it would decrease before increasing again (forgot to include that in previous PR).
Also removed unused variables from previous commit (#273) noticed by clang-tidy.

2-pages mode: fix middle margin sizing

---

crengine/include/lvdrawbuf.h
crengine/src/lvdrawbuf.cpp
crengine/src/lvimg.cpp
crengine/src/lvstsheet.cpp

BGR -> RGB (c.f., https://github.com/koreader/koreader-base/pull/878#issuecomment-476723747).
Also includes a few minor cosmetic tweaks around suspicious-looking alpha-blending codepaths.
And a minor tweak to oddness checks to use AND instead of MOD
(I squashed stuff in logical units, so this should probably be rebased and not squashed ;)).

Fix 32bpp rendering (for our own target BB pixelformat)

---

crengine/include/lvdrawbuf.h
crengine/include/lvstsheet.h
crengine/include/lvtinydom.h
crengine/src/lvdrawbuf.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvtinydom.cpp

Will be requested when in night mode: inverted images will then get inverted back by night mode and displayed normally. See https://github.com/koreader/koreader/issues/2571#issuecomment-477339586
Commit https://github.com/koreader/crengine/commit/12c8e4e11d104c43eff0d423c0a9cf3443eb0ba4 from #263 (_lvtinydom: Adjust ldomXPointer::getRectEx(), used to get the rect of a char, to include its glyph's left and right overflows_) is nice for getting nice rects to highlight, but should generally not be done for other things - so have it done only when needed. Will avoid having "not a coherent xpointer" as seen in https://github.com/koreader/koreader/issues/4840#issuecomment-476603558.
That's [allowed](https://www.w3.org/TR/css-syntax-3/#%21important-diagram), and used in the testsuite: …

Allow drawing images inverted + Some CSS fixes

---

crengine/src/lvrend.cpp
crengine/src/lvtinydom.cpp

In DrawDocument() and elementFromPoint(), where we loop thru all the children of an element to check if their y is inside current page, compute only what's needed before tests that can return early.
This brings some speedup when turning pages on document that have thousands of small paragraphs in a single body/DocFragment.
Details and some profiling data in #277.

Delay some style computations until needed

---

crengine/src/lvstsheet.cpp

Fix some issues noticed by valgrind, reported by @Frenzie at https://github.com/koreader/crengine/commit/8f15e01c8aea15920381f14ea85b0b4abeb36cfd#r32972995
```
==11314== Invalid read of size 1
==11314==    at 0x1B16FCD1: substr_icompare(char const*, char const*&) (lvstsheet.cpp:221)
==11314==    by 0x1B170D92: LVCssDeclaration::parse(char const*&, bool) (lvstsheet.cpp:1153)
==11314==    by 0x1B1783B8: LVStyleSheet::parse(char const*, bool) (lvstsheet.cpp:3009)
==11314==    by 0x1B109BD8: lxmlDocBase::setStyleSheet(char const*, bool) (lvtinydom.cpp:10890)
==11314==  Address 0x145503c9 is 9 bytes inside a block of size 10 free'd
==11314==    at 0x48369AB: free (vg_replace_malloc.c:530)
==11314==    by 0x1B0F1738: lString8::free() (lvstring.cpp:1656)
==11314==    by 0x1B0F1862: release …
```

CSS: fix some attempts to read memory that has been freed

---

crengine/src/epubfmt.cpp
crengine/src/lvdocview.cpp
crengine/src/lvstream.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvtextfm.cpp

See https://github.com/koreader/koreader/issues/4353#issuecomment-479858881
Small thing missed in #273
See https://github.com/koreader/crengine/issues/176#issuecomment-478321727
More generic implementation of #105. See there for details. In some cases, this could happen at start too.

Various fixes: dot in paths, CSS transparent color, line-height

---

crengine/include/lvdrawbuf.h
crengine/include/lvimg.h
crengine/qimagescale/QIMAGETRANSFORM_LICENSE.txt
crengine/qimagescale/qdrawhelper_p.h
crengine/qimagescale/qglobal.h
crengine/qimagescale/qimagescale.cpp
crengine/qimagescale/qimagescale_neon.cpp
crengine/qimagescale/qimagescale_p.h
crengine/qimagescale/qimagescale_sse4.cpp
crengine/qimagescale/qrgb.h
crengine/src/lvdrawbuf.cpp
crengine/src/lvimg.cpp

As discussed in https://github.com/koreader/koreader/issues/1833 ;).
I expect the C++11 minor features (constexpr, nullptr) to fantastically blow up on the PB toolchain, so, this'll probably take a second PR with ifdeffery tweaks ;).

Implement optional 8bpp dithering & image smooth scaling

---

.gitignore

During testing, we need to populate `cr3gui/data/tessdata` with training data. This causes spam in git status all the way up the submodule chain. I propose we gitignore the directory altogether.

Ignore cr3gui/data/tessdata/

---

crengine/include/lvfntman.h
crengine/include/lvtinydom.h
crengine/src/lvdocview.cpp
crengine/src/lvfntman.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp

Depending on the added space between words to ensure text justification, underline (eg: for links spanning multiple words) could have some cuts.
(We can still have some cuts when the words are in distinct text nodes, eg with `<a href="">Louis <span class=roman>XIV</span></a>`, less easy to fix.)
Before:
<kbd>![before](https://user-images.githubusercontent.com/24273478/57122869-d139a180-6d7f-11e9-80e9-3c8dab625bbb.png)</kbd>
After:
<kbd>![after](https://user-images.githubusercontent.com/24273478/57122874-d4349200-6d7f-11e9-863b-c2b249d1d73a.png)</kbd>
As page numbers are calculated only when needed, they could still gather old numbers after book re-rendering, which could lead to wrong TOC page numbers when loading from cache. Details along …

Inter word text decoration, fix TOC page numbers, reproducible cache files

---

crengine/src/lvstream.cpp
crengine/src/lvstring.cpp
crengine/src/lvtinydom.cpp

Use new thirdparty lib https://github.com/JuliaStrings/utf8proc added by https://github.com/koreader/koreader-base/pull/915 for more complete and accurate string uppercase, lowercase and capitalize, used by CSS `text-transform`.
See https://github.com/koreader/koreader/issues/4958#issuecomment-486385893.
Also includes upstream fix for a rare crash https://github.com/buggins/coolreader/pull/89. I don't really know if we could ever be infected, but it looks harmless enough.

Use utf8proc for string uppercase/lowercase/capitalize

---

crengine/src/lvfntman.cpp

Fix small logic error: 'previous' was updated with a valid 'ch_glyph_index' only when going thru char width calculation.
Once that width is cached, we could stay with a possible invalide previous char, and get a different kerning value.
Very minor fix, probably hardly noticable.
I noticed it by accident, by selecting the highlighted word, in a book with embedded fonts that was using Times (which seems to have more kerning rules than any other font) for that title:
<kbd>![image](https://user-images.githubusercontent.com/24273478/58172566-399de380-7c99-11e9-8b7b-6a223c2af26a.png)</kbd>
When selecting that word, some part of the sentence was sliding to the right :) because the `L'` at the start, that should have a -2px kerning, was loosing it on further renderings (which happen when you …

Freetype kerning: fix possible unstable rendering

---

cr3gui/data/epub.css

It was present in the obsoleted txt.css, but its absence from our now generic epub.css made empty lines in plain text files not rendered.
Details in https://github.com/koreader/koreader/issues/5042#issuecomment-496020267

epub.css: add style for empty-line (used on text files)

---

crengine/src/lvrend.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp

Various small rendering fixes, see individual commit message for details.
8th commit _Fix: empty single or last paragraph line should have 0-height_ brings back the proper rendering shown on the screenshots in #223 that was lost when #240 decided to ensure the strut height on all lines.

Various small rendering fixes

---

crengine/include/lvdrawbuf.h

Mainly fully switching to unsigned maths, to simplify the clamping.

Minor cosmetic tweaks to dither_o8x8

---

crengine/include/lvstsheet.h
crengine/src/lvpagesplitter.cpp
crengine/src/lvrend.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp

Various small fixes, see individual commit message for details.
1st commit fixes some lines that may look rendered like the following (which was noticable in table cells):
<kbd>![image](https://user-images.githubusercontent.com/24273478/61145496-e5b0bd80-a4d7-11e9-97af-095c5096097e.png)</kbd>
2nd commits fixes small issue described in https://github.com/koreader/crengine/pull/111#issuecomment-510476050.
I'll bump this after 2019.07, because I haven't really tested these standalone much (they were parts of some bigger float rendering changes, but unrelated, so made into this individual PR).

Various small fixes, adds some CSS attribute selectors

---

cr3gui/data/html5.css

Implement HTML5 Suggested Rendering: https://www.w3.org/TR/html5/rendering.html#rendering
Adapted for crengine from:
https://github.com/FriendsOfEpub/WillThatBeOverriden/blob/master/ReadingSystems/html5/html5.css
(I found a few other ones, including some cleaner at https://github.com/Kozea/WeasyPrint/tree/master/weasyprint/css - but the WillThatBeOverriden one seems to follow the rendering.html page ordering quite as-is.)
Will allow quick switching from epub.css to html5.css in case books expect this HTML5 rendering as their base stylesheet. Discussed in #294.
Still keeping epub.css as our default because we're used to it, it looks better, and html5.css would bring too much changes (see https://github.com/koreader/crengine/issues/294#issuecomment-507227926).
@Frenzie : you understand that …

Adds HTML5 suggested rendering stylesheet (html5.css)

---

crengine/src/lvrend.cpp
crengine/src/lvtextfm.cpp

Fix really bad `vertical-align: top/bottom` and wrong `vertical-align: text-top/text-bottom` when there is some large `line-height:` involved (noticed at https://github.com/koreader/crengine/pull/273#issuecomment-512762418).
(Adding or removing `half_leading` was just tried until it works and we look like Firefox by chance, without much thinking... so, these may be wrong or need additional tweaks).
KOReader before:
<kbd>![valign_bad_top](https://user-images.githubusercontent.com/24273478/61462198-88eb5200-a972-11e9-90e4-485c0ba2baef.png)</kbd> <kbd>![valign_bad_bottom](https://user-images.githubusercontent.com/24273478/61462205-8be64280-a972-11e9-822d-f26946ec9f96.png)</kbd>
This text moving effect was not intended by the HTML, which just looks like:
```html
<div style="line-height: 3"> …
```

Fix vertical-align: top/bottom/text-top/text-bottom

---

crengine/include/lvhashtable.h
crengine/src/crtxtenc.cpp
crengine/src/hist.cpp
crengine/src/hyphman.cpp
crengine/src/lstridmap.cpp
crengine/src/lvdrawbuf.cpp
crengine/src/lvfntman.cpp
crengine/src/lvmemman.cpp
crengine/src/lvstream.cpp
crengine/src/lvstring.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp
crengine/src/pdbfmt.cpp
crengine/src/w32utils.cpp
crengine/src/wolutil.cpp
crengine/src/xxhash.c

Gets rid of explicit memset 0 calls on init, as there are often better ways to achieve that ;).
Also swaps a few malloc + memset 0 to calloc, which should be faster on Linux, because magic.

Minor zero-initalization cleanups

---

crengine/include/lvstsheet.h
crengine/include/lvtinydom.h
crengine/src/epubfmt.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvtinydom.cpp

First commit fixes the _another strange thing_ noticed in https://github.com/koreader/crengine/pull/276#issuecomment-513905987:
> There's another strange thing with this book: when you change some rendering parameters (font size, margins), it triggers a `Styles have changed in such a way that fully reloading the document may be needed for a correct rendering.` popup - which I've never seen happening before when ... styles have no reason to have changed :|
Second commit fixes attribute selectors that should not match when there is no such attribute. It should avoid some uneeded expensive work, as noticed in https://github.com/koreader/crengine/pull/276#issuecomment-517592585.
Third commit makes the parsing of attribute selectors more correct that …

Some CSS attribute selectors and pseudoclasses fixes

---

cr3gui/data/epub.css
crengine/src/lvrend.cpp
crengine/src/lvtinydom.cpp

- Forgot to have `<HR>`  centered by default in enhanced block rendering.
- Some black squares were shown on empty lines when I enabled floating punctuation:
<kbd>![black_BR](https://user-images.githubusercontent.com/24273478/62476456-541b2f80-b7a7-11e9-9062-083181525c00.png)</kbd>
- Highlights in some old test file about list items (opened and still re-opened with an older `cre_dom_version` that use some old list item code) were totally messed up (because of some change related to floats support):
<kbd>![before_list_item](https://user-images.githubusercontent.com/24273478/62476506-6f863a80-b7a7-11e9-828f-2f5547b3d115.png)</kbd>
They are now rendered as they were before:
<kbd>![after_list_item](https://user-images.githubusercontent.com/24273478/62476539-8036b080-b7a7-11e9-8505-de00d3f12619 …

Some small fixes after Enhanced Block Rendering big changes

---

crengine/src/lvrend.cpp
crengine/src/lvstsheet.cpp

- Cleanup formatting, simplify the parsing of some properties.
- Fix slow parsing of `border`, `border-top`... properties, where some uneeded strings containing the full CSS file content were created (and memory allocated). See https://github.com/koreader/koreader/issues/5226#issuecomment-522630738.
Parsing simplified and made conforming to specs (border style is allowed to be absent and default to 'none', instead of skipping the declaration).
Small optimisations to CSS parsing:
- avoid some lowercasing
- compare specific color name before scanning the whole table (may help with our `Pure black & white` styletweak setting `background-color: transparent` on all elements)
Small optimisations to CSS checking:
- `E#id` and `E.class`: skip string manipulations when empty or absent `id=` or …

CSS parsing code: formatting cleanup and optimisations

---

crengine/include/fb2def.h
crengine/include/hyphman.h
crengine/include/lvfnt.h
crengine/include/lvfntman.h
crengine/include/lvpagesplitter.h
crengine/include/lvstring.h
crengine/include/lvtextfm.h
crengine/include/lvtinydom.h
crengine/src/hyphman.cpp
crengine/src/lvfntman.cpp
crengine/src/lvpagesplitter.cpp
crengine/src/lvrend.cpp
crengine/src/lvstring.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp

See individual commit messages for details. Some technical notes in #307.
Some additional work on the block rendering code (list item bullets on the right, ordering of table cells/columns from right to left, H1,H2 `text-align` should be `start` instead of `left` in our epub.css...) is still needed to have full support for RTL documents - but a few style tweaks to force text right alignment may help in the meantime.
For now, we get the following (showing these limitations):
<kbd>![image](https://user-images.githubusercontent.com/24273478/64908045-32448f00-d6fb-11e9-8436-6369b250ff2e.png)</kbd>
More screenshots of arabic and hebrew texts in https://github.com/koreader/koreader/issues/5359#issuecomment-530354985.
Note: we won't draw highlights well when they span bidi segment boundaries, as …

Support RTL/bidi text, some font and harfbuzz fixes

---

crengine/src/lvfntman.cpp

Re-enable c02f5970 (#230) that was reverted by 330d7b18 (#231), as the performance hit [has been fixed on Harfbuzz side by using caching](https://github.com/koreader/crengine/pull/230#issuecomment-450808049).
Also re-init HB fonts on hinting mode change to clear HB's internal caches (so we get reproducible renderings when changing hinting mode - this should fix the frustration I had in https://github.com/koreader/koreader/issues/5359#issuecomment-534626303).
Recent discussion in https://github.com/koreader/koreader/issues/5359.

Re-enable: Use the same FT load flags in HB as in FT

---

cr3gui/data/epub.css
crengine/include/cssdef.h
crengine/include/lvpagesplitter.h
crengine/include/lvptrvec.h
crengine/include/lvrend.h
crengine/include/lvstsheet.h
crengine/include/lvstyles.h
crengine/include/lvtextfm.h
crengine/src/lvdocview.cpp
crengine/src/lvpagesplitter.cpp
crengine/src/lvrend.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvstyles.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp

Followup to #309, which added support for RTL/bidi text. Some technical notes in #307.
This PR completes support for RTL documents, by handling the `dir=` attribute in block nodes, drawing list item markers on the right of the page, and drawing RTL tables' cells from right to left.
See commit messages for details.
Some screenshots:
<kbd>![image](https://user-images.githubusercontent.com/24273478/65821999-72e4f200-e23d-11e9-82b3-d12d455f82fb.png)</kbd>
<kbd>![image](https://user-images.githubusercontent.com/24273478/65822002-82643b00-e23d-11e9-83b9-7e4cd9a5438a.png)</kbd>
<kbd>![image](https://user-images.githubusercontent.com/24273478/65822010-9445de00-e23d-11e9-97e3-0846df9ab20d.png)</kbd>
(/\ [source](https://ar.wikipedia.org/wiki/%D8%A7%D9%84%D8%A8%D8%AA%D8%B1%D8%A7%D8%A1) - \\/ …

Enhanced block rendering: handle RTL direction

---

crengine/src/lvdocview.cpp
crengine/src/lvtinydom.cpp

Fix issue noticed at https://github.com/koreader/koreader/pull/5436#issuecomment-536313311.
Since 5967f723 (#312) and some change to be able to traverse RTL tables for text selection, `LVDocView::getBookmark()`, which is used to get the current page xpointer, could be slow on some pages, or wrong on others.
So, make it clear that, with `createXPointer(lvPoint, direction)` and `elementFromPoint(lvPoint, direction)`, using direction=0 will check for x, while direction=1/-1 will not.
Wherever we are only interested in y, and provide a dummy x=0, we should use direction=1 or -1:
- `getPageDocumentRange()` was already using 1/-1 exclusively.
- `getBookmark()` now does too.
- `getNodeByPoint()` uses 0 to find the exact node at x/y.
- (Others LVDocView methods have not been updated nor checked, …

Fix LVDocView::getBookmark() which could be slow or wrong

---

crengine/src/lvfntman.cpp
crengine/src/lvtinydom.cpp

By just using `FT_LOAD_TARGET_LIGHT` instead of `FT_LOAD_TARGET_NORMAL`, to have hinting only on the y-axis and avoid issues with advance on the x-axis. Details in:
https://www.freetype.org/freetype2/docs/reference/ft2-base_interface.html#ft_load_target_xxx
https://www.freetype.org/freetype2/docs/text-rendering-general.html
See https://github.com/koreader/koreader/pull/5553#issuecomment-548553510

Text: use FreeType light hinting algorithm

---

crengine/include/lvdocviewprops.h
crengine/include/lvtextfm.h
crengine/include/lvtinydom.h
crengine/src/lvdocview.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp

Allow setting a factor that will be applied to the width of all spaces in all fonts (the regular and non-break space only, it won't apply to fixed width spaces). The default option of 100 (%) makes it do nothing.
The existing option "min space condensing percent", used only when trying to find a better line wrap position for text justification, now applies after/on the scaled width.
Details and discussion about that around https://github.com/koreader/koreader/pull/5628#issuecomment-557834352.
Much code just to handle the option passing - the real work is the 2 middle chunks in lvtextfm.cpp.
So, that percentage is applied on the rounded(+truncated with >>6) space width.
I initially thought we'd better do it on the original metric before the >>6, to avoid shifts due to rounding errors. But …

New option to tune word spacing: space width scale percent

---

crengine/src/lvrend.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp

When laying out lines and looking for wrap possibilities, we use the last breakable space found. But we also try to hyphenate the word that follows it to grab a bit of it.
In the case where there are more words after that last breakable space (words separated by a non-breakable spaces, or where our AVOID_WRAP_BEFORE/AFTER checks decided that wrap is to be avoided at these spaces), we would only look at hyphenating the last word of this series of words: if
that fails, we would not try to hyphenate previous words.
We know check hyphenation in all these words.
Sample test case: a french line ending with `pourqu'elle` overflowing max line width (wrap at `'` is avoided):
- if max line width (`$`) is met at `pourq$u'elle`, `pour-qu` hyphenation would be found and used.
- if max line width is …

Text: look for hyphenation in more words if needed

---

crengine/include/lvstsheet.h
crengine/src/lvtinydom.cpp

Backward search could meet the last text node in a paragraph that could be not part of any word, if that last text node contains only spaces (e.g. `<td><span>A few words</span> </td>`).
It could then segfault when `measureText()` that one-space string with` t.start+t.len` of the previous word.
Witnessed on this:
<kbd>![image](https://user-images.githubusercontent.com/24273478/69977710-940edb00-152b-11ea-983e-1bf2d9b1e288.png)</kbd>
Also remove invalid and unused item in CSS selector enum: `E[foo i]`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/321)

Fix possible crash with backward search

---

crengine/src/docxfmt.cpp
crengine/src/lvtinydom.cpp

By @pkb, from https://github.com/buggins/coolreader/pull/119
- Fixed processing of a paragraph with single hyperlink element, no runs
- Don't call virtual method in constructor just to avoid warning
- Handle anchor attribute in hyperlink element
- Added missing # to href
(Needed a bump of CACHE_FILE_FORMAT_VERSION to actually re-parse the docx and have the fix applied on previously opened documents.)
Actually fix in-document table of contents :) Thanks !
Before:
<kbd>![image](https://user-images.githubusercontent.com/24273478/70893758-ff58b280-1feb-11ea-9e6e-ee7ee52cdc6b.png)</kbd>
After:
<kbd>![image](https://user-images.githubusercontent.com/24273478/70894202-d8e74700-1fec-11ea-8736-320732aec719.png)</kbd>
---
This change is [<img src="https://reviewable.io/review_button.svg" …

(Upstream) DocX: fix paragraphs with single hyperlink

---

crengine/include/cssdef.h
crengine/include/fb2def.h
crengine/include/hyphman.h
crengine/include/lvrend.h
crengine/include/lvstyles.h
crengine/include/lvtextfm.h
crengine/include/lvtinydom.h
crengine/src/hyphman.cpp
crengine/src/lvrend.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp

Some additional notes:
- `lvtinydom.cpp: fix Use-after-free` Closes #324.
- `lvtextfm: fix/cleanup lastnonspace code bits` hopefully makes some dubious code right
- `lvtextfm: fix vertical-align: top & bottom` should implement them the right way, by delaying positionning until the full line is laid out. Closes https://github.com/koreader/crengine/pull/302#issuecomment-570061251.
Previous work on vertical-align in #240 and #273.
- `Better selection highlighting by using getSegmentRects()` should have in-progress text selection show just as already-made highlights, which will improve text selection in RTL text.
Should close https://github.com/koreader/koreader/issues/5735
- `Add support for display: inline-block/inline-table` and …

Add support for display: inline-block/inline-table. And other fixes

---

crengine/include/cssdef.h
crengine/include/fb2def.h
crengine/include/lvrend.h
crengine/include/lvstsheet.h
crengine/include/lvtextfm.h
crengine/include/lvtinydom.h
crengine/src/epubfmt.cpp
crengine/src/hyphman.cpp
crengine/src/lvdocview.cpp
crengine/src/lvimg.cpp
crengine/src/lvrend.cpp
crengine/src/lvstring.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp

Some additional notes:
- `CSS: ensure selectors are applied in the order met` discussed in https://github.com/koreader/crengine/pull/170#issuecomment-573414720.
- `Fix getPageDocumentRange() on bidi text` issue explained in https://github.com/koreader/crengine/pull/313#issuecomment-573356486
- `text-indent: some fixes, handle negative & hanging indent` Issues detailed at https://github.com/koreader/koreader/issues/2857#issuecomment-576319227 . Closes https://github.com/koreader/koreader/issues/2857
- `Text: fix: allow wrap on space around images` Sample case:
Before:
<kbd>![image](https://user-images.githubusercontent.com/24273478/72917777-c0352400-3d44-11ea-9c05-6ee504a0b427.png)</kbd>
After: …

Various fixes related to text-indent, CSS order. Adds -cr-hint: strut-confined

---

cr3gui/data/html5.css
crengine/include/fb2def.h
crengine/include/lvpagesplitter.h
crengine/include/lvrend.h
crengine/include/lvtinydom.h
crengine/src/lvdocview.cpp
crengine/src/lvpagesplitter.cpp
crengine/src/lvrend.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp

This does not include any of the xpointers and complete incomplete tables/inline-tables dicussed alongside https://github.com/koreader/crengine/pull/325#issuecomment-580413175, which is more risky and will be in another PR.
The bits in this PR are rather safe. So, they could be bumped for 2020.02 if we let it a few days - but as it seems ready :), they can as well wait and be bumped after.
Not much screenshots this time. Just some for the support of `vertical-align: baseline` in tables:
Before => After
<kbd>![image](https://user-images.githubusercontent.com/24273478/74107166-b2b5d180-4b6d-11ea-8e69-018aff2fd63b.png)</kbd>=><kbd>![image](https://user-images.githubusercontent.com/24273478/74107154-987bf380-4b6d-11ea-803b-853703954d3e.png)</kbd> …

Support vertical-align: baseline in tables, various other fixes

---

crengine/src/lvrend.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvtinydom.cpp

Fix issue with toStringV2() when the node is itself a boxing node. See https://github.com/koreader/crengine/pull/328#issuecomment-591070225.
Also a few commits related to FB2 footnotes (that I don't use, I just have 1 single FB2 file with footnotes...), which may help the user that posted at https://www.mobileread.com/forums/showthread.php?p=3956818#post3956818 on his 2 issues:
`FB2 footnotes: fix spurious newline ("display: run-in")`
I might have discovered why there was this strange support for that obscure/obsolete `display: run-in`:
https://css-tricks.com/run-in/ https://developer.mozilla.org/en-US/docs/Web/CSS/display
It might have been seen as a good and not-hackish solution to solve the fact that FB2 footnotes have a strange structure, and appears in the HTML as:
```html
<body> …
```

Normalized xpointers fix, some FB2 footnotes tweaks

---

.gitignore

We use CRe's data folder as-is for our own data symlink ;).
Fix #331
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/332)

Add libCURL's CA bundle to the ignore list

---

cr3gui/data/fb2.css
crengine/src/lvtinydom.cpp

`FB2 footnotes: fix setBoxingWishedButPreventedByCache()` when handling `display: run-in`.
It was called too early (so, even if we were not to need any autoboxing), causing some invalid display
hash mismatch messages.
`fb2.css: handle body[name="comments"] as footnotes`
`body[name="comments"]` contains another set of notes that can be considered as end notes.
They can be shown in-page too with style tweaks, and need to be wrapped just as "notes" to be properly shown as popup footnotes.
Also remove any hardcoded `font-size`: `font-size` can be fed via style tweaks too if a smaller one is preferred.
Both discussed around https://github.com/koreader/crengine/pull/329#issuecomment-599064384
Will come with updated FB2 footnotes style tweaks.
Note: first commit, if we ignore the indentation …

More FB2 footnotes tweaks

---

crengine/include/lvfntman.h
crengine/include/lvstyles.h
crengine/include/lvtinydom.h
crengine/src/lvdocview.cpp
crengine/src/lvfntman.cpp
crengine/src/lvrend.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvstyles.cpp
crengine/src/lvtinydom.cpp

`CSS: adds support for font-variant`
Details around https://github.com/koreader/koreader/issues/5821#issuecomment-600225376
Most values from CSS-FONTS-3 (31 named-values) are supported, see the code for the list.
Only `font-variant` and its buddies (`font-variant-caps`, `font-variant-ligatures`...) are parsed, but it could be extended to also support `font-feature-settings`.
https://drafts.csswg.org/css-fonts-3/#propdef-font-variant
https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant
https://en.wikipedia.org/wiki/List_of_typographic_features
https://docs.microsoft.com/en-us/typography/opentype/spec/features_ko#tag-onum
Note that I haven't thought about how font-variant should be handled when we need to use the fallback font - so, the fallback font should have currently no OT …

CSS: adds support for font-variant - More FB2 metadata

---

cr3gui/data/epub.css
crengine/include/lvdocview.h
crengine/include/lvtinydom.h
crengine/include/lvtypes.h
crengine/src/epubfmt.cpp
crengine/src/lvdocview.cpp
crengine/src/lvtinydom.cpp

`Fix lvRect:isRectInside(rc) with 0-width or 0-height rect`
will allow closing https://github.com/koreader/koreader/issues/5991
`TOC: parse EPUB3 nav toc, fallback to spine when no toc`
will allow closing https://github.com/koreader/koreader/issues/4915.
EPUB3 nav toc, although less strict that EPUB2 ncx TOC (because some items may not have xpointers, and we require one for each TOC element), will have precedence if both are present, because Sigil may include both, and keep its nav TOC up-to-date, while neglecting to update the ncx TOC.
Also fallback to showing each element of the spine as a TOC item if no TOC is present (as Kobo does as described in https://github.com/kobolabs/epub-spec#table-of-contents-toc).
`Parse and cache various hardcopy page list maps`
will allow closing …

Add support for EPUB3 nav toc and various hardcopy page maps/lists

---

crengine/src/lvrend.cpp

BR shouldn't be handled just like any block element (a height applied to it is not ensured by Firefox or Calibre).
We get more similar results with Firefox/Calibre by just forcing all BR to be `display: inline`.
Revert a bit of 36ae6ccd (from #337) (but let the logic in for `<empty-line>`).
More details in https://github.com/koreader/koreader/pull/6069#issuecomment-615914802 and https://github.com/koreader/crengine/pull/172#issuecomment-615933792.
---
Thought about removing the height in epub.css:
```
/* Element added for each empty line when rendering plain txt files */
empty-line {
height: 1em;
}
```
to keep lines aligned with .txt documents - but they use PRE for each line, which has some top and bottom margins, so preventing any constant line-height alignment.
But just noticed that if …

Force BR to always be display:inline

---

crengine/include/lvdocviewprops.h
crengine/include/lvfntman.h
crengine/include/textlang.h
crengine/src/lvdocview.cpp
crengine/src/lvfntman.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp

`Simplify libunibreak includes`
See https://github.com/koreader/crengine/pull/337#discussion_r410838779
`Text: fix read/write outside array bounds`
Fix crash that could happen (in rare situations) since #337.
(The large diff is just wrapping that section with `if ( pos > 0 ) {`).
Witnessed with an embedded float (so, malloc'ed dynamic buffers), being a `<bdi>` which made text start with U+2068 (FIRST STRONG ISOLATE, which happens to be breakable after a leading space), leading to `|= LCHAR_ALLOW_WRAP_AFTER` modifying byte at -1, causing a double free (while
`&= ~LCHAR_ALLOW_WRAP_AFTER`, done when no break allowed, did not cause any harm.)
Also switch to using a Zero-Width Joiner instead of a space as the initial libunibreak char.
`lvtextfm: dont adjust space after initial quotation …

Allow providing and using multiple fallback fonts

---

crengine/src/lvfntman.cpp

Shows up when using an Arabic nastaliq font, see https://github.com/koreader/koreader/pull/6090#issuecomment-619418198 (and above).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/340)

Font: fix wrong usage of Harfbuzz y_offset

---

crengine/src/lvtextfm.cpp

Fix Issue noticed at https://github.com/koreader/koreader/pull/6112#issuecomment-623679395 and introduced by previous commit (2504a403, #341), witnessed only with `space_width_scale_percent=100`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/342)

Text: fix possible bad widths after collapsed spaces

---

crengine/src/lvfntman.cpp

Fix issue noticed around https://github.com/koreader/koreader/pull/6112#issuecomment-624850251 , made noticable by #341.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/343)

Font/HB: don't add letter-spacing to no-advance clusters

---

cr3gui/data/epub.css
crengine/include/cssdef.h
crengine/include/fb2def.h
crengine/include/lvdocview.h
crengine/include/lvfnt.h
crengine/include/lvfntman.h
crengine/include/lvrend.h
crengine/include/lvstsheet.h
crengine/include/lvstyles.h
crengine/include/lvtextfm.h
crengine/include/lvtinydom.h
crengine/include/textlang.h
crengine/src/lstridmap.cpp
crengine/src/lvdocview.cpp
crengine/src/lvfntman.cpp
crengine/src/lvimg.cpp
crengine/src/lvrend.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvstyles.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp
crengine/src/textlang.cpp

See https://github.com/koreader/koreader/issues/6215
See https://github.com/koreader/koreader/issues/6191
Will allow frontend to feed crengine with TOC markers, so we can have the same markers in the top bar and in the bottom bar. See https://github.com/koreader/koreader/issues/5848#issuecomment-584766009, https://github.com/koreader/crengine/issues/335.
(chores)
Least fancy CSS value... but needed to properly size some table cells and floats (some `:before` pseudo elements are styles with `floats: left; white-space: pre-wrap`)
<kbd>![image](https://user-images.githubusercontent.com/24273478/83775148-eb326b80-a686-11ea-90f0-3038ed8b996a.png)</kbd>
Each colored segment is an element with `white-space: nowrap`: …

CSS: support for pseudo elements ::before & ::after

---

crengine/include/epubfmt.h
crengine/src/epubfmt.cpp
crengine/src/lvtinydom.cpp

Per-specs only, and only if they're declared in a sane order.
(i.e., belongs-to-collection first).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/346)

Support ePub 3 series metadata

---

cr3gui/data/epub.css
cr3gui/data/html5.css
crengine/include/cssdef.h
crengine/include/fb2def.h
crengine/include/lvrend.h
crengine/include/lvstyles.h
crengine/src/lvrend.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp
crengine/src/lvxml.cpp

`Fix some non-recursive subtree walkers`
`Text: skip formatting optimisations when inlineBoxes`
`CSS parsing: parse selectors starting with [attrib]`
`Use T="" for internal elements attributes`
`CSS: re-order css_d_* (display) enum for easier checking`
`Rendering methods: remove erm_table_cell`
`Rendering methods: remove erm_table_caption`
`Rendering methods: remove erm_list_item`
`getRenderedWidths(): better estimate table width`
`styleToTextFmtFlags(): adds is_block parameter`
Some fixes and needed cleanups noticed while making the ruby stuff - but unrelated to the ruby support itself.
See previous discussion and early attempts at supporting ruby via style tweaks in https://github.com/koreader/koreader/issues/6223.
Some final results …

Adds support for "display: ruby" and <ruby> elements

---

.ci/script.sh
crengine/include/lvfntman.h
crengine/include/lvpagesplitter.h
crengine/include/lvptrvec.h
crengine/include/lvref.h
crengine/include/lvstream.h
crengine/include/lvstsheet.h
crengine/include/lvtinydom.h
crengine/include/rtfimp.h
crengine/src/crgui.cpp
crengine/src/cri18n.cpp
crengine/src/crskin.cpp
crengine/src/crtxtenc.cpp
crengine/src/epubfmt.cpp
crengine/src/lvbmpbuf.cpp
crengine/src/lvdocview.cpp
crengine/src/lvdrawbuf.cpp
crengine/src/lvfnt.cpp
crengine/src/lvfntman.cpp
crengine/src/lvmemman.cpp
crengine/src/lvpagesplitter.cpp
crengine/src/lvrend.cpp
crengine/src/lvstream.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp
crengine/src/lvxml.cpp
crengine/src/pdbfmt.cpp
crengine/src/props.cpp
crengine/src/rtfimp.cpp

Trying to fix some clang-tidy warnings. See https://github.com/koreader/crengine/pull/349#issuecomment-651734790.
Let's see how I'm doing so far.
Still 49 "Use of memory after it is freed" to look at.
There are some dubious and some quick&dirty stuff...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/351)

Fix clang warnings

---

crengine/src/lvdrawbuf.cpp

I'm not quite sure what the bit twiddling was attempting to do, because
I'm not familiar with those low bitdepths, but it's almost definitely
wrong for 8bpp targets, where we do *NOT* want/need *any* quantization.
Dates back to 4c9e894b23a5af82ba5b8b7d0678d37a9da11cad
Re https://github.com/koreader/koreader/issues/6345
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/352)

Don't mangle source pixel when alpha-blending to 8bpp

---

crengine/include/cssdef.h
crengine/include/dtddef.h
crengine/include/fb2def.h
crengine/include/hyphman.h
crengine/include/lvstyles.h
crengine/include/lvtextfm.h
crengine/src/hyphman.cpp
crengine/src/lvdocview.cpp
crengine/src/lvrend.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvstyles.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp

Relevant stuff by @virxkane picked from https://github.com/virxkane/coolreader/commit/e461e58c6cc69458204852eed9225e0ad1fa0d6d
Simplify it so this obsolete stuff used to support for FB2 footnotes (see #329) is more localized and does not bleed on too much code.
This also fixes an issue with alignment since #347 cleaning. Will allow closing https://github.com/koreader/koreader/issues/6344.
For reference, FB2 footnotes could be handled with floats (but display: run-in has the benefit of blending in the paragraph, so for Arabic RTL FB2, they would be displayed at start, on the right - unlike with floats):
```css
body[name="notes"] section title,
body[name="comments"] section title {
float: left;
margin: 0;
margin-right: 0.5em; /* spacing after footnote number */
font-size: inherit; …
```

Background images enhancements, fix FB2 footnotes alignment

---

crengine/src/lvmemman.cpp

Remove bits added by 0f19c4ac (#349).
Will allow closing https://github.com/koreader/koreader/issues/6351.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/354)

Fix build on MacOS

---

cr3gui/data/fb2.css
crengine/include/cssdef.h
crengine/include/lvtextfm.h
crengine/src/lvrend.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp

Fix most issues with FB2 noticed from https://github.com/koreader/koreader/issues/6344#issuecomment-655936850 and later comments.
`CSS: adds text-align-last: -cr-right-if-not-first private keywords` 
To be used with FB2 `<v>` https://github.com/koreader/koreader/issues/6344#issuecomment-657347443
`CSS: adds "-cr-only-if: fb2-document"`
Might allow to target some style tweaks to only EPUB or FB2, and avoid some conflicts. https://github.com/koreader/koreader/issues/6344#issuecomment-658273890
`FB2 footnotes: fix spacing between number and text`
Have consistent (1 space, fixed width) spacing between FB2 footnote number and text.
`ldomTextCollector: guess block boundaries better`
Avoid spurious newlines in text selection in various context (FB2 footnotes, ruby...)
(Changes not super tested …

FB2: fix various issues

---

crengine/include/cssdef.h
crengine/include/lvstsheet.h
crengine/include/lvstyles.h
crengine/src/lvrend.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvstyles.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp

`(Upstream) lvstsheet: avoid compilation warnings`
Fix some issue affecting upstream only, See https://github.com/koreader/crengine/pull/339#issuecomment-660298773
`Strut confinning: don't when there is no strut`
Fix list item markers not showing in in-page footnotes (when `-cr-hint: footnote-inpage strut-confined`, allowed with next commit).
`CSS: switch cr-hint from enum to bitmap`
Allows specifying multiple hints on a same node. Might help with #355 if we allow glyph overflows by default, and want to get previous behaviour by specifying it via `-cr-hint:` (on all elements, on only some like tables).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/359)

CSS: switch cr-hint from enum to bitmap

---

cr3gui/data/fb2.css
crengine/src/epubfmt.cpp
crengine/src/lvdocview.cpp
crengine/src/lvfntman.cpp
crengine/src/lvtinydom.cpp

getRenderRectData() is doing that right, but setRendRectData() was possibly not allocating the chunk we're about to use.
Follow up to 0b7cc16e (#358), to fix possible crash when loading some books with embedded fonts.
Investigation in https://github.com/koreader/crengine/pull/358#issuecomment-662544553 and followup comments - thanks @virxkane .
Will allow closing https://github.com/koreader/koreader/issues/6413 .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/361)

More generic cleanup of RenderRect used for CSS caching

---

crengine/include/cssdef.h
crengine/include/lvrend.h
crengine/include/lvstyles.h
crengine/include/lvtextfm.h
crengine/include/lvtinydom.h
crengine/include/textlang.h
crengine/src/lvdocview.cpp
crengine/src/lvrend.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp
crengine/src/textlang.cpp

Updated details below at https://github.com/koreader/crengine/pull/355#issuecomment-665232136
----
Initial comment:
Pushing this early so @zwim (and others!) can play with it and provide some feedback and help take decisions.
This kills the original hanging punctuation implementation (aimed at CJK only), to implement hanging punctuation as some kind of visual margin alignment, as envisionned in #307.
It no more adds padding, it just allows the line to be extended a bit outside its container inner box (which is fine if there's some padding, or if we're the main text and the user has keep some page margins - otherwise in the margins, borders, or over other elements :)
I previously detailed 2 technical options for handling this in https://github.com/koreader/koreader/issues/6235#issuecomment- …

Hanging punctuation: new implementation

---

cr3gui/data/fb2.css
crengine/include/fb2def.h
crengine/include/lvtinydom.h
crengine/src/lvrend.cpp
crengine/src/lvtinydom.cpp
crengine/src/textlang.cpp

Various fixes discussed with @virxkane these last days:
`(Upstream) LVImportStylesheetParser: avoid possible segfault`
(seems to not happen with KOReader, but this simple check looks sane https://github.com/koreader/crengine/pull/355#issuecomment-667652503 )
`(Upstream) FB2: fix <stylesheet> not being applied on first load`
https://github.com/buggins/coolreader/pull/142#discussion_r463956126
`(Upstream) Legacy rendering: partial support of new hanging punctuation`
https://github.com/koreader/crengine/pull/355#issuecomment-667645818
`(Upstream) Fix sentence selection in TTS`
https://github.com/koreader/crengine/pull/69#issuecomment-668175384
`Fix possible crash with 'display: run-in'`
https://github.com/koreader/crengine/pull/355#issuecomment-667689433
`fb2.css: have tables full-width with …

Various small FB2 and other fixes

---

crengine/src/lvdocview.cpp
crengine/src/lvtinydom.cpp
crengine/src/lvxml.cpp

`(Upstream) LVBase64NodeStream: fix possible segfault`
`(Upstream) Fix getting encoding from HTML META tags`
by @virxkane from https://github.com/buggins/coolreader/pull/150.
`FB2: also look for cover in <src-title-info>` https://github.com/koreader/koreader/issues/6493#issuecomment-671357506
`FB2: fix cover image colors` https://github.com/koreader/koreader/issues/6490#issuecomment-671768171
`FB2: don't draw cover in scroll mode` https://github.com/koreader/koreader/issues/6490#issuecomment-671317973
So it does not cover the text (and because correctly drawing the cover in scroll mode looks complicated and feels like it would need some frontend changes - so let's not. we'll revert that if upstream comes up with a solution and see how much change it would require to our frontend).
--- …

Various upstream and FB2 fixes

---

crengine/include/textlang.h
crengine/src/lvrend.cpp
crengine/src/lvtextfm.cpp
crengine/src/textlang.cpp

This implements the crengine part of the changes discussed in #364, it requires exporting `lb_get_char_class` from libunibreak.
**Problem to solve** By default line breaks are allowed at both sides of an em-dash. This causes problems when a dash is at a paragraph or quotation boundary, which may leave a dangling dash in one line. Additionally, in some languages dashes are not supposed to allow line breaks unless there are spaces.
**Solution for easy languages** Just replace the line breaking class of the em-dash with that of the "horizontal bar" (or quotation dash), i.e. a regular letter. This applies to Spanish, possibly French and other languages: `has_em_dash_alphabetic = true`.
**Solution for Engish** The text has to be parsed and decide whether a particular dash should allow breaks …

Try to improve em-dash linebreaks

---

crengine/include/textlang.h
crengine/src/textlang.cpp

Fix possible crash with #365 where we could add 2 more slots in the statically sized array `_lb_props[10]`. Use 20 to be safe for the future.
Noticed at https://github.com/koreader/koreader-base/pull/1160#issuecomment-675045553.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/368)

TextLang: increase _lb_props static array size

---

cr3gui/data/fb2.css
crengine/include/fb2def.h
crengine/include/lvtinydom.h
crengine/include/lvxml.h
crengine/src/docxfmt.cpp
crengine/src/epubfmt.cpp
crengine/src/fb3fmt.cpp
crengine/src/hist.cpp
crengine/src/hyphman.cpp
crengine/src/lvdocview.cpp
crengine/src/lvrend.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp
crengine/src/lvxml.cpp
crengine/src/rtfimp.cpp
crengine/src/wordfmt.cpp

`Revert "FB2: don't draw cover in scroll mode"` (revert lazy workaround from #366)
`(Upstream) FB2: fix coverpage drawing in scroll mode`
Proper solution by @virxkane to this issue, https://github.com/koreader/koreader/issues/6490#issuecomment-678612146 , and fixing a bug of mine.
`FB2 footnotes: only merge run-in when next is erm_final` https://github.com/koreader/koreader/issues/6344#issuecomment-678635145
`fb2.css: use OTF tabular-nums for footnote numbers` https://github.com/koreader/koreader/issues/6344#issuecomment-678637131
`Text: ignore ascii and unicode control chars`
https://www.mobileread.com/forums/showthread.php?p=4025496#post4025496
I'm not sure it's really preferable, I'd like to set the crap I get :) but I guess if we find these control chars, it's usually crap left by …

New HTML parser, libRu and FB2 tweaks

---

crengine/src/lvtinydom.cpp

Don't include `<?xml?>` and the like in the DOM tree.
See https://github.com/koreader/crengine/pull/370#issuecomment-680743042
(The change from printing `<RootNode>` instead `<?RootNode?>` in a DOM dump is totally unrelated: I changed that just for aesthetic reasons :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/371)

HTML parser: ignore XML processing instructions

---

crengine/src/epubfmt.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp

`Text: fix possible crash with duplicated hyphens`
Fix possible crash (infinite loop until an out of memory) with languages having `_duplicate_real_hyphen_on_next_line=true` when text is rendered in a small width (floats, table cells...)
Noticed with, in a small float at 48 dpi, with typography lang set to Serbian (with hyph) or Polish (no hyph), `famille de Valois-Angouleme en haut` that would end up being rendered as:
```
famille
de Valois-
-
-
-
-
-
[infinitely]
Angouleme
en haut
```
when `-Angouleme` happens to not be breakable, except after the initial duplicated hyphen...
`EmbeddedBlock inlineBox: fix createXPointer()/toPoint()`
Tap on links and xpointers highlighting was not working in such embedded blocks (from #330).
`FB2: include footnotes and endnotes start page in TOC` …

Fix possible crash with duplicated hyphens

---

crengine/include/bookformats.h
crengine/include/odtfmt.h
crengine/src/docxfmt.cpp
crengine/src/lvdocview.cpp
crengine/src/odtfmt.cpp
crengine/src/odxutil.cpp
crengine/src/odxutil.h

Adds support for ODT documents (OpenDocument Format), by @pkb, from:
https://github.com/buggins/coolreader/pull/164
https://github.com/buggins/coolreader/pull/165
https://github.com/buggins/coolreader/pull/168 (5th commit)
(I haven't digged into the code :/ I have just checked it works quite well :)
Closes #367.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/377)

(Upstream) Adds ODT (ODF) format support

---

cr3gui/data/epub.css
cr3gui/data/fb2.css
crengine/include/lvrend.h
crengine/include/lvtinydom.h
crengine/src/lvrend.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvtinydom.cpp
crengine/src/lvxml.cpp

Should allow closing https://github.com/koreader/koreader/issues/6632.
See https://github.com/koreader/koreader/issues/6622#issuecomment-686292173
Fix some possible issues with RUBY that would have blank in between or on the sides because of too large estimated widths.
Before | after:
<kbd>![image](https://user-images.githubusercontent.com/24273478/93483385-0ad16500-f901-11ea-8453-3e3798708733.png)</kbd> <kbd>![image](https://user-images.githubusercontent.com/24273478/93483030-a7473780-f900-11ea-8f18-d88eff1bc0ac.png)</kbd>
Also fixe some issues with [the ugly rendering while playing with the MathML CSS handling](https://github.com/koreader/koreader/issues/6346#issuecomment-653774141).
Noticed while playing with that MathML CSS handling styletweak on the big EPUB full of MathML from …

Various small fixes: rendered widths, table head/foot re-orderning

---

crengine/include/fb3fmt.h
crengine/include/lvdocview.h
crengine/include/lvdocviewprops.h
crengine/include/lvrend.h
crengine/include/lvstsheet.h
crengine/include/lvtextfm.h
crengine/include/lvtinydom.h
crengine/include/props.h
crengine/src/epubfmt.cpp
crengine/src/fb3fmt.cpp
crengine/src/hyphman.cpp
crengine/src/lvdocview.cpp
crengine/src/lvopc.cpp
crengine/src/lvrend.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp
crengine/src/props.cpp

`(Upstream) Allow faster LVDocView::getBookmark()`
`(Upstream) Fix scroll mode at start and end of book`
`(Upstream) Fix sentence selection in TTS`
`(Upstream) Fix issues with legacy text rendering`
`(Upstream) Fix FB2 footnotes in legacy text rendering`
`(Upstream) Some CRC32 management fixes`
`(Upstream) FB3/DocX/ODT: get lang and description metadata`
`(Upstream) HyphMan: tweak handling of obsolete pdb files`
`(Upstream) remove global gHangingPunctuationEnabled`
`(Upstream) remove global gRenderBlockRenderingFlags`
`(Upstream) remove global gDOMVersionRequested`
`(Upstream) remove global gInterlineScaleFactor`
Commits from: https://github.com/buggins/coolreader/pull/156 https://github.com/buggins/coolreader/pull/157 https://github.com/buggins/coolreader/pull/160 …

(Upstream) replace global variables, some legacy text rendering fixes

---

cr3gui/data/fb2.css
crengine/include/lvfntman.h
crengine/include/lvstyles.h
crengine/src/lvfntman.cpp
crengine/src/lvrend.cpp
crengine/src/lvstyles.cpp
crengine/src/lvtinydom.cpp
crengine/src/textlang.cpp

`TextLang: German: loosen quotation marks handling`
See https://github.com/koreader/koreader/issues/6717 . This removes some libunibreak specific defaults for "de", but we'll then see if and why these are really needed.
`Fonts: add LVFontManager::getFontFileNameAndFaceIndex()`
Will allow showing font faces in their own font in KOReader Font menu.
See https://github.com/koreader/koreader/issues/6739#issuecomment-703131167.
`fb2.css: avoid break before footnote links`
See https://github.com/koreader/koreader/issues/6718#issuecomment-699600019.
`FlowState: fix possible wrong baseline with nested inline-table`
`Tables: fix possible layout issues with rowspan`
`Table cells: minor refactoring of baseline handling`
`getRenderedWidths(): better estimate table width`
Various generic table fixes I …

Allows for more than 64 styles, some table layout fixes

---

crengine/include/fb2def.h
crengine/include/lvdocview.h
crengine/include/lvdocviewprops.h
crengine/include/lvpagesplitter.h
crengine/include/lvrefcache.h
crengine/include/lvtextfm.h
crengine/include/lvtinydom.h
crengine/src/epubfmt.cpp
crengine/src/lvdocview.cpp
crengine/src/lvfntman.cpp
crengine/src/lvpagesplitter.cpp
crengine/src/lvrend.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp

This contains the backend changes necessary for implementing https://github.com/koreader/koreader/issues/6809:
* Files marked with `linear="no"` in the EPUB spine will be written as `<DocFragment nonlinear="true">`.
* Each page is assigned to the linear flow (0) or to one of possibly many non-linear flows (each source file is a different one). The flow is assigned according to the first line in the page.
* A new method `getPageFlow(page)` is exposed to query the flow to which a given page belongs. Also `hasNonLinearFlows()` to tell whether there are any non-linear flows to care about.
* If the property `crengine.doc.nonlinear.pagebreak.force` is enabled, page breaks will be forced before and after each non-linear flow, to ensure that the non-linear content can be safely skipped by pages. …

Mark non-linear EPUB fragments

---

crengine/src/lvpagesplitter.cpp

With in-page long footnotes, there may be pages made exclusively of footnotes, those have no `pagestart` and end up in flow 0. This should fix it by keeping track of the current flow in `PageSplitState`, so footnote pages are added to the flow that was active before that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/392)

Fix for multi-page footnotes in non-linear pages

---

crengine/include/lvstring.h
crengine/src/lvfntman.cpp
crengine/src/lvrend.cpp
crengine/src/lvstream.cpp
crengine/src/lvstring.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvtinydom.cpp

A few little commits:
`(Upstream) Fix errors in lString16 to 32 update`
See https://github.com/koreader/crengine/issues/389#issuecomment-722528703
`(Upstream) Misc Win32 fixes`
From not yet merged https://github.com/buggins/coolreader/pull/202
`(Upstream) lString32: add 2 additional pos() methods` 
From https://github.com/buggins/coolreader/pull/199. Not used, but might be one day.
`(Upstream) Ignore WORD_JOINER when font has no glyph`
From https://github.com/buggins/coolreader/pull/200
`(Upstream) FB2 metadata: discard empty genres`
From https://github.com/buggins/coolreader/pull/195
`FB2: mark 2nd++ BODYs as non-linear`
So that what's been added for EPUB is also available with FB2 books.
See https://github.com/koreader/koreader/pull/6847#issuecomment-727200617 and follow-ups.
`Fix …

FB2: mark 2nd++ BODYs as non-linear, fix base64 images in EPUB, sync with upstream

---

crengine/include/lvxml.h
crengine/src/lvxml.cpp

~~Was added in #17, requiring the presence of `type="text/css"`. Just stop requirint it.~~
Closes #396.
~~More correct handling of CDATA should probably be implemented, but well/xml/hell...~~ gentle hell actually, so done:
`<div>abc <![CDATA[d<e&>f]]> ghi</div>` will now add intothe DOM 3 text nodes: `abc  `, `d<e&>f` and ` ghi`, as it's supposed to happen in XML/XHTML.
(In HTML, browsers would not do any specific parsing, with possibly strange results. We do it too in plain HTML.)
More details and discussion at https://github.com/koreader/crengine/issues/396#issuecomment-739245637 and follow up.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/397)

XML parsing: correctly parse CDATA

---

crengine/include/pdbfmt.h

PDBFmt unconditionally requires zlib, duh'.
re #399
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/400)

Unbreak !ZSTD builds

---

crengine/include/lvdrawbuf.h
crengine/src/lvdocview.cpp
crengine/src/lvdrawbuf.cpp
crengine/src/lvfntman.cpp
crengine/src/lvrend.cpp

(Essentially reverts #275)
c.f., https://github.com/koreader/koreader-base/pull/1265
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/402)

Get rid of RevRGB & co

---

crengine/include/lvtinydom.h
crengine/include/lvxml.h
crengine/src/lvxml.cpp

`EPUB: fix truncated HEAD>STYLE stylesheet` Closes #403
`XML parsing: slightly better parsing of <script>` Closes #401
Handle content as text, but don't stop just at any '<', only at '</script>', as <script> may contain tags.
Not doing that might put a lot of javascript as document text content. Note that <script> content is "display: none" by default.
This is not perfect (no script tag case check for balancing), but might work in most cases.
Not tested: <script> + CDATA :/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/405)

XML parsing: slightly better parsing of <script>

---

crengine/include/cssdef.h
crengine/include/lvrend.h
crengine/include/lvstyles.h
crengine/src/epubfmt.cpp
crengine/src/lvrend.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvstyles.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp

See https://github.com/koreader/crengine/issues/360#issuecomment-756810641. Closes #360.
`CSS: parse and store min/max-width/height`
Increase nb of bitmaps from 2 to 3 lUInt32 as we're going over 64 properties.
`Add getStyledImageSize() ensuring min/max-width/height`
Compute image size according to CSS2 specs, ensuring CSS `width`, `height`, `min-width`, `min-height`, `max-width` and `max-height`.
Used in lvtextfm when drawing images, and when estimating block widths in `getRenderedWidths()` instead of the previous wrong computation.
Limitation: heights in `%` are not supported and ignored.
`renderBlockElementEnhanced(): ensure min/max-width/height`
Ensure `min-width`, `min-height`, `max-width` (but not `max-height`) on block elements, inline-block/table, block floats and floating images …

CSS: add support for min-width, max-width, min-height, max-height

---

crengine/include/lvdocview.h
crengine/include/lvdocviewprops.h
crengine/include/lvtinydom.h
crengine/src/lvdocview.cpp
crengine/src/lvtinydom.cpp

The 3 first commits will allow more proper support for "Dual page" mode in KOReader, actually making it feel more as "Two columns".
Previous related discussions in https://github.com/koreader/koreader/issues/7129 and https://github.com/koreader/crengine/pull/408
Supercedes https://github.com/koreader/crengine/pull/408.
Can be set by frontends to get one page number per view instead of 2 when in 2-pages mode, actually making it feel like 2-columns on 1 page.
Updating 4 public methods is all it needs: `getCurPage()`, `getPageCount()`, `getBookmarkPage()` and `goToPage()`. They now return or accept the "external" page number (which differs from the "internal" page number when `VisiblePageCount=2` and `m_twoVisiblePagesAsOnePageNumber=true`.
As the crengine code itself use these methods, some …

2-pages mode: twoVisiblePagesAsOnePageNumber, single wide header

---

crengine/include/lvstring.h
crengine/src/lvfntman.cpp
crengine/src/lvstring.cpp
crengine/src/lvtextfm.cpp

`(Upstream) Text: don't remove trailing space on last word if pre`
From https://github.com/buggins/coolreader/pull/236
`(Upstream) Text: replace notfound glyphs only on last fallback font`
Make non-Harfbuzz drawing similar to Harfbuzz drawing:
Changed the search logic for missing glyphs: first, we search for a glyph in all fallback fonts without replacing missing ones, and at the end, if a glyph is not found, we replace it with a replacement one.
From 2nd commit of https://github.com/buggins/coolreader/pull/239
`(Upstream) Add a few lString8 methods`
Needed by upstream QT frontend for checking language tags.
From https://github.com/buggins/coolreader/pull/235
----
Considered but not (yet) picked:
`(Upstream) Ordered list markers: add a decimal point suffix` …

Minor upstream fixes: keep last word space if pre, replacement char on last fallback font only

---

crengine/include/cssdef.h
crengine/include/lvrend.h
crengine/src/lvrend.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvtinydom.cpp

Discussed at https://github.com/buggins/coolreader/pull/246
Btw is it possible to disable the image scaling from the KOreader UI, to better test this code on KOreader?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/413)

CSS: add units vw vh vmin vmax

---

crengine/src/epubfmt.cpp
crengine/src/lvdocview.cpp

See https://github.com/koreader/koreader/pull/7204#issuecomment-769661194
See https://github.com/koreader/koreader/issues/7219#issuecomment-770442114
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/415)

Small fixes: crash on missing items in EPUB, 2-pages mode/1-page number alt title/author

---

crengine/include/cssdef.h
crengine/include/lvpagesplitter.h
crengine/include/lvstyles.h
crengine/include/lvtextfm.h
crengine/src/lvdocview.cpp
crengine/src/lvpagesplitter.cpp
crengine/src/lvrend.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvstyles.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp

An image having its bottom on the baseline, don't account for the strut added space below when this space would be negative (ie. with line-height: 0, which might be explicitely used to kill that strut added bottom blank space).
See https://github.com/koreader/koreader/issues/7257#issuecomment-774648460. Will allow closing https://github.com/koreader/koreader/issues/7257
Measured widths could be wrong when other unicode space chars are used, which should not collapse.
Noticed with some MathML book abusing that kind of thing to add spacing:
```html
<mtext>&#8201;</mtext><mtext>&#8201;</mtext><mtext>&#8201;</mtext>
```
Will be needed for MathML `<mphantom>`. Feels totally uneeded with eBooks, but I figure it can be nice to have, allowing hiding some content via style tweaks, for example …

CSS: adds support for "visibility: hidden", and other fixes

---

crengine/include/cssdef.h
crengine/include/lvstyles.h
crengine/include/lvtextfm.h
crengine/include/textlang.h
crengine/src/lvrend.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvstyles.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp
crengine/src/lvxml.cpp
crengine/src/textlang.cpp

Avoid '`</sc`' at buffer end to miss matching '`</script>`' if it would come next when reading from file stream.
A bit of clean up of this part of the code, added comments as I understand what bits are supposed to do.
A bit risky though - spent hours on this, but not 100% sure I didn't break anything.
See https://github.com/koreader/crengine/pull/405#issuecomment-781570875 and follow ups.
"en" and "en-US" do start with "en", but "eno" should not.
Proper parsing of "!important" at end of font-family.  Also try to handle "inherit" in the most compatible way, even if not per current specs: "inherit" is nowadays invalid when not standalone.
We have seen books with '`font-family: "Some Font", inherit`', that Calibre 3.x would render with "Some Font", while Firefox and Calibre 5.x would …

CSS: add support for 'line-break' and 'word-break', and other fixes

---

crengine/include/cssdef.h
crengine/include/lvrend.h
crengine/include/lvstyles.h
crengine/src/lvfntman.cpp
crengine/src/lvimg.cpp
crengine/src/lvpagesplitter.cpp
crengine/src/lvrend.cpp
crengine/src/lvstring.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvtinydom.cpp

A few fix and tweaks I needed for MathML support, but that aren't MathML specific - so here in an independant PR.
It was working somehow as we mostly use them with count=1, but it was wrong when count >=2. See https://github.com/koreader/crengine/pull/71#issuecomment-798798891
Follow up to 5330750b: when getting a non-boxing parent or child, be sure we actually get one (as we can have nested boxing elements, like tabularBoxes with completed incomplete tables).
When there are multiple font names in a list (ie, with CSS 'font-family: "Font1", "Font2"', multiple fonts may get the same higher score. We keep the first best match in the loop, but at the end, we prefer an instantiated font to a not yet instantiated one with the same math.  Depending on various things, it may not be the first …

Various fixes and tweaks before MathML support

---

cr3gui/data/hyph/German.pattern

After 23 months a new version of the dehypn-exptl patterns were released: https://ctan.org/pkg/dehyph-exptl?lang=de
The new patterns in this PR are based on dehypn-expt 0.7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/431)

new patterns based on dehyph-exptl 0.7

---

crengine/include/lvarray.h
crengine/include/lvdocviewcmd.h
crengine/include/lvdocviewprops.h
crengine/include/lvfntman.h
crengine/include/lvrend.h
crengine/include/props.h
crengine/src/crtxtenc.cpp
crengine/src/epubfmt.cpp
crengine/src/lvdocview.cpp
crengine/src/lvfnt.cpp
crengine/src/lvfntman.cpp
crengine/src/lvrend.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp
crengine/src/mathml.cpp
crengine/src/props.cpp

From upstream https://github.com/buggins/coolreader/pull/274 by @virxkane, large discussion there.
Includes a few followup fixes and tweaks.
Didn't pick the changes to measureText() and drawTextString() to use 26.6 units, as this could cause some glitches with the normal rendering, as noticed in https://github.com/koreader/koreader/issues/4174#issuecomment-815270310.
@virxkane original 26.6 changes is included as an individual commit below, but reverted.
Then I decided to keep the idea of compensating the emboldening with tweaking letter-spacing, which was OK, but a bit frustrating as then, it didn't happen for small weights increase, so, font-weights adjustments didn't look much different than gamma changes :/ And these constant letter spacing addition make it look a bit ugly like our …

Fonts: more granular weights (real and synthetic)

---

crengine/include/lvstring.h
crengine/src/lvfntman.cpp
crengine/src/lvstring.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp

`getCharProp()` is nearly no longer used when using libunibreak, but it is still used by `lStr_findWordBounds()` to detect words to try to hyphenate.
It knowing only about latin, greek and cyrillic letters made hyphenation not detect any candidate word in Armenian and Georgian text.
So, fallback to use utf8proc to detect letters in any other alphabet so hyphenation (including soft-hyphens) can work.
Also detect RTL chars, as we don't want to hyphenate on soft-hyphens in Arabic or Hebrew, as the text rendering code currently can't draw hyphens on the left.
Will allow closing https://github.com/koreader/koreader/issues/7539
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/4 …

Fix hyphenation on Armenian and Georgian text

---

cr3gui/data/fb2.css
crengine/src/lvtextfm.cpp
crengine/src/lvxml.cpp

In case footnotes' `<body>` don't come with a proper `<title>` that would have ensured this page break.
See https://github.com/koreader/koreader/pull/7625#issuecomment-830662168
Increase the buffer size for recognition of named character references to handle all those expected to be recognised. The longest name in the `def_entity_table[]` appears to be CounterClockwiseContourIntegral" so including a trailing null a buffer size of 32 is needed.
From https://github.com/buggins/coolreader/pull/287
Should allow closing https://github.com/koreader/koreader/issues/7661 and hopefully won't cause much harm.
Rework 89b0650e: ignore the space even if followed by another text node; just don't ignore it for the first line where it could have some purpose (eg. to add some indentation).
See …

Various XML, text and FB2 fixes

---

crengine/include/hyphman.h
crengine/include/lvdocviewprops.h
crengine/src/hyphman.cpp
crengine/src/lvdocview.cpp
crengine/src/lvtinydom.cpp

The first round of testing went fine.
I have tried a huge user hyphenation dictionary with about 14MB and 400'000 word. Rendering time was as fast as with the same word in a *.pattern file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/439)

User hyphenation dictionary

---

crengine/src/hyphman.cpp

Two bugs are resolved here:
1.) The filename/filesize should also be cleared on an unload, so that the lazy dictionary load can check this.
2.) `lString32 words[]` has to be released.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/440)

User hyphenation dict: some memory cleanup fixes

---

crengine/include/lvfntman.h
crengine/include/lvplatform.h
crengine/qimagescale/qdrawhelper_p.h
crengine/src/lvdrawbuf.cpp
crengine/src/lvimg.cpp

c.f., the discussion in #426
It's fairly anecdotal for LvImg, but it might yield significantly better performance in LvFntMan, because, arguably, memcpy'ing cached glyph bitmaps around is kinda what CRe does the most ;p.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/441)

Allocation & alignment trickeries

---

crengine/include/cssdef.h
crengine/include/lvarray.h
crengine/include/lvtextfm.h
crengine/src/lvdocview.cpp
crengine/src/lvopc.cpp
crengine/src/lvpagesplitter.cpp
crengine/src/lvrend.cpp
crengine/src/lvstring.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp
crengine/src/mathml.cpp
crengine/src/mathml_table_ext.h
crengine/src/textlang.cpp

**(Upstream) lvstring: fix signed integer overflow
(Upstream) lvopc: fix memory leak
(Upstream) ldomDocument(): fix memory leak
(Upstream) lvtinydom: fix memory leaks**
From https://github.com/buggins/coolreader/pull/299
Fix oversight in our decb46c75db253ac52639029085fc7ea821e6b40 / https://github.com/buggins/coolreader/commit/a11201401e1bba63039140c0ae5d807948a51f63#diff-f37b0ebc86a9c3391b92d47a8dce2d3cdb5cc270e2dcf07b4ef73af5e1d4af6f  I guess,
(Pinging @virxkane  for info).
Can be handy to counteract https://github.com/koreader/crengine/pull/423#issuecomment-856147122.
See, and should allow closing https://github.com/koreader/koreader/issues/7913.
Footnote links inside floats were previously associated to the line before the float, which could make them shown on the previous page if …

Page splitting: revamp, fix some issues

---

crengine/src/lvtinydom.cpp

First of all: We are not hit by this bug, because we check for a valid pattern before doing the search.
The bug would be triggered:
pattern1 correct -> regex cached
pattern2 incorrect -> regex gets destroyed, but cache key is not invalidated
pattern1 cached regex (which was destroyed) would be used :(
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/445)

Regex search: fix potential pattern cache bug

---

.github/workflows/build.yml
crengine/include/lvdocview.h
crengine/include/lvhashtable.h
crengine/include/lvstring.h
crengine/include/lvtinydom.h
crengine/src/chmfmt.cpp
crengine/src/lvdocview.cpp
crengine/src/lvfntman.cpp
crengine/src/lvstring.cpp
crengine/src/lvtinydom.cpp
thirdparty/chmlib/src/lzx.c

Picking what we can easily from https://github.com/buggins/coolreader/pull/304 and https://github.com/buggins/coolreader/pull/307:
- methods added to base objects, that can be helpful with future devs
- stuff that touches things we don't use (LVDrawBookCover, sentence selection fixes) and that git applied without much complain
- some easy cleanup.
Many other things not picked as they touch mostly the UI<->Core interface and we have already diverged too much, so even if I would have liked picking https://github.com/buggins/coolreader/commit/2d693aedd44c93 to keep much of that in sync, I didn't as we have diverged because of previous added things that we didn't need and I didn't picked at the time :/
Also, some top status bar refactoring that couldn't be integrated because we did some …

(Upstream) Various minor picks to keep some bits in sync

---

cr3gui/data/epub.css
cr3gui/data/html5.css
crengine/include/cssdef.h
crengine/include/lvstsheet.h
crengine/include/lvstyles.h
crengine/include/lvtinydom.h
crengine/src/chmfmt.cpp
crengine/src/lvdocview.cpp
crengine/src/lvfntman.cpp
crengine/src/lvrend.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvstyles.cpp
crengine/src/lvtinydom.cpp

Rework bits from 46ad95e3 to not include declaration of static variables from fb2def.h, saving 20KB of libcrengine.so size.
Discussed around https://github.com/buggins/coolreader/pull/308#discussion_r699276529. Picked from https://github.com/buggins/coolreader/pull/310.
Follow up to 545e609ee.
This also makes sure that our specific XHTML DOM element handling in ldomDocumentWriter only match on real books and not on secondary XML files (like .opf, .ncx...) parsed with LVParseXMLStream().
Also use `getAttributeValueLC()` when appropriate.
Also make `attr_dir` comparisons more readable.
This is already done for some formats like EPUB/DocX...
Be sure it's also done for simpler formats like HTML, before the DOM writers act, so the root node can get its style set.
(This was not really an issue, …

CSS: add support for 'box-sizing', and various other fixes

---

crengine/include/lvstsheet.h
crengine/include/lvtinydom.h
crengine/src/lvstring.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvtinydom.cpp

`lString32Collection::erase(): fix bounds checking`
As already done correctly in `lString8Collection::erase()`.
Before this fix, a single stylesheet associated to an EPUB html fragment would have been parsed twice; this may then speed up applying styles to nodes in this case.
Details at https://github.com/koreader/koreader/issues/8384#issuecomment-961294424
Bug since #454, causing x2 / x3 slowdown on EPUBs where fragments reference a single stylesheet.
`ldomDocumentFragmentWriter: fix OnTagBody called twice`
It caused issues with some combinations of styles/fonts are set on a BODY element.
See https://github.com/koreader/koreader/issues/8417#issuecomment-961950942
Should allow closing https://github.com/koreader/koreader/issues/8417.
`CSS: optimize E.class rule check`
`CSS: optimize E#id …

CSS: some fixes and optimisations

---

crengine/src/lvstsheet.cpp

So we can tweak our style tweaks for all other supported formats if need be.
See https://github.com/koreader/koreader/issues/8456#issuecomment-974659281
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/460)

CSS: adds "-cr-only-if: txt-document" and other formats

---

crengine/include/lvtextfm.h
crengine/include/textlang.h
crengine/src/lvdocview.cpp
crengine/src/lvtextfm.cpp
crengine/src/textlang.cpp

`setStatusFontSize/Face(): avoid spurious re-rendering`
Update the font instance as soon its size or face is updated. Should help fixing https://github.com/koreader/koreader/pull/7312#issuecomment-986180114, see followup comments there.
Also call updateLayout() on main font size change, as in 2-pages mode, the middle margin needs to be recomputed. See https://github.com/koreader/koreader/pull/8501#issuecomment-986271199.
Otherwise, these would be noticed later and cause spurious and uneeded re-renderings.
`Hanging punctuation: include it in native highlighting`
The part of punctuation hanging in the right margin wasn't included in the "native" text selection highlighting because the range segments were cropped to frmline-width.
So, remember by how much we overflow it, and extend the crop …

Avoid some re-renderings, hanging punctuation tweaks

---

crengine/include/lvdocview.h
crengine/src/epubfmt.cpp
crengine/src/lvdocview.cpp
crengine/src/lvtinydom.cpp

CoolReader CSS macro processing of user-agent stylesheets prevents using `p[id$="foo"]` (to match "foo" at the end of the "id" attribute value, as anything starting with a `$` is handled as a macro and replaced, which may corrupt normal stylesheets (and style tweaks).
We will use this on our side:
```diff
--- a/cre.cpp
+++ b/cre.cpp
@@ -1580 +1580 @@ static int setStyleSheet(lua_State *L) {
-       doc->text_view->setStyleSheet(css);
+       doc->text_view->setStyleSheet(css, false); // Skip crengine substituteCssMacros()
```
Fix initial parsing of CSS files (used to see if any embedded fonts), that would stumble on `txt ******/` depending if odd or even number of `*`.
This fixes issue 1 reported at https://github.com/koreader/koreader/issues/8715#issuecomment-1019537155
---
This change …

CSS: minor parsing fixes

---

crengine/src/hyphman.cpp

Find word boundaries before doing the gethHyphenation lookup.
Use in conjunction with #468
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/469)

Trim word in getHyphenation (in conjuction with #468)

---

.github/workflows/build.yml

Cf. `https://github.com/actions/virtual-environments/issues/1757`. This will likely add about 10 extra seconds to the runtime.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/471)

[CI] Run apt-get update before apt-get install

---

crengine/include/lvstring.h
crengine/include/lvtinydom.h
crengine/src/hyphman.cpp
crengine/src/lvdocview.cpp
crengine/src/lvrend.cpp
crengine/src/lvstring.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp

Followup to #468, hoping to get now a more consistent char categorization without duplicated code (that could contradict each other), and trusting Unicode (via utf8proc).
Reorganize `CH_PROP_*` flags: remove unused ones, combine some of them to possibly get new slots for the future.
Fix some chars' `CH_PROP`, have `getCharProp()` correctly set them for other ranges thanks to utf8proc categories, even if some of these flags are not used yet.
(Added CH_PROP_PUNCT_OPEN/CLOSE even if not used currently, it might be useful with CJK typography https://github.com/koreader/koreader/issues/6162.)
Factorize RTL detection in `lStr_isRTL()`.
Factorize CJK detection in `lStr_isCJK()`.
Remove wrong defines of CJK ranges: they were mostly used in legacy code (where we harcoded these bad ranges, not …

Rework and cleanup char categorization and word selection

---

crengine/src/lvdrawbuf.cpp
crengine/src/lvrend.cpp
crengine/src/lvstsheet.cpp

Followup to #474 : lvdrawbuf: also handle alpha in DrawLine() (forgotten in ada7342e8f).
Handle alpha in lvrend.cpp DrawBorder(). Should allow closing https://github.com/koreader/koreader/issues/8991 .
Behave as Firefox with "border-color: black" for border-style outset/inset/groove/ridge, using some fixed values of gray.
Also fix parsing of 8-digits hex color values.
Different alpha values on each side:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/476)

lvdrawbuf: handle border colors with alpha

---

crengine/include/lvtextfm.h
crengine/src/lvrend.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp

First 3 commits are just cleanups to allow for the main 4th commit.
We have room in `src_text_fragment_t` in the union struct used for objects, so put object-only flags in there, leaving more bits available in the 'flags' field shared by object (image, inline-block, floats) and text fragments.
(This is just reorganisation, no rendering change.)
Also rename `OBJECT_CHAR_INDEX` to `IMAGE_CHAR_INDEX`.
Also remove `LTEXT_WORD_` unused flags.
To keep things clearer and avoid some function calls.
Handle left/right margin/border/padding on inline elements.
Also add limited support for top/bottom borders (drawn at line height edges, no support for vertical padding).
Only dotted/dashed/solid border styles are handled (any other style is drawn as solid).
Should allow closing …

Add support for inline margin/border/padding

---

crengine/include/lvtinydom.h
crengine/src/epubfmt.cpp
crengine/src/lvtinydom.cpp

Add a method (available to frontends) to build a synthetic page map, with a new page number every N chars.
This could allow a frontend to show stable page numbers, that do not change with the rendering.
Initial idea described at https://github.com/koreader/koreader/issues/9020#issuecomment-1104374155.
This reuses what was added in https://github.com/koreader/crengine/pull/336  and https://github.com/koreader/koreader/pull/6004.
The function to build it is just there, it works, takes a little bit of time to navigate all the text nodes (too complicated to do it as XML parsing time, and most people won't need it, so no need to force doing it here and waste space and memory - people who want it can bear the additional time it takes).
I'm still not sure how/if this could go into KOReader's …

PageMap: allow building synthetic pages numbers

---

crengine/include/lvstring.h
crengine/src/lvfntman.cpp
crengine/src/lvrend.cpp

Use ASCII minus char instead of Soft-Hyphen char as the latter may be unavailable/blank/bad in some fonts, while the former is usually perfect.
See https://github.com/koreader/koreader/issues/9074#issuecomment-1120099697 and followup posts.
Should allow closing https://github.com/koreader/koreader/issues/9074.
A 2nd `<tr>` in a `<thead>` was moved above the first `<tr>` (the fix is just how it is done for `<tfoot>`).
See https://github.com/koreader/crengine/pull/379#issuecomment-1120263579.
Should fix https://www.mobileread.com/forums/showthread.php?t=346684
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/479)

Use the right hyphen glyph, fix table THEAD with multiple TRs

---

crengine/include/cssdef.h
crengine/include/lvdocviewprops.h
crengine/include/lvfnt.h
crengine/include/lvfntman.h
crengine/include/lvtextfm.h
crengine/include/lvtinydom.h
crengine/include/textlang.h
crengine/src/lvdocview.cpp
crengine/src/lvfntman.cpp
crengine/src/lvrend.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp
crengine/src/textlang.cpp

Improve CJK typography (mostly Chinese and Japanese, Korean didn't really need and doesn't get anything), as discussed over the last 2 years in https://github.com/koreader/koreader/issues/6162.
Should allow closing https://github.com/koreader/koreader/issues/6162 and https://github.com/koreader/koreader/issues/6078.
Skip them early (not sure if it's really the best thing to do) to avoid a possible crash later when `font->measureText()` an empty string. Closes #481.
Some publishers include 〘 and 〙 around a `<rt>` so that, when ruby is not supported, these are displayed inline and wrap the annotation.
We'd rather have them not shown by having them wrapped and swallowed/hidden among table-like elements.
This is a quick simple solution to get Traditional Chinese punctuation back, and should …

Improved typography for Chinese and Japanese

---

crengine/include/lvdocview.h
crengine/include/lvfntman.h
crengine/include/lvtinydom.h
crengine/src/chmfmt.cpp
crengine/src/lvdocview.cpp
crengine/src/lvfntman.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp
crengine/src/lvxml.cpp

Messed by a7cea02c #482: it since fails detecting Harfbuzz is used and would handle bracket mirroring, and we end up mirroring them and Harfbuzz unmirroring them, resulting in messed up brackets in Arabic and Hebrew.
Noticed at https://github.com/koreader/crengine/pull/483#discussion_r889719759, thanks @weijiuqiao.
Met in some CHM files at https://github.com/koreader/koreader/issues/9176#issuecomment-1147386804
May be used to extend highlight to include punctuations, some idea at https://github.com/koreader/koreader/issues/8857#issuecomment-1151198923
Should allow selecting text by panning from/to/inside the outer margins, and getting something better/nearer when in paragraph left/right margins or in their collapsed top/bottom margins.
See …

Tweaks to allow text selection in margins

---

crengine/include/cssdef.h
crengine/include/lvstsheet.h
crengine/src/lvimg.cpp
crengine/src/lvrend.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp

Should allow `'* { -cr-hint: late; ... }'` to be checked and applied after other selectors with higher specifity.
This can be useful with style tweaks, and makes tweaks a lot simpler.
See https://github.com/koreader/koreader/pull/5863#issuecomment-1173095462
Existing values are static, and depend on the document and rendering options.
Add a few non-static ones, that need to be saved in the declaration and checked on each node.
This allows such combinations:
```css
* { -cr-only-if: inside-inpage-footnote -inpage-footnote -inline;
margin: 0 !important; display: inline; }
```
See https://github.com/koreader/koreader/pull/5863#issuecomment-1173097714
When `gRenderDPI`=0 (old crengine behaviour), `lengthToPx()` returns 0 for absolute CSS units (in, cm, mm, pt, pc), which might be ok for …

CSS: add a few style tweaks helpers, and other fixes

---

cr3gui/data/epub.css
cr3gui/data/fb2.css
crengine/include/lvdocviewprops.h
crengine/include/lvfntman.h
crengine/src/lvdocview.cpp
crengine/src/lvfntman.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp
crengine/src/lvxml.cpp

Since #454, text in PRE could overflow the PRE width. Fix that.
As crengine/FreeType can't distinguish sans serif from serif, this is only useful to detect if a font is monospace or not. Might be useful for frontends.
See https://github.com/koreader/koreader/issues/9211#issuecomment-1160556267.
Should trigger a rerendering when we change the bias of some fonts.
Also fix `GetFontListHash()` which was always returning 0 since ages...
This should allow another monospace font, set with a bias, to be used for `<pre>` and `<code>` (as with anything having `font-family: monospace`).
So that when using a main font with a small x-height, one can avoid having tall inline `<code>` bits, and adjust them (manually) to fit the size of the main font or to be a bit smaller to help distinguishing them. …

Monospace and fallback fonts tweaks

---

crengine/include/cssdef.h
crengine/include/lvdocviewprops.h
crengine/include/lvfntman.h
crengine/include/lvtinydom.h
crengine/src/lvdocview.cpp
crengine/src/lvfntman.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvtinydom.cpp
crengine/src/mathml.cpp
crengine/src/mathml_css_h.css

Properly parse (instead of dropping/skipping):
```css
m|math { display:block; }
[m|foo] { background-color: yellow ; }
[m|foo|="bar"] { font-weight: bold; }
```
so these are matched (namespaces are ignored when matching selectors):
```html
<math foo="bar-baz">
<m:math m:foo="bar-baz">
```
Check for math support at font registration time.
Allow frontends to provided a list of font to use with each of the generic font-family names.
Also let `font-family: math/emoji/fangsong` be supported.  Have the font set for "`font-family: math`" font be used with MathML `<math>`.
This will allow implementing support for font-family in KOReader, see https://github.com/koreader/koreader/issues/7426#issuecomment-1258335839 .
- - -
This change is [<img src="https://reviewable.io/review_button.svg" …

CSS/Fonts: add support for font-family to font name mapping

---

crengine/include/textlang.h
crengine/src/lvtinydom.cpp
crengine/src/textlang.cpp

Can be used by frontends to get any text soft-hyphenated according to crengine hyphenation dicts.
Code and logic taken (and removed) from writeNodeEx().
Will help with https://github.com/koreader/koreader/pull/9630.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/492)

TextLang: add TextLangCfg->softHyphenateText(lang, text)

---

crengine/include/lvstsheet.h
crengine/include/lvtinydom.h
crengine/src/lvstsheet.cpp
crengine/src/lvtinydom.cpp

Stylesheets included in each DocFragment are parsed individually, even if they point to the same file. Depending on the number of CSS files, their size, and number of DocFragments, CSS parsing accounts for several percentage of a full LVDocView::Render() time, or even more in extreme cases. By introducing a parsing cache, the time spent in LVImportStylesheetParser::Parse is now negligible.
Closes #491.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/493)

CSS: cache parse results

---

crengine/include/epubfmt.h
crengine/include/lvstream.h
crengine/src/chmfmt.cpp
crengine/src/epubfmt.cpp
crengine/src/lvrend.cpp
crengine/src/lvstream.cpp
crengine/src/pdbfmt.cpp

In LVNamedContainer, and so for its subclasses like directories and ZIP archives, maintain and use a name to index table when looking and opening files by name.
- Optimize EpubItems id lookups with a hashtable.
- Avoid using doc-`>nodeFromXPath(..[n])` n times, as it is slow, and just iterate the children nodes instead.
- Also add some comments.
- Optimize metadataOnly handling, and tweak it so we get a single exit point.
(I have not tested all the toc & pagemap types, because I can't easily find the documents that has each type, so I hope I didn't mess any - but the changes are all similar.)
Some big book (3000 items in the zip) I have used over the years for benchmarking (and that I remember took 70 seconds loading at some point in the past), was taking these days 64 seconds. With this …

EPUB loading optimizations, support obfuscated embedded fonts

---

crengine/include/lvstyles.h
crengine/include/lvtinydom.h
crengine/include/textlang.h
crengine/src/lvrend.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvtinydom.cpp
crengine/src/mathml.cpp
crengine/src/textlang.cpp

So frontend can use it (for hyphenating any text) without being affected by the `_embedded_langs_enabled` crengine setting.
Thsi fixes a small issue noticed at https://github.com/koreader/koreader/pull/9630#issuecomment-1314320371:
> One required thing to have it work (a bug I'll solve later): you need to have opened once a CRE document after the start of KOReader, and have "Respect embedded lang tags" enabled.
And, if noticed in the XML loading phase (where boxing elements are inserted in the DOM), force a rerendering so the final rendering is consistent between loading/rendering.
This could have caused hard to understand differences when using style tweaks, ie. with in-page footnotes that target autoBoxing, as they can themselves cause a full reloading of the document.
Also make the …

Styles: check when inheritable CSS set on boxing elements

---

crengine/include/lvhashtable.h
crengine/src/lvtinydom.cpp

Ensure **all** elements of the last bucket are iterated on (not just the first one).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/499)

LVHashTable: fix iterator implementation

---

crengine/src/lvtextfm.cpp

Allocation is done [here](https://github.com/koreader/crengine/blob/master/crengine/src/lvtextfm.cpp#L2120).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/501)

Text: fix mismatched `free` on `new`-allocated memory

---

crengine/src/epubfmt.cpp
crengine/src/lvdocview.cpp

It's only used by the caching, so only calculate it on full document load (i.e. not metadata only).
Resulting speedup during metadata extraction:
- simulator on my laptop (1068 files): ~9% speedup, average ~12 → ~10 ms, minimum 5 → 5 ms, maximum 486 → 319 ms
- on my Kindle Paperwhite (6th generation, 956 files): ×2 speedup: average 225 → 107 ms, minimum 84 → 84 ms, maximum 4862 → 400 ms
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/498)

only calculate a document's CRC32 if needed

---

crengine/include/lvtinydom.h
crengine/include/lvtypes.h
crengine/src/hyphman.cpp
crengine/src/lvdocview.cpp
crengine/src/lvfntman.cpp
crengine/src/lvrend.cpp
crengine/src/lvstream.cpp
crengine/src/lvstring.cpp
crengine/src/lvtinydom.cpp
crengine/src/lvxml.cpp
crengine/src/mathml.cpp
crengine/src/textlang.cpp

Various picks from @virxkane 's https://gitlab.com/coolreader-ng/crengine-ng .
Remove unused variables, fix types, more proper casts.
From crengine-ng commits:
https://gitlab.com/coolreader-ng/crengine-ng/-/commit/259e8e7a9951d74fa81b268c7117c24070d8b7cb
https://gitlab.com/coolreader-ng/crengine-ng/-/commit/a90ac8cc26fd1aefa9a33d11edecd6696578cbd5
https://gitlab.com/coolreader-ng/crengine-ng/-/commit/3ed32dd05d1d26c79ec3cc725e8a04f28e7ad984
https://gitlab.com/coolreader-ng/crengine-ng/-/commit/f9095b8aa773c1bcafa5ec0fb3b0cd4587feadbe
https://gitlab.com/coolreader-ng/crengine-ng/-/commit/64ce6c2a8135841374f0f9338c29b753657a25c6
https://gitlab.com/coolreader-ng/crengine-ng/-/commit/146fdd59a46958cda6a1cbce5e14c8f0a1bee845
https://gitlab.com/coolreader-ng/crengine-ng/-/commit/2791906f7b59b9eb …

Various picks from crengine-ng

---

crengine/src/lvfntman.cpp

Avoid wrong font choice when handling CSS with out default font (which has a bias) specified by name and not first, ie. `font-family: ExistingFont1, BiasedFont2`
See https://github.com/koreader/koreader/issues/10040#issuecomment-1399464738
Should allow closing https://github.com/koreader/koreader/issues/10040.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/505)

LVFontDef::CalcMatch(): don't use the bias if typeface matches

---

crengine/src/lvtinydom.cpp

Zero each node's document index so the cache file content does not change based on the number of previously opened documents.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/506)

Cache: improve cache file reproducibility

---

crengine/include/lvstream.h
crengine/src/chmfmt.cpp
crengine/src/lvstream.cpp

The initial goal of this PR was to avoid unnecessary rewinds of ZIP streams
due to the common pattern of first reading an initial chunk (to detect the
encoding/format) before consuming/parsing the whole stream.
Example when loading an EPUB:
```
LVStreamFragment(“mimetype”)
LVZipDecodeStream(“META-INF/container.xml”)
rewind(META-INF/container.xml)
rewind(META-INF/container.xml)
rewind(META-INF/container.xml)
rewind(META-INF/container.xml)
LVZipDecodeStream(“OEBPS/content.opf”)
rewind(OEBPS/content.opf)
rewind(OEBPS/content.opf)
rewind(OEBPS/content.opf)
rewind(OEBPS/content.opf)
rewind(OEBPS/content.opf)
LVZipDecodeStream(“OEBPS/Styles/style0001.css”)
rewind(OEBPS/Styles/style0001.css)
LVZipDecodeStream(“OEBPS/Styles/style0002.css”)
rewind(OEBPS/Styles/style0002.css) …
```

LVStream: fix and improve `LVZipDecodeStream` implementation

---

crengine/include/lvdocview.h
crengine/include/lvpagesplitter.h
crengine/include/lvtinydom.h
crengine/src/lvdocview.cpp
crengine/src/lvpagesplitter.cpp
crengine/src/lvrend.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvtinydom.cpp

This could be painfully slow if used to highlight any other paragraph in a document made of thousands of such paragraphs (ie. to highlight character names in a dumb theater play EPUB
where all character names and speeches are in a same kind of `<P>`).
Could cause some flags to leak to next elements, and unexpected page splitting and collapsing margin issues.
Should allow closing https://github.com/koreader/koreader/issues/10073. See https://github.com/koreader/koreader/issues/10073#issuecomment-1416036120.
Allows getting the real `doc_rendering_hash`, use `extended=true` to get this hash augmented with
some view-related state.
Only available with EPUBs containing 2 or more fragments, and a file size large enough to ensure a cache file is used.
The idea is simply, on any rendering setting …

Toggleable support for partial rerenderings of individual DocFragments

---

crengine/include/lvstsheet.h
crengine/src/lvstsheet.cpp

Take into account the fact that the selectors are already ordered.
This change improves loading times on a number of my EPUBs (~20 files, including 8 out of the 15 slowest on both Kindle and PC).
Timings (release builds with LTO):
| file                       | master (kindle) | PR (kindle)      | master (laptop) | PR (laptop)      |
| -------------------------  | ------:         |-------:          | ------:         |-------:          |
|  461 (814 KB, ~ 480 pages) | ~27052 ms       | ~18532 ms (-31%) | ~ 3237 ms       | ~ 1550 ms (-52%) |
|  609 (938 KB, ~ 702 pages) | ~26807 ms       | ~23162 ms (-14%) | ~ 2706 ms       | ~ 1926 ms (-29%) |
|  798 (604 KB, ~ 550 pages) | ~14431 ms       | ~12204 ms (-15%) | ~ 1558 ms       | ~ 1044 ms (-33%) |
| 1373 (  1 MB, ~1023 pages) | ~13895 ms …

LVStyleSheet: optimize `LVStyleSheet::merge`

---

cr3gui/data/hyph/German.pattern

This is an update to the German hyphenation patterns (after one year now ;-) ). 
Also added a minor update to the format used by coolreader (seee https://github.com/buggins/coolreader/commit/7925f6b8906d5bf39be2e3f4a6e47133751c6edd).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/510)

Update German hypenation patterns

---

crengine/include/lvdocview.h
crengine/include/lvstsheet.h
crengine/include/lvtinydom.h
crengine/src/lvdocview.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp

Allow getting the in the header the glyphs for the book languages, see https://app.gitter.im/#/room/#koreader_koreader:gitter.im/$pbQZfpmcRQ9kcILx8uWwgnlh7ve6U98x2iAc1M1UI6A
See https://github.com/koreader/crengine/pull/261#issuecomment-1445123070.
As done in 3ff7558e.
Use an additional stream where writeNodeEx can output formatted info about tags met (with offset in the main stream, the tag level, the node dataIndex, and selectors for the classnames and attributes).
For a node, returns all the rulesets (from all stylesheets involved), as text snippets, that the provided node would match.
Can be used by frontends providing View HTML/CSS features to help understanding what CSS bits cause what.
The last 2 commits will allow supporting long-press in the View HTML widget, to get more info …

Add some helpers for "View HTML", other small fixes

---

cr3gui/data/hyph/German.pattern

No real changes here. This is just an update of the version number to dehyph-exptl-v0.9. 
So we are in sync with the upstream repo on https://repo.or.cz/w/wortliste.git
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/512)

Update German hyphenation patterns to V0.9

---

crengine/include/lvdocview.h
crengine/src/lvdocview.cpp
crengine/src/lvtinydom.cpp

Followup to c71001e7 #493, where we already do clear that cache after a re-rendering. We also need to clear it after the initial loading, otherwise these cached stylesheets would be used on the first re-rendering, possible causing media queries changes and font-family font substitutions to have no effect on the first rerendering.
See https://github.com/koreader/crengine/pull/493#issuecomment-1455186966.
Forgotten in cc5147cb3 #467.
See https://github.com/koreader/crengine/pull/467#issuecomment-1462649997.
Follow up to 1bfb7103 #484: also check also check if xpointer is text to avoid other strange issues.
This function is only used in some obscure cr3gui/src/cr3jinke.cpp, but can be useful, so make it behave as the function used to get the current page xpointer.
Will help with …

Various small fixes and tweaks

---

crengine/include/lvxml.h
crengine/src/lvxml.cpp

Some bytes/chars could be lost if, while reading, our buffer would end inside a multibyte character, possibly losing sync and causing garbled data.
See issue and discussion in https://github.com/koreader/koreader/issues/10218.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/515)

LVTextFileBase: fix parsing of variable width encodings

---

crengine/include/lvrend.h
crengine/src/lvdrawbuf.cpp
crengine/src/lvrend.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp

This is used to draw FB2 covers, so they too will get enhanced image handling from frontend (dithering, color...)
See https://github.com/koreader/koreader-base/pull/1484#issuecomment-1507508646 and around.
As per-specs. They were already ignored when sizing tables and cells, but not when rendering the cell content, which could cause unwanted wraps.
Should help inspecting books that use `@import` in their main stylesheet (as in the slow-loading Japanese books provided by @NiLuJe in the past).
Handle cases like these:
`  <p><img src="..." style="float: right"/></p>`
which should have a zero-height.
`  <p><img src="..." style="float: right"/><br/></p>`
which should keep the strut height.
This behaves as Firefox, and should do the proper handling mentionned in be304606d.
Also do the proper …

Various BiDi, <br/>, floats, table cells and FB2 cover related fixes

---

crengine/src/epubfmt.cpp
crengine/src/lvtinydom.cpp

EPUBs may have occasionally buggy NCX entries with invalid targets. Don't ignore them, it's best to get a title and not ignore any subentries, even if tapping on them will lead us nowhere.
`<p></p>` and `<p><span> </span></p>` are handled correctly.  This handles `<p><span></span></p>`, which was resolving to a null xpointer.
See https://github.com/koreader/koreader/pull/10506#issuecomment-1570167960
Should allow closing https://github.com/koreader/koreader/issues/10505
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/518)

MInor NCX ToC and createXPointer(pt) fixes

---

crengine/src/lvtextfm.cpp

```bash
▸ pkg-config --cflags fribidi
-I/usr/include/fribidi
```
Otherwise, using `fribidi/fribidi.h` may result in the wrong (system) include being picked up when building the emulator.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/519)

fix fribidi include

---

crengine/include/hyphman.h
crengine/include/lvhashtable.h
crengine/src/hyphman.cpp
crengine/src/textlang.cpp

Fix issues with calling koreader base' teardown in `cre.cpp`, including the fact that the destructor for `static LVHashTable<lString32, HyphMethod*, true> _loaded_hyph_methods` gets called before it, so trying to iterate on the hashtable to cleanup memory is triggering uses after free.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/520)

fix teardown

---

crengine/include/lvstring.h
crengine/src/lvstring.cpp

Avoid breaking strict aliasing rules (casting `lstring8_chunk_t` to `lstring32_chunk_t` and vice versa). Also simplify the code by getting rid of all the duplicated code thanks to using only one unified `lstring_chunk_t` struct.
See https://github.com/koreader/koreader/issues/10679.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/522)

lvstring: fix clang release build

---

crengine/include/lvstsheet.h
crengine/src/bookformats.cpp
crengine/src/docxfmt.cpp
crengine/src/lvfntman.cpp
crengine/src/lvimg.cpp
crengine/src/lvstsheet.cpp

https://github.com/koreader/koreader/issues/10599#issuecomment-1627678171. Thanks @pkb.
Should allow closing https://github.com/koreader/koreader/issues/10599.
Computations could stop too early (when meeting the ASCII char `cssd_stop`, currently `h`, ie. in a `'url(aha.png)'`), which would have any change after that `h` goes unnoticed.
Noticed at https://github.com/koreader/crengine/issues/514#issuecomment-1616584156.
(We still expect ASCII for element and attribute names.)
Got a French EPUB that has in its CSS (as utf8, shown here read as latin1):
```css
section{
visibility: hidden;
}
section#mentions,
section#prÃ©face,
section#lever-de-rideau-avant-propos,
section#actepremier-en-scÃ¨ne-histoire,
section#remerciements { visibility: visible !important; }
```
which was mostly blank :) …

Minor CSS fixes, add support for .docm

---

cr3gui/data/epub.css
crengine/include/cssdef.h
crengine/include/lvdocview.h
crengine/include/lvstsheet.h
crengine/include/lvstyles.h
crengine/include/lvtinydom.h
crengine/src/lvdocview.cpp
crengine/src/lvimg.cpp
crengine/src/lvrend.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvstyles.cpp
crengine/src/lvtinydom.cpp

Fix embedded base64 images not supported when used by frontends to render a SVG without having a document loaded.
Issue noticed at https://github.com/koreader/koreader/issues/10711#issuecomment-1641562965.
A single nav.xhtml could be in the spine, and host a ToC `<nav>` and a huge page list `<nav hidden="">`, that we should not show as per-specs.
Should allow closing https://github.com/koreader/koreader/issues/10703 (see discussion in there).
Ie. with the following, the cells would overflow the document width:
```html
<table style="width: 100%;">
<tr><td style="width: 4em">abc</td><td>def</td></tr>
</table>
```
Per-specs, a caption computed max width should not be involved in the table width computation (it was not, in the table rendering code, but it was in `getRenderedWidth()`).
On the …

CSS: add support for "caption-side: top/bottom", and other SVG, CSS and table fixes

---

cr3gui/data/epub.css
crengine/include/cssdef.h
crengine/include/fb2def.h
crengine/include/lvdrawbuf.h
crengine/include/lvstyles.h
crengine/src/lvdrawbuf.cpp
crengine/src/lvrend.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp
crengine/src/mathml_css_h.css

As we support SVG better now since #489.
At the start of a paragraph, and after a `<br/>`, don't have the width of leading `nbsp` shrunk or expanded if the line is going to be justified, to ensure alignment of the first word on following similar paragraphs.
See https://github.com/koreader/koreader/issues/7366#issuecomment-1657179477.
See https://github.com/koreader/koreader/issues/10770#issuecomment-1662071876.
Also helps getting nicer `<head><style>` CSS with "View HTML" instead of all of it on a single line.
We used to support '`inherit`' only for properties that are inherited by default; not supporting 'inherit' set by publishers for others could lead to various issues.
Support '`inherit/initial/unset`' on all the properties we support (and make these invalid if not standalone: …

CSS: revamp 'inherit' handling, now fully per CSS specs, and other fixes

---

crengine/src/lvstsheet.cpp

1. isRoot() is not free. Move it up the hierarchy.
2. avoid unnecessary string copy
3. don't allocate new strings when matching class name.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/528)

Optimize LVCssSelectorRule::check()

---

crengine/src/lvtextfm.cpp

Happens with `<p>&#x2060;abc</p>`, this word joiner char, being 0-width, is considered a diacritic and cluster tail.
Noticed by @benoit-pierre at https://github.com/koreader/crengine/pull/511#discussion_r1342174345
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/530)

Text: fix possible underflow/crash

---

crengine/src/lvfntman.cpp

The cache size was not updated when removing the last item.
Potential impact: negligible, between 64 and 316 bytes on each book opening after the first one, resulting in a ~1% reduction in usable cache size after opening 17 books.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/532)

lvfntman: fix `LVFontGlobalGlyphCache::removeNoLock`

---

crengine/src/lvfntman.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/534)

lvfntman: fix harfbuzz related memory leak on quit

---

crengine/include/lvfntman.h
crengine/src/lvdocview.cpp
crengine/src/lvfntman.cpp
crengine/src/lvtinydom.cpp

Main 2 changes:
- ensure a self-referencing font can still possibly be garbage collected.
- check and ensure we don't remove the last reference (from the font manager internal list of instances / registrations) to a font with a reference count >1 (leak).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/536)

fix fonts leaks

---

crengine/src/lvtinydom.cpp

Between 128 and ~2M when doing a full load on 23 (out of ~1K) of the files I tested.
Examples:
- [epub30-spec.epub](https://github.com/IDPF/epub3-samples/releases/download/20170606/epub30-spec.epub): 17152 byte(s) leaked in 402 allocation(s).
- [hefty-water.epub](https://github.com/IDPF/epub3-samples/releases/download/20170606/hefty-water.epub): 2048 byte(s) leaked in 48 allocation(s).
- [kusamakura-japanese-vertical-writing.epub](https://github.com/IDPF/epub3-samples/releases/download/20170606/kusamakura-japanese-vertical-writing.epub): 2356736 byte(s) leaked in 55236 allocation(s).
- [kusamakura-preview-embedded.epub](https://github.com/IDPF/epub3-samples/releases/download/20170606/kusamakura-preview-embedded.epub): 2356736 byte(s) leaked in 55236 allocation(s).
- …

lvtinydom: fix memory leaks

---

crengine/src/lvxml.cpp

There are more than necessary comparions made on every char. By
1. do a quick check before proceeding to more complicated paths
2. use pointers instead of indices
we see ~50% fewer time spent in the function.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/526)

Speedup PreProcessXmlString()

---

crengine/include/lvtinydom.h
crengine/src/lvtinydom.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/540)

lvtinydom: minor cleanups / simplifications

---

thirdparty/antiword/CMakeLists.txt
thirdparty/chmlib/CMakeLists.txt

Hide everything since antiword and chmlib are compiled and linked statically and none of their symbols are exported by the main library.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/544)

set thirdparty libraries symbol visibility

---

crengine/include/lvstring.h
crengine/src/lvstring.cpp

The chunk `size` is the allocated size minus one (the terminating `\0`). Fix methods that don't have the same definition.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/538)

lvstring: fix size handling

---

crengine/include/lvdocview.h
crengine/include/lvimg.h
crengine/src/lvdocview.cpp

Will allow https://github.com/koreader/koreader-base/pull/1675.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/542)

lvdocview: remove (unused) `crskin` and `wolutil` related code

---

crengine/include/lvstring.h
crengine/src/lvrend.cpp
crengine/src/lvtinydom.cpp
crengine/src/mathml.cpp

The extra `value_type & operator []` accessors would get picked-up over the normal readonly one: `value_type operator []`, resulting in unnecessary calls to `modify()` (triggering an allocation+copy if the reference count is not 1). Get rid of the former, and fix `lastChar` and `firstChar` method to also be read-only. Additionally, avoid using the `at()` method (prefer an explicit `modify()[…]` when needed), and remove it.
Note: depends on https://github.com/koreader/koreader-base/pull/1675.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/543)

no unnecessary string modifications

---

crengine/include/crtxtenc.h
crengine/include/lvxml.h
crengine/src/crtxtenc.cpp
crengine/src/lvxml.cpp
crengine/src/pdbfmt.cpp

This is a series of commits superseding https://github.com/koreader/crengine/pull/497
Current implementation works as follows:
1. run `AutodetectEncoding()`. It detects BOM, runs heuristics on 128K bytes if not found.
2. use the previous result to convert input bytes to char32_t
3. scan for tags. if it's (x)html then look further for encoding information. If charset/encoding is found in html, it prevails.
The problem with this approach is:
- slow
- if the heuristics used in step2 is wrong, step 3 is likely to fail.
The new implementation is (very) loosely based on the HTML standard.
Tests:
- I tested on some mid-sized epubs from Project Gutenburg, and `LoadDocument()` consumes (median) ~11% less cycles as reported by callgrind.
- I haven't tested other formats nor malformed inputs, due to …

Optimize `LVHTMLParser::CheckFormat()`

---

crengine/include/lvstring.h
crengine/include/lvstsheet.h
crengine/src/lvstring.cpp
crengine/src/lvstsheet.cpp

This is my first PR on https://github.com/koreader/crengine/issues/529
I've tested with load and render, but I've no knowledge of cache mechanism yet so not sure it works there. I publish them  for review now because I want to avoid conflicts to subsequent commit(s) :)
Tested with two sets of books from Project Gutenburg, and cycle estimations of `LoadDocument()` reported by callgrind are as follows (fewer is better):
| Percentile | Largest Books | Median Books |
| --|--|--|
| Best 10% | -39.2% | -11.3% |
| Median | -6.0% | -3.3% |
| Worst 10% | -1.6% | -0.2% |
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/545)

Improve css class matching

---

cr3gui/data/fb2.css

Some FB2 books incorrectly use <p /> tags to add an empty new lines. Ideally, they should use <empty-line /> instead, but oh well.
KOReader doesn't display any empty vertical space, so there's no break at all.
I've tested this change on my own device, and it worked.
<details>
<summary>See the images for comparison.</summary>
</details>
Closes koreader/koreader#11173.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/547)

Use empty paragraphs to insert a new line

---

crengine/src/lvtextfm.cpp

Actually, all inline boxes on the last line of a justified paragraph.
Follow up to c7c6bef9, where I didn't think about light formatting and not all lines going thru alignLine() on the initial opening of a book: these wrong positions would be saved in the cache, and never corrected.
See https://github.com/koreader/koreader/issues/11021#issuecomment-1771537372
~~I'm not super confident with this though: modifying stuff fetched from the cache (we never do that), and not explictely updating an existing cache (we also never do that, when this is needed, we fully reload and rebuild the DOM+cache).~~
~~All the cache memory <=> disk handling/flushing/trashing is still pretty obscure to me, and I'm not sure if implicit cache update can happen (and what happens when it happens :). There is [code …

CJK: fix bad ruby drawing on last paragraph line

---

cr3gui/data/hyph/German.pattern

Well, I was lazy. The last update was 9 months ago. ;)
Maybe this PR will find its way into 2023.12?
Happy new year and a peaceful Christmas for all!!!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/549)

Uplift German hyphenation patterns

---

crengine/src/lvstsheet.cpp

Followup fix to #545 55fa1043: if there's not a single '* {}' or '.cls {}' in a stylesheet, none of it would have been matched and applied.
See https://github.com/koreader/koreader/issues/11235#issuecomment-1859090477
Should allow closing https://github.com/koreader/koreader/issues/11235.
Pinging @bbshelper for a quick review before merging later today.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/550)

LVStyleSheet: fix stylesheet possibly not applied

---

crengine/include/lvdocview.h
crengine/include/lvpagesplitter.h
crengine/include/lvtinydom.h
crengine/include/props.h
crengine/src/lvdocview.cpp
crengine/src/lvpagesplitter.cpp
crengine/src/lvrend.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp
crengine/src/props.cpp

Frontend can set custom title/authors/series to be displayed in the top status bar (and in the rarely seen FB2 synthesized front text cover).
Will help https://github.com/koreader/koreader/pull/11463 to do it stuff more properly. See https://github.com/koreader/koreader/pull/11463#issuecomment-1939067151
A float at the end of the document could add some overflow to the root node "rect", and we would segfault when looking for its parent.
See https://github.com/koreader/koreader/issues/11409#issuecomment-1913089844 .
Should allow closing https://github.com/koreader/koreader/issues/11409 .
Followup to 03e0f372, where we added the closing of a non-linear sequence for erm_block elements, but totally forgot to do the same for erm_final elements!
Noticed around …

Various text selection, footnotes & misc fixes and tweaks

---

.github/workflows/build.yml
.stylelintignore
.stylelintrc.json
cr3gui/data/fb2.css

In reply to https://github.com/koreader/crengine/pull/555#issuecomment-1970053271
This is an initial poc. Some of the rules like `length-zero-no-unit` definitely make sense to me, but the existing code is full of things like `0px` and I dislike changing things for the sake of changing them.
For `-cr-etc` I think we should be able to define a `custom-property-pattern` (as a regex).
For `selector-type-no-unknown` we should do something like `"ignoreTypes": ["genre", "author", "etc"]`. Disabling it completely would probably defeat the purpose.
And so on.
I don't know if I'll continue on this tonight, but this way the (rather excessive) list of complaints is already available to see.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

[CI] Add stylelint to prevent typos in CSS

---

crengine/include/cssdef.h
crengine/include/epubfmt.h
crengine/include/lvdrawbuf.h
crengine/src/epubfmt.cpp
crengine/src/lvdocview.cpp
crengine/src/lvpagesplitter.cpp
crengine/src/lvrend.cpp
crengine/src/lvtinydom.cpp

This hint was initially added to prevent footnote popups by frontend, and is rarely useful and used. Have it also prevent in-page footnotes from being added to the pages of links with that hint.
Already documented at https://github.com/koreader/koreader/blob/67cd647d1a6a36c95d512b1ee461b7a7faf484c4/frontend/apps/reader/modules/readerstyletweak.lua#L882-L885 :
> Can be set on links (`<a href='#..'>`) to have them NOT trigger footnote popups and in-page footnote.
If some DocFragment presents an index of names with cross references, resulting in in-page footnotes taking half of these pages, you can avoid this with:
`DocFragment[id$=_16] a { -cr-hint: noteref-ignore }`
When footnotes are pushed on a next page, make sure this page ends up in the same "flow": if the next content is part of …

Various in-page footnotes, tables and covers fixes and tweaks

---

crengine/src/textlang.cpp

Russian typography frowns upon having one letter prepositions and conjunctions hanging at the end of the line.
There are many Russian resources discussing this, I've linked some of the better known ones:
https://www.artlebedev.ru/kovodstvo/sections/62/
https://gramota.ru/spravka/vopros/294020
https://gramota.ru/spravka/vopros/219773
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/557)

Add typography rules for Russian

---

cr3gui/data/hyph/Russian.pattern
cr3gui/data/hyph/Russian_EnGB.pattern
cr3gui/data/hyph/Russian_EnUS.pattern

I'm not sure why it was prohibited before. Looking at [the modern Russian hyphenation rules](https://gramota.ru/biblioteka/spravochniki/pravila-russkoj-orfografii-i-punktuacii/pravila-perenosov), it's perfectly allowed, even recommended to add hyphens after prefixes.
I've tested on my device, and it looks better with this change. You can see how the word spacing has improved:
| Before | After |
|--------|--------|
| <img src="https://github.com/koreader/crengine/assets/483357/520dc84c-2af7-4711-a56a-0f6784c9e8a2" width="400"> | <img src="https://github.com/koreader/crengine/assets/483357/2fe310db-d7d7-4762-9759-9cf35c66caf1" width="400"> |
| <img src="https://github.com/koreader/crengine/assets/483357/78edece2-c3a3-4564-8457-76c27d0bb1df" width="400"> | <img …

Allow hyphens after Russian "не" prefix

---

crengine/include/lvdocview.h
crengine/include/lvtinydom.h
crengine/src/epubfmt.cpp

I wanted to write a plugin to automatically sync my progress from KOReader to hardcover.app and need the ISBN of the book for that to ensure proper matching.  
This will add the identifiers as `doc_prop` in the format of `scheme:identifier` separated by `;` e.g. `isbn:9783462312317;asin:b0ckwvvv4z`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/560)

EPUB: add identifiers to doc props

---

cr3gui/data/fb2.css
crengine/src/epubfmt.cpp
crengine/src/lvrend.cpp
crengine/src/lvtinydom.cpp

Assertions in `LVFontCache::_removeDocumentFonts()` would fail (when DEBUG enabled).
Noticed and investigated at https://github.com/koreader/crengine/pull/536#issuecomment-2002142872.
Followup to 1544bcfb, where we made an image self container's width adjust to the image width, so `text-align:center` no longer does what was expected.  Switch to `margin-left/right:auto` to get them centered again. See https://github.com/koreader/koreader/issues/11623#issuecomment-2040436412.
Also, for standalone block images, set the strut and line-height to 0 (as we do for HTML) so they their block is adjusted to the page height when the image itself exceeds it, to avoid such images to be truncated and sliced on two pages. Noticed and investigated in https://github.com/koreader/crengine/pull/562.
Should …

Fix FB2 image sizing & centering, and bottom border on empty block elements

---

cr3gui/data/html5.css
crengine/include/lvdocview.h
crengine/include/lvpagesplitter.h
crengine/src/lvdocview.cpp
crengine/src/lvpagesplitter.cpp
crengine/src/lvrend.cpp

Should allow closing https://github.com/koreader/koreader/issues/11771.
Coding error: images with width=0 in tables/floats would cause an infinite loop and a stack overflow.
Should allow closing https://github.com/koreader/koreader/issues/11680
If a non-linear flow was created, but we never got any "line" associated to it, just ignore it and reset the counter.
(Otherwise, frontend would get holes/nil in the array of flows, and would get confused.)
Fix issue noticed at https://github.com/koreader/koreader/issues/8623#issuecomment-2068168592.
So frontend can build this bit of text and propagate it to crengine for it to display in place of its own computed text.
Will allow KOReader (via ReaderCoptListener) to display something similar to what it displays in the footer (which is different …

Fix ruby alignment, fix one possible crash, ignore empty non-linear flows

---

cr3gui/data/hyph/Russian.pattern
cr3gui/data/hyph/Russian_EnGB.pattern
cr3gui/data/hyph/Russian_EnUS.pattern

As @Abradoks correctly mentioned, this rule existed for a reason:
> This is a common sense typographical rule. "Не" is a negative prefix or particle, so separating it makes the text easy to be misread:
> 
> > Недопустимы неблагозвучные переносы, а также переносы, ведущие к двусмысленному прочтению текста, способные запутать читателя, привести к недоразумениям, нарушить нормальный процесс чтения. Например, нельзя отделять отрицание «не» от следующего слова или переносить конечный слог «не» какого-либо слова в другую строку, если далее следует глагол
> > https://print-standart.ru/printing-reference/174-technical-rules-of-typing
> > https://www.nrap.ru/pub10_90_1_1054.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Revert #561

---

cr3gui/data/hyph/Serbian.pattern

This pull request continues on the pull request #372.
As Serbian language uses two scripts with different codepoints, it is safe to combine the patterns into one file. In that way, it doesn't matter which script is used, and even texts that use both scripts will be properly hyphenated. Only the main part of the language tag in (X)HTML should be consulted to load the appropriate patterns. So sr, sr-Cyrl, sr-Latn, and regional versions of these (like sr_RS) should all load the same pattern file.
This approach is already successfully implemented in ConTeXt.
Patterns have been converted from https://devbase.net/dict-sr/ same ones used in LibreOffice extension Serbian Spellchecker.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Combine hyphenation patterns for Serbian Cyrillic and Latin scripts

---

crengine/include/lvdocview.h
crengine/src/lvdocview.cpp
crengine/src/lvtinydom.cpp

Make them single line in the "extra stream" output giving position of nodes in the main stream, used for handling long-press in the HTML Viewer.
See https://github.com/koreader/koreader/issues/12004#issuecomment-2156748523.
This helper function makes use of our (nearly) conforming HTML parser (#370), which handles unbalanced HTML and builds a proper DOM, and returns the serialized DOM, so balanced.
This is currently not used by crengine nor frontend, but it's available for use in HTML dict funcs where giving balanced HTML to MuPDF can give better rendering.
I added that to see if it helped with https://github.com/koreader/koreader-base/pull/1586#issuecomment-2143459278.
and used it like this:
```lua
return function(html)
html = "<html><body>"..html.."</body></html>"
html = …
```

Fix writeNodeEx(), add getBalancedHTML()

---

crengine/src/lvxml.cpp

This part of code are not very testable, so I submit these small commits which I find easier to verify by eyes. Basically I removed unnecessary checks in the inner loop. 
In my test on mid-size Project Gutenberg epubs, these commits can save ~2% total load & render time.
| pct |  chg%|  epub  |
|----:|-----:|-------:|
| best| -3.13|  pg1204|
| 25th| -2.66|  pg6884|
| 50th| -2.40| pg50816|
| 75th| -2.11| pg61089|
|worst| -1.17| pg31015|
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/567)

LVXMLParser::ReadText() Optimizations

---

crengine/include/lvstream.h
crengine/src/epubfmt.cpp
crengine/src/lvfntman.cpp

Handle obfuscated font files smaller than 1040 bytes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/572)

EPUB: fix possible buffer overflow

---

.ci/script.sh

Fix issues in shell scripts picked up by base `.ci/lint_script.sh` when running it locally with the crengine submodule checked out.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/576)

lint: shell scripts

---

crengine/include/lvdocview.h
crengine/include/lvdocviewprops.h
crengine/src/lvdocview.cpp

I enjoy using KOReader, and I especially like using the alt status bar, but the author and title switching every page was distracting on my Kindle PW2's e-ink display. The functionality seemed to be mostly in place already, but wasn't entirely exposed. I have made an implementation of the feature in KOReader and plan to make a pull request to that repo as well, if this pull request gets merged. I have tested the feature in the emulator and it appears to be working properly, but a second opinion would be much appreciated.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/575)

lvdocview: fix and expose functionality for displaying author and book title separately in the status bar

---

crengine/src/lvfntman.cpp

When checking "font-family: SomeFont, serif" and requesting italic or bold, the serif font could win even if SomeFont is present, if SomeFont has no real italic of bold variant, but the serif font has them.
So, stop iterating the provided names list early when a typeface matches.
Noticed at https://github.com/koreader/crengine/pull/572#issuecomment-2195504556, see followup posts.
When using Harfbuzz, if we would meet max_width (32767px) while measuring text with a fallback font, we would return a too large lastFitChar, and invalid measurements for the chars between the real lastFitChar and the one returned, possibly resulting in chars overlapping previous ones and garbled text rendering.
See https://github.com/koreader/koreader/issues/12183#issuecomment-2240950279.
Should allow closing …

Fonts: fix font scoring and Harfbuzz measurements

---

crengine/src/textlang.cpp

Many Russian texts are using quotes from Word (“”), so this rule leads to incorrect line breaks. It also isn't correct for Russian_En-US and Russian_En-GB variants, because English words are using these quotes extensively.
See the following screenshot, I've marked the hanging curly quote with red color. It should stay together on the next line with the word "_маркий_", but it's left hanging on the previous line instead.
@hius07, what do you think?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/577)

Don't break lines on curly quotes in Russian

---

crengine/include/crlocks.h
utils/lint.mk

- it's already stubbed anyway, stub it more!
- I have seen at least one crash with the default stub (clang emulator)
- cppcheck is not happy about it
NOTE: this need a corresponding change in base:
```diff
--- i/thirdparty/kpvcrlib/CMakeLists.txt
+++ w/thirdparty/kpvcrlib/CMakeLists.txt
@@ -30,7 +30,6 @@ add_library(crengine STATIC
${CRE_DIR}/qimagescale/qimagescale.cpp
${CRE_DIR}/src/chmfmt.cpp
${CRE_DIR}/src/cp_stats.cpp
-    ${CRE_DIR}/src/crconcurrent.cpp
${CRE_DIR}/src/cri18n.cpp
${CRE_DIR}/src/crtxtenc.cpp
${CRE_DIR}/src/docxfmt.cpp
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/585)

comment out / don't compile concurrency code

---

crengine/include/lvrefcache.h

To make cppcheck happy (parsing error).
This prevented cppcheck from properly checking a lot of files (23 out of 38).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/586)

lvrefcache: tweak `LVCacheMap` implementation

---

crengine/include/lvref.h
crengine/src/crtxtenc.cpp
crengine/src/lvstring.cpp
crengine/src/lvtinydom.cpp
crengine/src/lvxml.cpp
crengine/src/pdbfmt.cpp

Most of them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/587)

lint: fix cppcheck lint errors

---

.github/workflows/build.yml
utils/lint.mk

- this generate a lot of warnings with clang-tidy & cppcheck in nanosvg & stb headers
- it does not match our default configuration on koreader anyway (where lunasvg is used)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/588)

ci: stop linting with nanosvg support enabled

---

crengine/src/textlang.cpp

Simplify the code and make cppcheck happy.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/589)

textlang: get rid of `LANG_STARTS_WITH(…)` macro hack

---

crengine/src/lvrend.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/590)

lvrend: fix compiler / cppcheck warning (maybe-uninitialized)

---

crengine/include/lvptrvec.h
crengine/qimagescale/qimagescale.cpp
crengine/src/cri18n.cpp
crengine/src/epubfmt.cpp
crengine/src/hist.cpp
crengine/src/lvdocview.cpp
crengine/src/lvfntman.cpp
crengine/src/lvstream.cpp
crengine/src/lvstring.cpp
crengine/src/lvstsheet.cpp
crengine/src/odtfmt.cpp

Rehash of #579, only the uncontroversial stuff, with amended commit messages.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/592)

fix a bunch of `-Wall` warnings

---

crengine/src/docxfmt.cpp
crengine/src/hyphman.cpp
crengine/src/lvstsheet.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp
crengine/src/mathml.cpp

Rehash of #579, only the uncontroversial stuff, with amended commit messages. Second batch.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/593)

fix a bunch of `-Wall` warnings, part 2

---

crengine/include/lvtinydom.h
crengine/src/lvtinydom.cpp

With the `int maxLen` private field of `ldomTextCollector` removed, the `int maxTextLen` arguments to `ldomTextCollector(…)` and to `ldomXRange::getRangeText` can also be removed.
Note: calls to `getRangeText` in `cre.cpp` will need to be updated.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/597)

lvtinydom: fix compiler warning [-Wunused-private-field]

---

crengine/src/lvfntman.cpp

Additionally:
- don't look at `_fileName` (possibly set from a previous call) when loading from buffer
- better error handling: `Clear` on error (and before loading a new font)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/598)

lvfntman: factorize `LVFreeTypeFace::loadFromBuffer|loadFromFile`

---

crengine/src/lvtinydom.cpp
crengine/src/lvxml.cpp

- in 40082dcf, limit was not applied
- in 9d70a2e5,
- loop should terminate if a qualified newline is encountered
- `last_split_txtlen` should take the space/newline into account
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/584)

xml parser: fix regressions

---

crengine/src/lvfntman.cpp

Some of the fields of `FT_Outline` changed type:
https://github.com/freetype/freetype/commit/2a7bb4596f566a34fd53932af0ef53b956459d25
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/601)

lvfntman: tweak code to be forward compatible with freetype 2.13.3

---

crengine/src/lvxml.cpp

Wrongly calculated `limit` could be smaller than `ptr`, causing infinite loop.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/602)

xml parser: fix a regression in 40082dcf/b3874805

---

crengine/src/lvdocview.cpp

If FB2 cover is narrower than the reader screen width but wider than 75% of it (100 % / 6 * 8 math in the code), then the cover will be stretched to occupy 100% of the width. The same applies to height. This results in distorted cover images.
I went down the memory lane, and in 2012 the threshold for ratio change was 7 / 8 in https://github.com/koreader/crengine/commit/7734722fb92556ed23cad57b5d221c1614b36fc5 and in 2010 9 / 10 in https://github.com/koreader/crengine/commit/cad44764cdaf100da965d1feeb302970fdedf83d. I'm not sure why CoolReader's creator added this logic originally in https://github.com/koreader/crengine/commit/fb5a4beca0cf94537e32cdfc785d60e44e7493bc, though.
I suggest removing it, so the cover aspect ratio will be preserved, the same way we do for ePubs and other file …

Preserve FB2 cover aspect ratio

---

crengine/include/bookformats.h
crengine/src/lvdocview.cpp
crengine/src/mdfmt.cpp
crengine/src/mdfmt.h

Only the md4c code path.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/606)

cherry pick markdown support from crengine-ng

---

crengine/src/lvdocview.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/609)

lvdocview: fix `getDocFormatName` implementation

---

crengine/include/lvdrawbuf.h
crengine/src/lvdocview.cpp
crengine/src/lvdrawbuf.cpp

Use `LVDrawBuf::Draw` (which already handles scaling) instead of the buggier `LVDrawBuf::DrawRescaled`.
Additionally, don't compile unused `lvdrawbuf` code. Example code size reduction for release builds:
- `android-arm64`: -15.1 KB
- `emu-x86_64`: -19.4 KB
- `kindlepw2`: -10.9 KB
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/611)

fix FB2 covers in grayscale mode

---

.stylelintrc.json

With latest styleint (16.13.1):
```
[…]/cr3gui/data/html5.css:185:15: Unexpected unknown value "-cr-html-align-center" for property "text-align" (declaration-property-value-no-unknown) [error]
[…]/cr3gui/data/html5.css:189:15: Unexpected unknown value "-cr-html-align-left" for property "text-align" (declaration-property-value-no-unknown) [error]
[…]/cr3gui/data/html5.css:193:15: Unexpected unknown value "-cr-html-align-right" for property "text-align" (declaration-property-value-no-unknown) [error]
[…]/cr3gui/data/html5.css:197:15: Unexpected unknown value "-cr-html-align-center" for property "text-align" (declaration-property-value-no-unknown) [error]
[…]/cr3gui/data/html5.css:495:17: Unexpected unknown value "-cr-special" for property "padding-left" …
```

ci: fix `stylelint` check

---

crengine/src/lvdocview.cpp

`getCurrentPageLinks()` may miss links on the first line of a page if the paragraph it is from has some vertical padding.
See https://github.com/koreader/koreader/issues/13130#issuecomment-2614314934.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/616)

getPageDocumentRange(): fix vertical padding not accounted

---

crengine/include/lvstring.h

Small bugfix for `lString32Collection`
Accidentally found this bug while working on footnote improvements. This was copying the pointers directly instead of doing the correct refcount adjustments.
Didn't end up needing it in #618 but might save someone some debugging time when writing
lString32Collection strings;
strings = other_collection;
and wondering about a double free.
Also delete the assignment operator for `lString32HashedCollection`. This is also broken. I didn't feel like implementing it here but this way you'd at least get a compiler error instead of a crash when trying to use it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/619)

fix: rule of three for string collections

---

crengine/include/cssdef.h
crengine/include/lvpagesplitter.h
crengine/src/lvpagesplitter.cpp
crengine/src/lvrend.cpp
crengine/src/lvstsheet.cpp

As promised (threatened?) in #617, this adds support for in-page footnotes that span more than one node.
This adds a hint-based way to allow marking nodes that continue an in-page footnote that starts in a previous node. This is necessary to make in-page footnotes usable in many books with footnotes like this:
```
<p class="footnote" id="f1">footnote 1 starts here</p>
<p>footnote 1 continues here</p>
<p class="footnote" id="f2">footnote 2 starts here</p>
```
(one could of course argue that the publisher did a poor job)
This introduces a new hint to mark such footnotes, as well as a way to target this hint more accurately. These are split across two commits that work independently.
If there is a node with `-cr-hint: footnote-inpage` immediately followed by a node with `-cr-hint: …

Add hint-based footnote extension

---

crengine/src/lvfntman.cpp

Handle `@font-face {src:  url("../Fonts/%2A%2A%3..."}` in publishers' stylesheets.
See https://github.com/koreader/koreader/issues/14056#issuecomment-3112798934.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/625)

RegisterDocumentFont: handle %-encoded urls

---

.github/workflows/build.yml
.stylelintrc.json
utils/lint.mk

- update configuration: ignore deprecation warnings about `page-break-xxx` properties
- switch to the `@csstools/stylelint-formatter-github` formatter, since the builtin one is deprecated
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/627)

ci: fix stylelint linting
