koreader/crengine

crengine/include/lvfntman.h
crengine/src/lvfntman.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp

1. will not create font in font selection menu when opened a book define font with "local" 
2. fix first italic Chinese character in a line clashes with second one.
3. fix crash on toggle floating punctuation or other unpredictable circumstances

several fixes

---

crengine/src/lvtextfm.cpp

1. fix this https://github.com/koreader/koreader/issues/1566
2. Chinese floating punctuation.

fix russian '?' at line end and improve Chinese floating punctuation

---

cr3gui/data/epub.css
crengine/src/lvrend.cpp

images dont need border
images inside \<sub> \<sup> \<a> \<p> should be inline

format tweak

---

crengine/src/lvimg.cpp

1.Better support for interlaced PNGs. CRE used to handle interlaced by
itself, which is not recommended by LibPNG and caused ugly results.
2.will not give up reading PNG file on warnings, which is pretty common
reason for not showing a png. For example, "iCCP: known incorrect sRGB
profile" warning could happen in PNGs generated by GIMP, and CRE used to
ignore these images.
example:
Interlaced PNG

Fix PNG decoding

---

crengine/src/lvrend.cpp

small changes to table rendering

table rendering

---

cr3gui/data/hyph/languages.json

This should fix koreader/koreader#1937.

add None and Algorithm hyphenation options

---

crengine/include/lvtextfm.h
crengine/src/lvtextfm.cpp

Allow negative x positions for hanging indent and y because why not

---

crengine/src/lvrend.cpp

should fix koreader/koreader#2070

fix #2070 lost text alignment

---

crengine/src/lvtinydom.cpp

Preliminary code for discussion.
Decided to have a go at the em-dash selection problem, and found out a single place where stuff could be solved.
crengine was using only the space character to delimit words (finding start or end of word when onHold or next/prev word when onHoldPan), via this function IsUnicodeSpace(ch), which is used numerous times in the functions folowing the one i modified.
I thought I would have to add a new function IsWordSeparator(ch), and decide which IsUnicodeSpace() calls to replace with this new one, but I first tried to just replace them all by just adding my changes to IsUnicodeSpace()... and the result is quite smooth, with no strange things seen over a few days (tested only on the emulator thus).
With this, word selection stops at space and punctuations, and …

More accurate word detection and text selection

---

crengine/src/lvtinydom.cpp

see discussion [#3187](https://github.com/koreader/koreader/issues/3187) [#3192](https://github.com/koreader/koreader/issues/3192)

fix #3187 and #3192 introduced in previous patch

---

crengine/src/lvdocview.cpp

See https://github.com/koreader/koreader/pull/3353#issuecomment-336554217
(no need for bumps, this will go in with the next valuable commit)

Fix yellow bgcolor on first launch

---

crengine/src/lvstsheet.cpp

@poire-z I don't quite know what to make of this.

[fix] Ubuntu 17.10 bad memory address segfault

---

crengine/src/lvdocview.cpp

See https://github.com/koreader/crengine/pull/89#issuecomment-338505286

Fix blue font color on first launch

---

crengine/src/pdbfmt.cpp

mobi file shows images in wrong order

fix mobi images order

---

crengine/src/epubfmt.cpp

Returns them as a single doc_props string with values separated by `\n`.
(multiple dc:subject were already supported and concatenated with `; `, but let's use a generic `\n` for any multiple occurence tags - the lua side of koreader can adapt them if a more appropriate displays is needed.)
See https://github.com/koreader/koreader/issues/3583

(epub) supports multiple <dc:creator> (authors) and <dc:subject> (keywords)

---

crengine/src/lvdocview.cpp
crengine/src/lvfntman.cpp
crengine/src/lvrend.cpp

References
https://github.com/koreader/koreader-base/pull/600
https://github.com/koreader/koreader/pull/3676
https://github.com/koreader/koreader/issues/2686

[fix] more font sizes

---

crengine/src/lvtinydom.cpp

Add what I did to the 1st constructor (30 lines above this one) to the 2nd constructor (which seems never used - for consistency only).

Use factor also in the other tinyNodeCollection constructor

---

crengine/src/lvtinydom.cpp

One Element node could be confused with another Text node.
It could cause the various functions related to finding a xpointer coordinates in the rendered document (that use `ldomXPointer::getRect()`) to find the wrong node and so the wrong coordinates.
`getRect()` first finds the rendered final block, and then iterates thru all its children text nodes to find the given xpointer. It could then stop on the wrong element node and return invalid coordinates.
Text nodes and Elements nodes use a different incremented counter for their index, and this bug could happen when we had them walking near each other when processing text and elements in some paragraph of the document (that's why it wasn't related in anything to the HTML tags or CSS styles, it was just chance, some coincidence in internal …

Fix ldomNode::getChildIndex() that could find wrong child

---

crengine/include/lvdocview.h
crengine/src/lvdocview.cpp

I don't think anyone or anything uses this, but it reduces the delta between our fork and other forks. I think it'll be easier in small increments. Also it's by @houqp so it must be good. ;-)

Upstream lvdocview::propApply()

---

crengine/src/hyphman.cpp
crengine/src/lvimg.cpp
crengine/src/lvmemman.cpp
crengine/src/lvtinydom.cpp
crengine/src/txtselector.cpp
crengine/src/wordfmt.cpp

@poire-z I had noticed these compiler warnings but it feels like a bit of a fake fix, doesn't it. :-P

Upstream fix unused argument warnings

---

crengine/src/pdbfmt.cpp

See https://github.com/koreader/crengine/issues/106#issuecomment-372062488
As done in https://github.com/koreader/crengine/pull/114/files#diff-177cf4caa03bed6297a8bd322d30fdd3

Fix last cppcheck warnings

---

crengine/src/lvtinydom.cpp

Quick and simple solution to https://github.com/koreader/koreader/issues/3746:
One can rename manually (outside of koreader) files in cache/cr3cache, and add `.keep` to the cache filename he wants to keep and never see deleted by crengine.
```
drwxr-xr-x 3      4096 Mar 22 07:45 ..
-rw-r--r-- 1  16434176 Mar 22 09:43 Bible_TOB_20-_fixed2.epub.9ee17c82.1.cr3.keep
-rw-r--r-- 1    192512 Mar 22 09:52 Soliman_le_M-big2018.epub.d1465b5c.1.cr3
-rw-r--r-- 1   2355200 Mar 22 11:40 aaadireito_p-_11.1.4.epub.ba73fd5b.1.cr3
-rw-r--r-- 1   2455552 Mar 22 11:40 Direito_Admi-_-_2017.epub.762d8a79.1.cr3
-rw-r--r-- 1   3857408 Mar 22 11:41 breviarium2018-01.epub.652c6069.1.cr3
-rw-r--r-- 1    624640 Mar 22 11:41 The_Strange_-_Murray.epub.5b2321a7.1.cr3
-rw-r--r-- 1       326 Mar 22 11:41 cr3cache.inx …
```

Use cache files renamed as .cr3.keep

---

crengine/include/lvrefcache.h

When loading a document, in very rare circumstances, ldomNode::initNodeStyle() would end up with a NULL
style (it shouldn't), that would later cause a segfault in ldomNode::initNodeFont() where that style is accessed.
A segfault happens (and happens too with a 3 months old crengine) with this epub [Leonard de Vinci.FR.epub.zip](https://github.com/koreader/crengine/files/1889729/Leonard.de.Vinci.FR.epub.zip).
It's a Wikipedia article saved as EPUB with no image.
If you just change in koreader `data/epub.css`:
`b, strong { font-weight: bold; }`
to
`b, strong { font-weight: normal; }` or `b, strong { font-weight: bolder; }`
it does not happen!
If you remove or rename to `<zzz>` 1 of the 3 `<b>stuff</b>` in the content.html, it does not happen!
If you save it again as EPUB, with images (all, …

Fix possible segfault with LVIndexedRefCache.cache()

---

crengine/src/hyphman.cpp
crengine/src/lvtinydom.cpp

https://github.com/koreader/koreader/issues/3848#issuecomment-380863368 (for context)

Increase hyphenation max pattern size from 9 to 16

---

cr3gui/data/hyph/French.pattern

see a bunch of https://github.com/koreader/koreader/issues/3848 for context

updating french.pattern

---

crengine/include/lvstyles.h
crengine/src/lvstsheet.cpp
crengine/src/lvstyles.cpp

As described in https://github.com/koreader/koreader/issues/1430#issuecomment-385014559
Simple rules:
CSS are applied (to each node) mostly in the order they appear in the (concatenated) stylesheets, inline styles last.
When meeting a property with` !important`: set it to node's style, and set a flag this property is important
When meeting a property without `!important`: check first if an important flag has previously been set to this node property, and if yes, ignore it. If no, set it and override any previous value.
Our external css don't have any `!important`, so it shouldn't hurt. This may just start supporting (badly or rightly, time will tell:) any `!important` in publishers css.
Tested with various manipulations to:
```html
<html xmlns="http://www.w3.org/1999/xhtml">
<head> …
```

Stylesheets: adds support for !important

---

cr3gui/data/hyph/French.pattern
cr3gui/data/hyph/German.pattern

French : added rules for désir and removed duplicate rule for aujourd, removed cul5 which conflict in some cases.
German : corrected problem with encoding

Update fr & de patterns

---

crengine/src/hist.cpp

Taken from https://github.com/buggins/coolreader/pull/14/commits/e54d409c1d8625679a1732395069388363f2da9b

Fix potential segfault

---

crengine/include/lvtinydom.h
crengine/src/lvtinydom.cpp

They share much of the same code, that we can add a default parameter to `getRect(rect, extended=false)` to get one behaviour or the other.
I noted in #158:
> getRectEx() was introduced in #51 and #52 (it could have been made simpler by just passing an optional parameter to the existing getRect()).
and while trying to fix other things, when not really knowing which of the 2 will be called, I often have to put the same printf or tries for fix in both, which complicate things.
Pinging @frankyifei for comments and ack, as he added it in #52.
A full diff of getRect and getRectEx shows as:
```c
--- getrectClassic.cpp  2018-05-15 15:40:17.687306044 +0200
+++ getrectEx.cpp       2018-04-22 13:32:41.144950452 +0200
@@ -1,202 +1,206 @@
-/// returns caret rectangle for pointer inside formatted …
```

Factorize ldomXPointer::getRect() and getRectEx()

---

crengine/src/lvdocview.cpp

In some edge cases, the xpointer obtained from getBookmark() (to just get the xpointer to top of current page) could point to previous page.
But we can check if it does and increase y until we find one that is in current page.
For example, with these 2 pages of a book:
<kbd>![image](https://user-images.githubusercontent.com/24273478/40586090-975b0a00-61bc-11e8-852a-84d65a64be86.png)</kbd>
<kbd>![image](https://user-images.githubusercontent.com/24273478/40586111-0316fd9e-61bd-11e8-9104-c768739d4349.png)</kbd>
If you leave the book on this second page, when re-opening, you would get back to the first page.
The xpointer saved is `["last_xpointer"] = "/body/DocFragment/body/div[30].0"` and it points to the div containing the image of the first page, whose border is supposed to be on the …

Fix getting xpointer to current page

---

cr3gui/data/epub.css
crengine/include/fb2def.h
crengine/src/lvrend.cpp
crengine/src/lvtinydom.cpp
fb2props/FictionBook2.2.xsd

As discussed in https://github.com/koreader/koreader/issues/3987#issuecomment-392607363 and followups.

fb2def.h incremental update

---

crengine/include/lvstyles.h

Try to please clang 2: avoid compiler errors

---

crengine/include/hyphman.h

Follow up to #206
(also needs to be updated in cre.cpp)

Update reference to default english hyph dict

---

crengine/src/lvtinydom.cpp

Needed to force a new rendering with the page-break: avoid on borders change.
(I too often forget to do that when it's needed...)

Bump FORMATTING_VERSION_ID

---

cr3gui/data/hyph/French.pattern

Corrected a typo for "désir" and added a rule for "souffle" to be sure it will be OK when optional rules are enabled.

french.pattern

---

.gitignore

ignore mac junk files

---

crengine/src/lvfntman.cpp

I like it, but it's just way too expensive given how things are
implemented right now.
re #230

Revert the HB w/ proper load_flags experiment

---

cr3gui/data/hyph/French.pattern

adding the rule `<pattern>o2s </pattern>` to disable `photo-s`

Update french pattern again

---

cr3gui/data/hyph/French.pattern

for the word désir
revert 380 and edit 1886 and 1887
`<pattern> dé3s2i3r</pattern>`
`<pattern> dé3s2i4r </pattern>`
`<pattern> dé3s2i4rs </pattern>`

Update French pattern

---

crengine/include/lvtinydom.h
crengine/src/lvtinydom.cpp

Might be useful for moving highlights edges, cf https://github.com/koreader/koreader/pull/4582.

Adds ldomXPointerEx::prevVisibleChar() and nextVisibleChar()

---

.codacy.yml

Mainly to ignore what would otherwise be a lot of useless noise.

[CI] Add .codacy.yml

---

crengine/src/lvtinydom.cpp

Might be needed with https://github.com/koreader/crengine/commit/f2b30e15df3b84822abd9c4ec9233ca524225483 (#265) to avoid cache issues (https://github.com/koreader/crengine/pull/265#issuecomment-468037995).

Bump CACHE_FILE_FORMAT_VERSION

---

crengine/src/lvtinydom.cpp

I always forget to do that, but it's needed by the 2nd commit of #280.

bump cache file format version

---

crengine/qimagescale/qimagescale.cpp

`posix_memalign`  is API >= 16 :/.

Android build fix after #282

---

crengine/qimagescale/qimagescale.cpp

Should have read the bug report 'til the end :D.

Oh, apparently it's sometimes broken on API 16, too. Yay Android.

---

crengine/src/lvstsheet.cpp

Both `.cls1 .cls2 .cls3` and `.cls1.cls2.cls3` (which have different meanings) would not be parsed correctly (while `.cls1 div.cls2 div.cls3` was working).
Other combinations like `#someId.cls1[someAttr=val]:first-child` would fail too :)
(Some links about these kind of combinations: http://galjot.si/combining-css-selectors https://css-tricks.com/multiple-class-id-selectors/)
Also fix some specificity computation error.
Tested with that kind of stuff:
```html
<style>
.test1 .test2 .test3 { color: red; }
.test1 .test3 { background-color: yellow; }
.test1 ~ .test2 ~ .test3 { color: red; }
.test2 ~ .test3 { background-color: yellow; }
.test1.test2.test3 { background-color: black; color: white }
</style>
<div class=test1>
<div class=test2>
<div class=test3>
text in test1 test2 test3
</div> …
```

CSS: fix parsing of multi classnames and attributes selectors

---

cr3gui/data/hyph/French.pattern
crengine/src/hyphman.cpp
crengine/src/lvtinydom.cpp

```
<pattern> cy1be2r1</pattern>
<pattern> cybera2</pattern>
<pattern> cybere2</pattern>
<pattern> cyberé2</pattern>
<pattern> cyber3h2</pattern>
<pattern> cyberi2</pattern>
<pattern> cybers2</pattern>
<pattern> cybe3rien</pattern>
```

dealing with cyber- words

---

crengine/src/lvdrawbuf.cpp

re: https://github.com/koreader/koreader/issues/4986
(Basically, only invert post blending, and fake a background for transparent pixels).

Make our nightmode trickery behave with transparent images

---

crengine/src/lvdocview.cpp

Instead of showing the following when a file is less than 5 bytes:
<kbd>![image](https://user-images.githubusercontent.com/24273478/70340607-5ffc2880-1851-11ea-8356-c0dd25b4c246.png)</kbd>
Should allow closing https://github.com/koreader/koreader/issues/5669.
(The diff shows too much, as it's mostly indentation and tab>space fixes in that section.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/322)

Open (as text) small or empty files

---

crengine/include/lvdocviewprops.h
crengine/include/lvfnt.h
crengine/include/lvfntman.h
crengine/include/lvtextfm.h
crengine/include/lvtinydom.h
crengine/src/lvdocview.cpp
crengine/src/lvfntman.cpp
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp

See commit messages for details.
Discussion and screenshots at https://github.com/koreader/koreader/pull/5628#issuecomment-622354587
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/341)

Tunable use of letter spacing for justification

---

crengine/include/lvtinydom.h
crengine/src/lvtextfm.cpp
crengine/src/lvtinydom.cpp

Will allow closing https://github.com/koreader/koreader/issues/6394 and https://github.com/koreader/koreader/issues/6391 . Details in these issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/358)

Fix possible crash with embedded fonts, and when more than 64 nested elements

---

cr3gui/data/hyph/German.pattern

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/375)

updated hyphenation patterns for German

---

cr3gui/data/hyph/German.pattern

Another update of the German patterns (roughly 800 changes)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/406)

update of German patterns

---

crengine/src/lvstring.cpp
crengine/src/lvtextfm.cpp

As discussed in the tail end of #409 
----
Also includes @zwim's fix for #412
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/421)

resizeImage logic fixes

---

crengine/src/lvdocview.cpp

Status-line: add symbol if charging, when battery state is shown in percent.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/425)

Status-line: add symbol if charging, when battery state is shown in percent.

---

crengine/src/lvimg.cpp

* Avoid unnecessary per-scanline allocs in PNG
* Defer BGR swapping and alpha padding to libjpeg-turbo
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/426)

LVImg: Simplify JPG & PNG decoding 

---

crengine/src/lvimg.cpp

* Get rid of redundant NULL guards around free/delete
* Switch to BGRX and a mask instead of BGRA and an XOR (the former is
bound to be faster, and the latter might be more easily vectorized).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/427)

LVImg: Tweak JPEG decoding some more

---

crengine/include/lvplatform.h

`>_<"`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/434)

Fix DISABLE_CLOEXEC

---

crengine/src/lvxml.cpp

Fix for #448
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/449)

Fix loading EPUBs containing XML files starting with the byte order mark (BOM)

---

cr3gui/data/hyph/German.pattern

These are the newly updated patterns.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/455)

Updated German patterns

---

crengine/src/lvstream.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/459)

Fallback to stat64 on EOVERFLOW error

---

crengine/src/lvdocview.cpp

This should fix https://github.com/koreader/koreader/issues/8790
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/465)

Status line correct 00:15->12:15 AM

---

crengine/src/hyphman.cpp

Previously, hyphenation could happen between a letter and its diacritic, leaving the diacritic dangling on next line. Explanation why at https://github.com/koreader/koreader/issues/8977#issuecomment-1091997812.
So, be sure we correctly skip diacritics/modifiers: remove them from the word to be matched, and when applying flag to the input string, be sure to apply any flag after any diacritic.
As some pattern files (Latin, Greek) do contains some diacritics, check which are present at load time, and don't skip these ones (and only these ones): this should ensure existing patterns will still match what they aimed at, but it expects the patterns to handle all cases with these diacritics (which may or may not be the case for Latin and Greek).
Should allow closing …

Hyphenation: handle combining diacritics better

---

crengine/src/lvimg.cpp
crengine/src/lvtinydom.cpp

Companion to https://github.com/koreader/koreader-base/pull/1511.
Should allow closing https://github.com/koreader/koreader/issues/9240.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/487)

LVImg: add support for WebP images (with libwebp)

---

crengine/src/lvfntman.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/500)

Fonts: fix possible memory leak

---

crengine/include/lvstream.h

- fix `GetMode`: `LVNamedStream` implementation always returns `LVOM_ERROR`, which in turn breaks `getcrc32`.
- fix `Seek(…, LVSEEK_CUR, …)`: convert to absolute seek of the underlying stream to ensure seeking is done from the correct position.
- fix `Read`: don't allow reading past the fragment's end
I noticed those issues when testing the support for opening a document from within another archive. I'm not sure if that's actually a reachable/supported case when using KOreader (I tested by patching `LVDocView::LoadDocument` to load a test file).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/502)

LVStream: fix `LVStreamFragment` implementation

---

crengine/src/lvimg.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/531)

lvimg: fix leak on image decoding error

---

crengine/include/lvtinydom.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/535)

lvtinydom: minor simplifications

---

crengine/src/lvstsheet.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/541)

lvstsheet: minor cleanup

---

crengine/src/lvstring.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/539)

lvstring: minor cleanups

---

crengine/src/lvfntman.cpp

Which would trigger a use after free.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/546)

lvfntman: fix stupid mistake

---

crengine/src/lvstring.cpp

remove unnecessary assignment
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/571)

lvstring: optimize Utf8ToUnicode

---

crengine/src/lvfntman.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/573)

lvfntman: add error traces for some freetype calls

---

utils/lint.mk

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/594)

ci: remove leftover debug statement in lint tool

---

crengine/include/lvtinydom.h
crengine/include/lvxml.h
crengine/src/crtxtenc.cpp
crengine/src/docxfmt.cpp
crengine/src/hist.cpp
crengine/src/hyphman.cpp
crengine/src/lvfntman.cpp
crengine/src/lvxml.cpp
crengine/src/odtfmt.cpp
crengine/src/odxutil.h
crengine/src/wordfmt.cpp
utils/lint.mk

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/596)

fix a number of clang tidy warnings

---

.github/workflows/build.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/608)

ci: fix libunibreak installation

---

crengine/include/lvimg.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/614)

lvimg: minor cleanup (dead code)

---

crengine/src/lvstring.cpp

Don't mangle non-encoded non-ASCII characters.
Partially fix koreader/koreader#12656 (the file manager's part).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/615)

lvstring: fix `DecodeHTMLUrlString` implementation

---

crengine/src/lvtinydom.cpp

See https://github.com/koreader/koreader/pull/9072#issuecomment-3361953034
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/crengine/635)

lvtinydom: buildSyntheticPageMap(): clean page info
